### ISSUE TITLE
uploading zip file

### ISSUE THREAD

**Issue by j-hn** [microsoft/appcenter#1003]
we currently distribute our windows (wpf) apps using hockeyapp. our app installers are built with wix, and contain custom bootstrapper, so the installer is an exe. in hockeyapp we upload the installer as a zip, which has been working fine.
in appcenter we've been told this is supported, but when we try we get a "version cannot be created from build" error when we upload the zip.
![image](https://user-images.githubusercontent.com/8558576/64604323-d952bf00-d3b9-11e9-9c79-041cebe9c911.png)

so we cant continue. how do i specify a version so we can continue?

thanks

John

**Comment by Oddj0b** [comment]
Hi John, I think @botatoes or @derpixeldan can help you with this problem.

**Comment by winnieli1** [comment]
Hi @j-hn - can you check if your app platform is WPF? You can go to the settings page to check: 
![image](https://user-images.githubusercontent.com/8868628/64719943-2ef09f80-d47e-11e9-9ced-5345b1268710.png)


You might be experiencing this because your app is labeled as UWP. If that's the case, you can reach out to our support team via the blue chat bubble and we can change the app platform for you. Thanks!

**Comment by j-hn** [comment]
Thank you @winnieli1 this has fixed our problem :)
