### ISSUE TITLE
iOS app for AppCenter

### ISSUE THREAD

**Issue by vanlooverenkoen** [microsoft/appcenter#1018]
Where can I download this iOS app to install iOS apps ?

![image](https://user-images.githubusercontent.com/21172855/64791986-e4078280-d578-11e9-8f74-4512dfe5ff62.png)

**Comment by derpixeldan** [comment]
@vanlooverenkoen @dutchme333 sorry for the mis-leading image, it was indeed a real app to browse and download releases in the early days of App Center. Unfortunately, Apple doesn't allow a store-like app in the App Store, hence we can't release it and also won't be able in the future.

I'm closing this ticket as there's no point of keeping it open, since it's not in our power.

**Comment by vanlooverenkoen** [comment]
Hmm I find it hard to bellieve that you can't build an app that is just available with a public appcenter link. It would be the same as a the android hockey app download. We simple downloaded the apk from the hockeyapp website. I think this should not be closed.

I think you should consider your own distribution platform.

**Comment by derpixeldan** [comment]
@vanlooverenkoen that's not how Apple works. You can either release to the store or you're limited to the device cap of an ad-hoc profile. Enterprise (in-house) profiles are not allowed to be released publicly, otherwise Apple will ban the entire account.

I can assure you that we tried, but as I said, it's not allowed.

**Comment by vanlooverenkoen** [comment]
Did you consider pwa's?

**Comment by vanlooverenkoen** [comment]
This biggest advantage we have with the mobile app is that it will keep you logged in. For iOS with every new release we have to log back in. That is just a pain for our testers and clients. We want something like android on iOS.
