### ISSUE TITLE
Dipslay events in version greater than

### ISSUE THREAD

**Issue by ivanicin** [microsoft/appcenter#1063]
**Describe the solution you'd like**
In the Analytics > Events you can pick either all versions or just a single version. However it happens that something is changed in some particular version and data before that is irrelevant, but the data after that is spread across multiple versions

**Describe alternatives you've considered**
Right now you could export data to Azure, but this is really a simple case to require something like that.

**Additional context**

**Comment by jwargo** [comment]
@ivanicin thank you for this feedback, I'll share this with the service owner.

**Comment by hamswan** [comment]
Hi @ivanicin , If I understand correctly you are asking if you can view data relevant to say a particular version as a starting point and then versions above that, rather than starting from the very first version and view this on the App Center portal?

We don't have this currently and this is first time we are getting a request for this.

**Comment by ivanicin** [comment]
Yes, after some version some data might not be comparable to the past, I think it is relevant to every app out there.
