### ISSUE TITLE
Blazor Support

### ISSUE THREAD

**Issue by fileman** [microsoft/appcenter#1084]
Add support for Blazor especially WASM client-side

**Comment by jwargo** [comment]
@fileman can you please provide some more detail as to what you're looking for?  What service are you talking about? what support do you want?

**Comment by fileman** [comment]
Based on [this](https://github.com/microsoft/appcenter/wiki/Roadmap) services I'm talking about Auth, Data and Notification, they are good candidate for a SPA Blazor Client-Side running on WASM.
On Blazor Server-Side they aren't necessary since we can be use AzureADB2C.UI, EF Core with CosmosDB provider

**Comment by jwargo** [comment]
Had to make sure I understood what you meant, found this article: https://docs.microsoft.com/en-us/aspnet/core/blazor/?view=aspnetcore-3.0. I imagine we'd have to get to web support first, but I'll share this with the PM team to track.

**Comment by fileman** [comment]
Yes, is "Asp.Net Core" Blazor ["Client-Side"](https://docs.microsoft.com/en-us/aspnet/core/blazor/hosting-models?view=aspnetcore-3.0#blazor-webassembly) is something similar to WPF and WinForms, since it was executed into client browser on mono runtime webassembly.
In [roadmap](https://github.com/microsoft/appcenter/wiki/Roadmap) there is in General support for SPA (single page apps) and Blazor is SPA in C#

**Comment by catlan** [comment]
I would be very interested in the diagnostics part of App Center for Blazor client-side apps.

**Comment by enigmaturing** [comment]
I am also interested in AppCenter adding support for client-side Blazor webapps in the near future,. Single Page Applications built with Blazor should be able to consume services, (e.g. Authentication and Databases) just like Xamarin Apps can do at the present time. Ist this being considered for the near future?

**Comment by jlinstrum** [comment]
Apparently it is possible to use Azure Application Insights in a blazor app, so that may be something worth trying. Still, it seems like AppCenter is a significantly easier entry point to application analysis, and I agree it would be nice to have it.

Application Insights for Blazor:  https://github.com/IvanJosipovic/BlazorApplicationInsights

**Comment by BillyMartin1964** [comment]
You mark everything closed that you don't feel like doing.  Why don't you ever listen to your users?

**Comment by jlinstrum** [comment]
Hello Billy,

I believe this is the first email I have received from you. I have received a number of emails from different users, and I have always made an effort to reply to them and address their issues. If you have a particular issue you would like me to address, please feel free to write me again and let me know.

As for the crashes that pop up on appcenter, yes I do sometimes close those when I can't figure out what went wrong, but in many cases I have also figured out what the issue was and fixed it, and sometimes when I can't figure out the bug I put in more instrumentation to gather more data or make some changes that I think might fix it. It really just depends on how much information I managed to glean from the error message data. But if a user actually takes the time to write me an email and describe their problem and provide me with some information to duplicate the problem, I have always fixed the problem (although sometimes it takes time to get a release out).

The appcenter crash data was something that I set up so I could learn about that feature and maybe use it to improve the quality of my program a bit. It is imperfect, but it has helped me find and fix quite a few bugs. "Listening to my users" is something I do through email, and I provide my email address in several different places (the help files, the feedback button, my website).

Perhaps I should put a message on the error dialog box so people can email me when a crash is particularly irksome and they can give me more data. I will try to do this on my next release.

Meantime if you have pressing issues that you want addressed, I'm afraid you may need to put in a bit more effort and send me an email giving me enough information to duplicate the problem so I can fix it. Several users have done this in the past, and the end result has always been that the bug got fixed.

Regards,
John Linstrum




Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by jlinstrum** [comment]
Billy,

It just occurred to me that your message isn't even about my app (a very nice app called Visual RPN Calculator that you can get in the Windows app store).

Somehow your message on the Blazor Support · Issue #1084 · microsoft/appcenter (github.com)<https://github.com/microsoft/appcenter/issues/1084> got forwarded to me. I don't know why, I'm not a Microsoft employee, but I did comment on that thread.

You may feel free to ignore my other email as it is not the least bit relevant.

Cheers,
John Linstrum



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by BillyMartin1964** [comment]
Yeah, I get those too if I was EVER involved with the thread. In fact, still do years after. LOL

 

Working on anything new? Are you on Twitter or Discord?

**Comment by jlinstrum** [comment]
Hello again,

No, just plugging away on the same old app to the most part. I've done a couple of other test projects just to learn different things but I keep coming back to the one that I've actually put on the store and that has actual users.

Not really on twitter or discord.

I hope your programming journey is going well?

Cheers,
John Linstrum


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by BillyMartin1964** [comment]
Cool. Got a link? Android or Windows?
