### ISSUE TITLE
Android iOS: support handled exceptions 

### ISSUE THREAD

**Issue by easterapps** [microsoft/appcenter#1092]
Users would like the ability to track handled exceptions for Android and iOS apps. Currently, this feature is only available for Xamarin, Unity Apps and soon for UWP.

**Comment by winnieli1** [comment]
Hi @easterapps - thanks for submitting an issue. We have plans to bring handled exceptions support to Android very soon. No immediate plans for iOS yet but I'll keep this thread posted when I have updates. 

Thanks!

**Comment by gfinden** [comment]
iOS support would be good, too. Why would these not both be of equal priority?

**Comment by christianruppert** [comment]
We are currently also migrating iOS and Android App from Hockey to App Center
We are also using Fabric (instead of Hockey for some Apps)

Having support for handled exceptions is quite important for us too. We have figured out a hack (using our own class in your com.microsoft.appcenter.crashes namespace to call your non public saveUncaughtException)

But I would prefer an OutOfTheBox Solution. Do you have a release date for "very soon" yet?

:-)

**Comment by easterapps** [comment]
Hi @winnie 
what is the status of handled errors on iOS. We would use the function if it is equally available on Android and iOS.

**Comment by easterapps** [comment]
Unfortunately, this function is still not available on iOS.

**Comment by easterapps** [comment]
Unfortunately, this function is still not available on iOS.
