### ISSUE TITLE
Build configuration page does not load - 500 error in browser console

### ISSUE THREAD

**Issue by robkite** [microsoft/appcenter#1107]
We have an iOS Xamarin project that the App Center has been providing build and release for some time now (> a year).

We cannot currently open the build configuration page to change our provisioning profile etc. etc. and are rather stuck. Re-adding the same project as a new App sees the same issue, as has removing the existing build configuration and attempting to add a new one.

We always see a 500 server error in the browser console when trying to add / edit a build configuration on the following URL (using a GET call):
`https://appcenter.ms/api/v0.1/apps/<username>/<project-name>/branches/master/toolset_projects?os=iOS&platform=Xamarin`

We've tried multiple browsers and this issue has been ongoing for at least a week now.

Our source code is hosted in Azure DevOps and typically when we try to open the build configuration multiple times we hit rate limiting in our DevOps account which is obviously irritating.

**Comment by nrajpurkar** [comment]
Hi @robkite, thanks for opening this issue. We're taking a further look. Could you also open a support issue via App Center support. This will help us if we need any further details. Thanks!

**Comment by robkite** [comment]
Have already done and have linked to this issue.

**Comment by DennisPan** [comment]
If you are running into the same, could you let us know if your repository is also in Azure DevOps?

In the meantime, please reach out to support so that we can take a deeper look into your app 🙏

**Comment by DennisPan** [comment]
We figured out this is caused by latency in certain apis when it comes to larger repositories. When this happens, `/toolset_projects` api times out (currently 30 seconds). To address this properly, it becomes couple features, which we will look into. For short term mitigation, we can whitelist certain applications for a workaround we have in place. For anyone has a need of it, please reach out to support via App Center portal
