### ISSUE TITLE
Export the email addresses from a Distribution Group

### ISSUE THREAD

**Issue by pbearstare** [microsoft/appcenter#1132]
**Describe the solution you'd like**
When viewing a distribution group, have a button that allows you to export all the tester's email addresses

**Describe alternatives you've considered**

**Additional context**
This allows us to send additional notes/instructions to our test group

**Comment by tjsomasundaram** [comment]
Thanks, this request is noted as well! I will add this to our review.

**Comment by ericcjobes** [comment]
I would also find this feature beneficial, as finding if a user is in a sufficiently large distribution group is incredibly difficult because:
- there is no option to search within a distribution group for a user
- the list of users in a distribution group is not sorted aphabetically
- searching the list via ctrl-F only shows results visible on the current page (i.e. if a username scrolls out of view, it is no longer searchable)

**Comment by tychau21** [comment]
This feature is a must for handling large user group.  Currently we have a user group of members over 1000 and it is impossible to scroll through the list and find a user.

**Comment by deepforu47** [comment]
Any update on this? I guess this issue has been created Oct last year.
