### ISSUE TITLE
Read update Release Notes from a native view rather than the browser

### ISSUE THREAD

**Issue by fabiendem** [microsoft/appcenter#1134]
**Describe the solution you'd like**
While distributing Android updates via HockeyApp, it was possible for the user to read the release notes of the update from an in-app native view.

While distributing Android updates using the AppCenter Android SDK, if the user tap on "View Release notes", the user is sent to the Browser on the dedicated web page of the project where the release notes are visible.

It would be a bit more convenient for the user to be able to read those notes while staying in the app.

**Describe alternatives you've considered**
A short term alternative is to write a custom in-app dialog showing the release notes within the app.
https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#customize-or-localize-the-in-app-update-dialog

**Comment by tjsomasundaram** [comment]
Hi! Thank you for the feature request. I will take this back to the team for review and addition to the backlog.

**Comment by Younes-L** [comment]
Has this been addressed yet ? I see a different dialog now

**Comment by Younes-L** [comment]
This is still a regression from hockeyapp, where it was possible to see release notes of multiple previous updates and not just the latest one.
In situation where user is updating from v1 to v3, skipping v2, with hockeyapp they could still read the release notes of v2, but with appcenter it's not the case.

In brief, please mimic the behaviour of hockeyapp with a "show more" button that displays release notes of previous versions within the update dialog box, instead of opening a link in browser
