### ISSUE TITLE
Download Binary File

### ISSUE THREAD

**Issue by narayan8291** [Microsoft/appcenter#115]
**Describe the solution you'd like**
I have been using HockeyApp to download the latest version of a mobile app (.apk or .ipa). I don't see an option to download the binary from App Center. Is it possible to have a way to download a specific binary from the App Center?

**Comment by kaischo** [comment]
This is already possible. Go to Distribute->Releases and chose a build. The download button is at the top right.

I think this feature is not finished yet, because it still links to hockey app.
I would love to see this option on the main download page like it was on the hockey app download page: Clicking install on mac/pc downloads the ipa, clicking the button on mobile devices installs the app.

**Comment by patniko** [comment]
@kaischo is correct. We are also working on this related issue #82 in March to enable you to download from the install portal on unsupported devices.

**Comment by lumaxis** [comment]
@narayan8291 @kaischo Issue #82 that @patniko mentioned is now closed, we now offer to "Download" a binary on platforms where it is not directly installable. e.g. for `.ipa` files on macOS.
Closing this for now, please let us know if there still anything you'd like to see improved! 👍🏼
