### ISSUE TITLE
Silent SignIn

### ISSUE THREAD

**Issue by ibraheemhlaiyil** [microsoft/appcenter#1151]
**Describe the solution you'd like**
In order to determine whether a user has ever signed in:
The ability to call a silent sign in as the first call to Auth

**Describe alternatives you've considered**
Keeping persisted local state to indicate whether the user has ever signed in or not on the device.
Completely customising presentation of the auth flow which is overkill.

**Additional context**
Use case - user downloads app and opens up the app. User is presented with a button to initiate sign in or sign up.
Next time user opens the app, they will need to be presented with the same button.
Of course, the app can attempt to silently auth the user and skip presentation of the button the second time. But, in that scenario, if it is the user's first time opening the app, the first thing they will see is the auth views. The requirement is that they see something else descriptive before they are directed to the auth flow, but that this is skipped if there is a current valid auth.
Looking at the source code, it shouldn't be too much to implement a `signInSilently()` or `hasValidAuth()` function and parse the results to see if the user should be presented with a "sign in/sign up" button, in the same way the existing `signIn()` function works, or continue to the authenticated areas of the app. Alternatively, the existing `signIn()` function can be overloaded with a `bool silent` parameter.

**Comment by amchew** [comment]
Hey @ibraheemhlaiyil, thank you for reaching out and sharing your feature request! I see your user scenario:
1. Check if the user is signed in, 
2. Show an alternate screen if so
with a isSignedIn() e.g. method. 

You can do that today, but it's not exactly elegant. 

To do so, 
1. call the `signIn()` method (for example, in the [Auth Andriod SDK](https://docs.microsoft.com/en-us/appcenter/sdk/auth/android#sign-users-into-the-app))
2. In the else statement of the `signIn()` method, you can edit the code to modify the user experience when the user has signed in to show an alternate screen, etc. The signIn UI wouldn't appear again: if the app calls signIn again, the SDK shows the sign-in UI again only if the saved sign-in information expired or was revoked by the authentication server. 

The feature is on our backlog, but ETA so far unfortunately. I'll leave this feature request here, and if you're keen on this feature, please give it a thumbs up.

**Comment by ibraheemhlaiyil** [comment]
I suppose it's related to #860 with regards to silentSignIn.
However, it would be useful to also retrieve from Auth, whether a user has signed in previously, to support "new user" or "try to sign in again" flows, without having to store data to indicate this.

**Comment by RedChops** [comment]
This is an older issue, but I'd like to bring it back up again. I'd love a way to know, through Auth, if a user has already signed in before.

I can't use the workaround described above with Xamarin Forms because there is no `else` statement in the `signInAsync()` method, so the method either returns me auth details or pops a sign in screen with no way around it. Quite sloppy from a UX perspective - if their login details have expired for some reason I would like to present some kind of reasonable UI to show that yes they still have an account, but they need to login again.

This is kind of a big problem with my starting view containing resources from Data. I want to take the user to the app as soon as possible. What I had tried was to store a boolean in the apps shared preferences noting that they've logged in before so I can optimistically get to the main view while refreshing their auth credentials, but that fails miserably if the auth token has completely expired and they must login again.

**Comment by Zakeelm** [comment]
Thank you so much for your request and valuable feedback. We announced this week in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Auth and Data services later this year and recommending customers transition to Azure Active Directory B2C and Azure Cosmos DB instead. Let me know if you have any additional questions about this transition and i'll make sure to get them answered! Closing this issue.
