### ISSUE TITLE
Maven appcenter distribute artifact seems to be unpublished for 2.4.0

### ISSUE THREAD

**Issue by luisnaranjo733** [microsoft/appcenter#1155]
The AppCenter distribute [documentation ](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#1-add-the-app-center-distribute-module)suggests declaring the native android dependency with a specific version like this:

```
dependencies {
   def appCenterSdkVersion = '2.3.0'
   implementation "com.microsoft.appcenter:appcenter-distribute:${appCenterSdkVersion}"
}
```

However, changing the appCenterSdkVersion to the latest release (2.4.0) results in an error.

> ERROR: Failed to resolve: com.microsoft.appcenter:appcenter-distribute:2.4.0

 It appears the module that corresponds to the latest release is not published in maven. Either that, or the versioning scheme is misleading.

**Describe the solution you'd like**
Locking the native dependency to the current release should be possible. Having the versioning scheme be the same on npm and maven implies that they should be locked side by side. Making this not possible implies risk that they won't work together.

**Describe alternatives you've considered**
This works if you use the "+" syntax. It probably pulls in the 2.3.0 maven artifact, which again, doesn't seem to align with the npm version.
.

**Comment by fabiendem** [comment]
@luisnaranjo733 

What's misleading is that the github repo https://github.com/microsoft/appcenter-sdk-android shows the `develop` branch by default rather than the `master` one.

At time of writing, the version 2.4.0 is on their `develop` branch, not `master`, so it's kind of expected imo.
https://github.com/microsoft/appcenter-sdk-android/blob/master/versions.gradle
https://github.com/microsoft/appcenter-sdk-android/blob/develop/versions.gradle

And version 2.4.0 is marked as under development at https://github.com/microsoft/appcenter-sdk-android/blob/develop/CHANGELOG.md#version-240-under-development

**Comment by luisnaranjo733** [comment]
Great point, I had not realized that. Totally agree that it's misleading that the GH repo shows the develop branch. That definitely seems like it would be a common source of confusion

**Comment by MatkovIvan** [comment]
Hey @luisnaranjo733,

As already mentioned above, 2.4.0 is not released yet.

The latest release on [GitHub](https://github.com/microsoft/appcenter-sdk-android/releases) and [Maven](https://mvnrepository.com/artifact/com.microsoft.appcenter/appcenter) is 2.3.0

Our docs is also point to 2.3.0 as it's the latest version for Android. So, I'm curious why you thought that it isn't the latest one?

**Comment by MatkovIvan** [comment]
Ah, "npm". React-Native, right?
It was updated to bring the fixes from iOS native SDK, but it uses Android SDK version 2.3.0 since it's the latest one.

> that they won't work together.

Android and iOS versions may not match (but they usually do). Currently React-Native SDK wraps Android 2.3.0 and iOS 2.4.0 SDK. It's definitely intended and the compatibility is verified, no worry.

**Comment by MatkovIvan** [comment]
Hi, we haven't heard from you in a while so I'm closing this issue. Please reopen/comment if you have more questions or run into this again.
