### ISSUE TITLE
Install an app via command line + auto update

### ISSUE THREAD

**Issue by Frank1234** [Microsoft/appcenter#116]
**Describe the solution you'd like**
Install an app via command line and have the app auto-update afterwards (on Android).

When we `adb install` an apk, the app will not auto-update, even if the release/distribution is public. I would like to have this functionality.

I implemented auto-updating, but it currently only works when downloading the app from the App Center installation url by clicking the download button. We would like the feature when installing via command line.

**Describe alternatives you've considered**

Creating our own (in-app) update service using the public (App Center) API's. Downloading the new version APK in the app itself and replacing 'myself' on updates. Drawback: dodgy implementation. When update fails, there is no state/app left to return to.

**Additional context**

Found this in the docs: "At this time, there are some limitations to In-App Updates: In-app updates only work for public distribution groups if testers have downloaded the app from their default browser with cookies enabled" - https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android

**Comment by Oddj0b** [comment]
In-app updates only work in conjunction with our distribution service because of how the SDK polls for a
 newer version. And as App Center is a cloud solution with no immediate intention of creating on-premises software, I don't think this feature will be implemented any time soon.

Thank you for your contribution, if you reach out to us through the blue bubble I hope we can find a working solution together.
