### ISSUE TITLE
App Center Bug Tracker for DevOps Tags

### ISSUE THREAD

**Issue by thbong** [microsoft/appcenter#1165]
**Describe the solution you'd like**
I'd like App Center bug tracker service to allow defining custom tags for DevOps.

**Describe alternatives you've considered**
The only alternative is to click on each work item and click on the link to see which app the bug belongs. We'd like to define custom tags as our team has multiple versions of our apps(alpha, beta, etc.) and filter by tags in the backlog without having to click on each work item and check which app the bug belongs.

**Additional context**
App Center automatically attaches an "appcenter" tag to the work item created for the crashes. If you try to define custom tags, which HockeyApp allows you to do, the work item will fail to get created because there's a conflict for the tag. Tags allow you to quickly identify which bugs are present in which version and filter work items, etc.

**Comment by kensykora** [comment]
For what it's worth, this feature used to be available in AppCenter and just recently (last few months) it broke. The ADO connector used to allow to set custom properties, including tags. We depended on this behavior since we have multiple build types in our AppCenter (Alpha/Beta/Store) and different platforms (iOS/Android) so tagging is needed to do this.
