### ISSUE TITLE
Cannot install App Center Profile on Ipad Air 2 with iOS 13

### ISSUE THREAD

**Issue by zjx** [microsoft/appcenter#1186]
when goes to https://install.appcenter.ms/profile to add a new device on an ipad air 2 with iOS 13, there is no popup to let customer to install the profile.

Also tried on an ipad air with iOS 12.4, no such error occur.

Does the app center website supports iOS 13 version already?

**Comment by lumaxis** [comment]
@zjx The website should show you a warning banner at the top. You need to use the "Request Mobile Site" option in the website settings as otherwise App Center is not able to recognize that the device that you're using is an iPad. See https://github.com/microsoft/appcenter/issues/543#issuecomment-520152579

**Comment by zjx** [comment]
Thanks @lumaxis, the workaround works for me.
