### ISSUE TITLE
[In app updates] Feature couldn´t be enabled

### ISSUE THREAD

**Issue by manuelmolerobusto** [microsoft/appcenter#1190]
Hi,

We get an error message trying to update an application in app center distribute. After downloading app from appcenter link (mail notification) and install app, we get "Feature couldn´t be enabled" screen in chrome browser, in Android device.

After that, one pop-up is showed in Android app alert us our app was installed side load or private browser.

Someone can help us?

Screenshot is attached.
![appCenter](https://user-images.githubusercontent.com/32092307/66756934-5088e080-ee9b-11e9-981a-9d2e98162db0.png)

**Comment by derpixeldan** [comment]
@manuelmolerobusto please reach out to us via support so we can better investigate the issue. You can mention this ticket and provide more information about the app/device/platform.

**Comment by AnastasiaKubova** [comment]
Hi! Sorry for the long response. When an application is downloaded from the link, the SDK saves important information from cookies to check for updates later, otherwise the SDK doesn’t have that key information (please [see](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/android#how-do-in-app-updates-work)). If you get this issue please:
- Make sure that you install the app from the App Center install portal. 
- Try to clean the browser cache and try to login again.

I am closing this issue but feel free to reopen it if this issue still persists.
