### ISSUE TITLE
Add support to indicate the environment or release type of an app

### ISSUE THREAD

**Issue by derpixeldan** [microsoft/appcenter#120]
**Describe the solution you'd like**
A string field to specify the environment of the app. On HockeyApp it's called "Release Type" and can be specified in the app settings.

**Describe alternatives you've considered**
Another option would be to write it in the name of an app but that's cognitively harder to recognise than having a dedicated field for it.

**Additional context**
This is important for HockeyApp users which will soon be able to move and still want to differentiate between their app environments.
![screenshot 2019-02-27 at 18 28 49](https://user-images.githubusercontent.com/3369400/53510141-92f0df00-3abd-11e9-9187-9fa060eeee70.png)

**Comment by bsimser** [comment]
Would like to see this available as a variable or something we can pull out in our scripts. The typical thing is to have different configurations for each environment but the environment support in App Centre right now doesn't seem to support that. In order to have an app point to a dev, test, and prod endpoint I have to make separate releases or do some funky things with my branches. Any deployment system (Octopus, etc.) has the ability to specify these settings per environment. So if that's what this is, then would like this scriptable so we can make the necessary changes to configuration files based on that environment.

**Comment by mkm12789** [comment]
I noticed this has been implemented for the Desktop UI but not mobile. Is there a separate ticket for the mobile UI?

**Comment by derpixeldan** [comment]
@mkm12789 yes, it has been implemented in the desktop UI only so far. We will be working on the mobile UI in a separate effort when we're integrating the install page with developer portal (FYI @botatoes)
