### ISSUE TITLE
IOS13 support with Appcenter using Appium 1.15

### ISSUE THREAD

**Issue by KS261187** [microsoft/appcenter#1203]
**Describe the solution you'd like**
I would like to use Appcenter to run my test cases against IOS13 using Appium 1.15. Currently the version supported by AppCenter is 1.11.0 which supports only till 12.4.1. I am able to see iPhone 11 devices in Appcenter but unable to use any of them since Appium 1.15 is not supported in AppCenter.

**Describe alternatives you've considered**
When trying to execute my tests against Appium 1.11 in AppCenter the test stalls and yielding no results.

**Additional context**

**Comment by amchew** [comment]
Thanks @KS261187 for sharing! @Oddj0b would you mind taking a look?

**Comment by King-of-Spades** [comment]
@Oddj0b @amchew Appium's release notes indicate that the version 1.15 supports iOS 13/Xcode 11: https://github.com/appium/appium/releases/tag/v1.15.0

I have seen evidence that at least some launch tests can complete on iOS 13 devices even with our current Appium support, however this may be specific to launch testing and not general functionality; I imagine this update is noted in Appium's release because it is at least recommended, if not required for normal testing functionality.

**Comment by KS261187** [comment]
Yes the App does launch in Appcenter with the current Appium version. However there are some inconsistencies like when i try to get the page source using Driver.getpagesource() command on IOS13 devices, i am getting an unknown server and the tests goes to the exception block. I tried running this locally with the Appium 1.15 and it works fine. This is one example. I can certainly attach the test run along with the logs, if that helps. I would appreciate, if the team can look into the upgrade as early as possible, since my organisation heavily relies on test cloud to execute regression test cases. Currently we are unable to run any of the tests against IOS 13 devices in the device farm.

**Comment by King-of-Spades** [comment]
Thanks for confirming that @KS261187.

**Comment by mohanrajmcad** [comment]
Team, 
Could you please accelerate the upgrade to latest appium version. I remember that Its took around 6 months to upgrade appium 1.11 version last time from the previous version. Thanks.

**Comment by caisd1998** [comment]
For my test, when using 1.10 for iOS 13, elements can't be found to be clickable, no problem for iOS 12.
I'm using following code:
`(MobileElement) new WebDriverWait(driver, TIME_OUT_IN_SECONDS).until(ExpectedConditions.
                elementToBeClickable(MobileBy.AccessibilityId(accessibilityId)))`
In Appium Log, I can see that checking element clickable is done by two steps:
1. Find that element.
2. Once found, check if that element is "displayed".
There's no problem in step 1, but in step 2, the "displayed" HTTP GET request always returns with value of false. Finally I get time out on finding element to be clickable.

**Comment by caisd1998** [comment]
I'm having another big issue. Each test needs at least 10 mins to start. Appcenter support investigated this and found: "The webdriver agent is taking a very long time to realise that the app has launched. Since you are not seeing this with Appium 1.15 i will assume that the issue will be fixed once appium is upgraded. "
So without the upgrade, iOS device test is useless in practice.

**Comment by Oddj0b** [comment]
We're internally testing the latest Appium upgrade and would like your help. If you want to test Appium in version 1.16 in App Center Test, all you have to do is add a `--test-parameter pipeline=appium-v1.16.0` switch when submitting your test. If you have problems, please don't hold back and let our support know.

**Comment by Oddj0b** [comment]
Appium 1.16 is the default version for all Appium Test runs and the `--test-parameter pipeline=appium-v1.16.0` is no longer required.
