### ISSUE TITLE
Distribute is not checking for updates when application is resumed (only on first startup)

### ISSUE THREAD

**Issue by Bishbulb** [microsoft/appcenter#1205]
**Background**
We are migrating a system from HockeyApp to AppCenter. We have a line-of-business application that is usually the only app that is running on the Android device where it is being used. In this situation, it is critical to the business that we are able to push mandatory app updates and have them be processed by the client applications within a relatively short timeframe (ie. a few hours, ideally no more than 1 hour). 

Right now we are considering this a show-stopping issue on our end. We cannot migrate to AppCenter until we are able to get this functionality working as expected.

**Issue**
With AppCenter's Distribute module, I have never been able to get it to trigger an in-app update for an app that is already launched and running. If I force kill the app and re-launch it, I will always see the in-app update notification dialog and the workflow works great. However, if the app is just running (as will be the case 99% of the time for our users), we don't observe the update dialog being shown. 

**What I expected based on the docs**
In the [docs](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#how-do-i-test-in-app-updates) it mentions the following:
> Members of the Distribution Group will be prompted for a new version the next time the app enters the foreground.

**What I've tried**

- Sending the app to the background for a while, then bringing it to the foreground (no in-app update dialog is shown)
- Waiting for an hour and then bringing the app into the foreground (no in-app update dialog is shown)
- Manually calling `AndroidDistribute.Instance.OnActivityResumed(activity)` from my main activity's `OnResume` method to try and force an update check

**Workarounds**

None that I'm aware of, but I'd welcome any feedback!

Thank you for your consideration on this matter.

**Comment by amchew** [comment]
Thanks @Bishbulb for sharing. @botatoes would you mind taking a look?

**Comment by franck-nadeau** [comment]
I used this as a workaround inside my main activity:

````
    @Override
    protected void onResume() {
        super.onResume();
        Distribute.getInstance().setEnabled(false);
        Distribute.getInstance().setEnabled(true);

        Distribute.getInstance().onActivityResumed(this);
    }
````

I hope it can help others.

**Comment by fabiendem** [comment]
I am having the same issue here, pretty bad. 
Reading the source code I don't really understand how the lifecycle methods are getting called in the Distribute module.

App will check for updates only if you kill it, rather than on resume as it should.
The adoption rate of updates will be pretty low with this.

This workaround won't work:
```
 @Override
    protected void onResume() {
        super.onResume();
		Distribute.getInstance().onActivityResumed(this);
    }
```

But @franck-nadeau 's trick will fix it.
I am just adding a `.get()` to make sure we run things synchronously:
```
 @Override
    protected void onResume() {
        super.onResume();
		
		Distribute.getInstance().setEnabled(false).get();
        Distribute.getInstance().setEnabled(true).get();

		Distribute.getInstance().onActivityResumed(this);
    }
```

Please keep in touch for a fix 🙏

**Comment by Bishbulb** [comment]
@botatoes I had a lengthy chat with AppCenter support about this, and they told me that this was currently working as designed and was not going to be changed.

I think for context, I'll paste in here what I wrote in the support thread:

> I find it hard to imagine how the use case we have (an internal app that is distributed to employees) is that rare/uncommon. I would be happy to build our own service that automatically polls for updates on an interval, but alas, that feature is also not in scope:
https://github.com/microsoft/appcenter/issues/1137#issuecomment-541246850
Overall, I'm disappointed as this means we will need to consider another service for distribution. That's too bad, because we had a great experience in the past with HockeyApp.

**Comment by fabiendem** [comment]
> this was currently working as designed and was not going to be changed

Damn, that doesn't make sense. The app rarely gets killed...

Even the source code suggests it should work:
https://github.com/microsoft/appcenter-sdk-android/blob/554205e9a53964f8e9b4080f5076c10a168976dd/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/Distribute.java#L469-L477

There must be a bug somewhere 😕 

Thank you @Bishbulb for sharing this and the initial report.

**Comment by Bishbulb** [comment]
@fabiendem Yes I also saw that in the source code and spent **hours** testing to try and get it to work, all to no avail. I haven't tried the combination trick of Enable/Disable + calling Instance.OnActivityResumed, so that gives me some hope that I can hack this to get it working. My alternative was going to be rolling my own update/distribution service, but of course I'd rather not have to do that.

**Comment by fabiendem** [comment]
@Bishbulb, @franck-nadeau

While testing the above, I was running on the AppCenter Android SDK 2.3.0.
With 2.3.0, while the user was tapping the app icon (without the "fix" above), it was not checking for updates.

I have just tried with the AppCenter Android SDK 2.4.1, and without the fix above, at least now it checks for the updates when the user taps on the Application icon.
This is better, so I will simply update the SDK.

**Comment by Bishbulb** [comment]
@fabiendem I agree that is better, but in my testing that wasn't working - I did the same thing where I started with 2.3.0 and then upgraded to 2.4.1. Curious to know how you have this setup - are you initializing AppCenter in your `MainActivity` or in the `Application`? 

Also, I just checked and it looks like 2.5.0 was released 2 hours ago, unfortunately nothing in the release notes indicating they fixed/changed this behavior:
https://github.com/microsoft/appcenter-sdk-dotnet/releases

**Comment by fabiendem** [comment]
🤣 
@Bishbulb 
When I tried 2.4.1 I installed the app via the browser, from the AppCenter download page. This was working, when the user taps the icon it checks for updates.

Then you said 
> but in my testing that wasn't working

I gave it a try again. But this time installing the first app using `adb install`. Then I simulated an update and tried to trigger the check by tapping the icon of the app. And nothing was happening. 😭 

And I remembered I made the initial try via the browser installation.
I tried this again and it's working.

➡️ Install the app via the browser rather than via `adb install`

--------

When you install your app via adb, the installer package name may be set to `null`.
Run `adb shell pm list packages -i com.yourpackagename` to check this.

In the source code of the AppCenter SDK, they check if you installed the app the expected way (not from an App Store) before checking for updates:

https://github.com/microsoft/appcenter-sdk-android/blob/4e109ce746ba93c0cc425cae598656d11f1a95b1/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java#L43-L50

https://github.com/microsoft/appcenter-sdk-android/blob/554205e9a53964f8e9b4080f5076c10a168976dd/sdk/appcenter-distribute/src/main/java/com/microsoft/appcenter/distribute/InstallerUtils.java#L81-L88

I _think_ the problem is that the `null` is then parsed as a String, and not listed in the `LOCAL_STORES` list.
This addition in the sdk may help 🤷‍♂  :
```
+	LOCAL_STORES.add("null");
```
