### ISSUE TITLE
Release script is not able to signe a renamed apk file.

### ISSUE THREAD

**Issue by Hesamedin** [microsoft/appcenter#1279]
**Describe the solution you'd like**
AppCentre supports different configurations for signing release builds. There is no problem when we have _release.keystore_ file under version control. However, I faced this problem when I uploaded _release.keystore_ on AppCenter (as well as putting its credentials over there).

The problem is, your signing script looks for the generic apk name. If I am not changing the name of the apk file then three is no problem and your script is able to sign the release build. However, your script fails the build if I change the name. This is the script I had in my app/build.gradle file.

```
applicationVariants.all { variant ->
    variant.outputs.all { v ->
        def date = new Date().format('ddMMMyyyy_HHmmss')
        def newName = "${variant.name}-${variant.versionName}-${variant.versionCode}-$date"
        v.outputFileName = new File(outputFileName, newName + ".apk")
    }
}
``` 
Above script changes the generic name, app-release.apk, to something like, release_3.15_315_29Oct2019_092753.apk. Renaming the apk file help us to prevent overring the previous version of the app when we push the apk file to Amazon S3, Google Bucket or etc to be used by testers or just for the backup.

**Describe alternatives you've considered**
I didn't have alternative so I removed the above code block from my build system.

**Comment by winnieli1** [comment]
Thanks for submitting an issue. I've tagged my colleague who will take a closer look.

**Comment by ranterle** [comment]
@Hesamedin Thanks for reporting this - I think it would be great if you can reach out to us through the support button in the App Center portal to better handle this since it sounds like there might be a bug investigation necessary.
Some things to consider: 
Our build signing step should not look for any specific APK, just for any APK under the `$module/build/outputs/apk` folder of your project. When you reach out, providing the URL to your build that fails will be useful.

**Comment by Hesamedin** [comment]
Hello @ranterle. Thank you for your advice. I reached out to your colleagues via email. They realized that something is wrong with variable naming and asked me to check my code to see am I changing the name. And they were right. I had the above code block in my code that was responsible to rename the apk file. By removing that, I am able to get my release build process passed.

That's why I thought it is good to report to you guys to let you know about this issue.

This is what your colleagues told me:
```
Ok from looking at the build, it seems that after the Gradle build is done, it leaves both an app-release.apk and app-release.apk.unsigned
Our postprocessing already cleans out anything with -unsigned but not .unsigned
this looks like fairly non-standard to have a file with that extension
can they check whether their Gradle configuration has anything configured for this?
```

**Comment by ranterle** [comment]
Nice, that was basically me through a different channel/colleague 😄 
I'm wondering how this might lead to both a `.apk` and `.apk.unsigned` to be created which then turns out to cause the signing step to fail.

Regardless, let me see how we can maybe improve our postprocessing. I can't make any guarantees on that we're able to ship it in the near future, a possible workaround for you would be to keep the APK file name "stock" during build and use a post-build script in App Center to rename it after.
