### ISSUE TITLE
Global distribution groups cannot be used over API keys

### ISSUE THREAD

**Issue by iAgentur** [microsoft/appcenter#1299]
**Describe the solution you'd like**
Global distribution groups (such set up under the team account) should also be addressable as distribution target over API.

**Describe alternatives you've considered**
sharing owner api key, but this is insecure and not logical, why a developer api key cannot be used.

**Additional context**
This currently only works with an API key created from account owner. I expect it to work also with one that belongs to a developer, which has all required permissions on app level.

Developers also don't see the global groups, how to give them permissions to do so?

**Comment by winnieli1** [comment]
Hi @iAgentur - thanks for filing an issue. What you're experiencing is actually by design. Users need have collaborator permission for the organization to view and manage shared distribution groups. If you make your app developers as org collaborators they should be able to view and target the shared distribution group.

You can read more about our permission models here: https://docs.microsoft.com/en-us/appcenter/dashboard/creating-and-managing-organizations#organization-roles

Hope that helps!
