### ISSUE TITLE
Increase file limit size for upload attachment API

### ISSUE THREAD

**Issue by hypherion2** [microsoft/appcenter#1341]
The errorAttachment API described here: https://docs.microsoft.com/en-us/appcenter/diagnostics/upload-custom-crashes#upload-an-attachment seems to have a maximum upload file size limit of 7Mb. 

First of all this is not documented on the page above and it took a lot of trial and error to figure out why my requests were denied with 400 error, until I found that platform specific SDK documentation does list the limitation (i.e. https://docs.microsoft.com/en-us/appcenter/sdk/crashes/macos under "Add attachments to a crash report").

Depending on how long the application has been running and how much information we need for troubleshooting, the logs we need may exceed 7MB.

HockeyApp did not have such a limitation.

**Comment by winnieli1** [comment]
Hi @hypherion2 thanks for submitting this issue. I'll update the upload crashes docs to be more clear. We have an item on our backlog to increase size limitation but unfortunately, due to other priorities at the moment, I don't have an ETA for you. 

We'll keep this issue open to monitor community interest. Thanks!

**Comment by glen-nicol** [comment]
Hi @winnie, thanks for adding the 7MB size limit to the docs. Can you clarify if it is 7MB per attachment or 7MB total between all attachment in the docs? Also, It looks like the limit is 7 mibibytes (MiB) not megabytes(MB) for what its worth.
