### ISSUE TITLE
Ability to sort apps by release date in App Install List

### ISSUE THREAD

**Issue by Sai** [microsoft/appcenter#1346]
**Describe the solution you'd like**
The current order of the apps (https://appcenter.ms/apps) & install apps (https://install.appcenter.ms/apps) list is sort by title, since we have more than 20+ apps to test, it would be better to have an option to sort the list by last updated like Hockey.

**Comment by derpixeldan** [comment]
Duplicate of #1138

**Comment by Sai** [comment]
@derpixeldan This is a different feature request, #1138 asks the sort feature in App Detail Page. Thanks.

**Comment by adammarks** [comment]
We are having problems with this issue,  people are looking on the install.appcenter.ms/app list which is available from the URL in the notification emails and not seeing the releases because they are used to seeing releases from appcenter.ms/apps list.   Because of the sorting difference people are thinking they aren't getting releases and/or thinking that there are permission problems.

**Comment by logicallayer** [comment]
It would be great if we could change the default of app sorting to be by recent instead of build.

Always causing issues for us to sort by build
