### ISSUE TITLE
set a crash limit for automatic crash reports into services

### ISSUE THREAD

**Issue by iAgentur** [microsoft/appcenter#1357]
**Describe the solution you'd like**
Allow to define when a new crash group should be reported to a connected service (jira, github etc.) 

**Describe alternatives you've considered**
turning reportin off, currently I am flooded with hundreds of minor reports from old app versions.

**Additional context**
this was possible in hockeyapp, please fix and make it possible again.

**Comment by winnieli1** [comment]
Hi @iAgentur thanks for the feature request! This is on our radar and we have plans to improve our bug tracker experience and make it more customizable. Due to other priorities at this time, I don't have an ETA for you but we will keep this thread open to track interest and post updates if we have any.

**Comment by evnik** [comment]
This seems to be a related to #901

**Comment by jtorre39** [comment]
wondering if there's any update on this ! this seems to be a missing feature on the current AppCenter still !
