### ISSUE TITLE
Allow users to edit the Version names of my builds like I was able to do so in HockeyApp.

### ISSUE THREAD

**Issue by a-n-d-y-w-a-t-s-o-n** [microsoft/appcenter#1408]
**Describe the solution you'd like**
I'd like to edit the Version names of my builds so I can clearly distinguish unique builds for my clients. This was a feature in HockeyApp that was super easy for devs/admins.

**Describe alternatives you've considered**

**Additional context**

**Comment by Jonny-Boschan** [comment]
Agreed, the inability to be able to edit Version names like how we could in HockeyApp is a tremendous loss in functionality for AppCenter. This edit function was very useful in renaming if there was a naming error. We would also always add notes to distinguish what was added in new builds for our QA testers.

**Comment by ukandpal** [comment]
Exactly what we are looking for right now. It needs to be added asap.

**Comment by ahdbilal** [comment]
Thanks for all the feedback. We have added this feature in the backlog.

**Comment by Jonny-Boschan** [comment]
@ahdbilal, is there any progress on this feature? Our team sincerely needs the ability to edit the version names like we used to in HockeyApp. I'm not saying the following as a threat, but as evidence for our demand for this feature. Our Product Manager said he was going to start exploring other options outside of AppCenter, because of the hassle and frustration the lack of this feature is causing.
