### ISSUE TITLE
Xamarin.Mac Support

### ISSUE THREAD

**Issue by projectgoav** [microsoft/appcenter#143]
**Describe the solution you'd like**

 App Center available for Xamarin.Mac applications.

**Describe alternatives you've considered**

Xamarin Insights supported this. When it was terminated, App Center was touted as the replacement and would support the same platforms.

I don't believe there is any other Xamarin supporting tool for insights or crash reporting without a custom in-house solution. 

**Additional context**

App Center website has indication that not all insights platforms are supported. https://docs.microsoft.com/en-us/appcenter/migration/xamarin-insights/

https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/529
https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/615

**Comment by emergencynap** [comment]
Are there any updates to this feature request or do we have to integrate using the Swift Mac app logic inside of a Xamarin Mac / Visual Studio for Mac app.  Seems backwards.

**Comment by equinox2k** [comment]
Been waiting patiently for this feature for a long time now.

**Comment by projectgoav** [comment]
Think you'll be waiting, patiently or otherwise, for a long time... Don't seem a priority for them.

**Comment by patniko** [comment]
In full transparency @projectgoav, you're totally correct. We've been focused on drilling deeper into our mobile platforms and adding more Windows support lately based on the large amount of feedback we receive. We _absolutely_ are tracking interest here, but we're stuck working a bit higher up the Github list for now.

**Comment by projectgoav** [comment]
> We absolutely are tracking interest here, but we're stuck working a bit higher up the Github list for now.

I think *interest* is the wrong word here. 

Xamarin Insights users were told the service was being turned off and to migrate to App Center. "Feature Parity" was quoted and visible on both Insights and AppCenter websites.

Insights is no longer available and yet not everything we could do with Insights is available with App Centre....

**Comment by KeithBoynton** [comment]
I would like to add that I've considered AppCenter a few times over the last year or so for Analytics and Crash Reporting since Insights was closed down. I have ditched the idea each time because of lack of Xamarin.Mac support. I come back here every now and then to see what's going on Xamarin.Mac wise and each time I see that it is still not supported with no confidence that anything is likely to change in the near future.

Unfortunately Xamarin.Mac has always been the achilles heel of the Xamarin platform and each time development effort is vastly increased when trying to make solutions work on the Xamarin.Mac platform.

This is clearly the case here too, it's disappointing to see that we still struggle to support the Mac platform as well as we could.

I wanted to be vocal about my disappointment and I'm sure there are a lot of other folks who are not being so vocal that are frustrated by this too. For a framework that is being touted as multi-platform not supporting such a key platform is a pretty strange move.

1) I think I read somewhere that there is a feature request that can be "voted on".. if that's the case could someone forward me a link so I can vote?

2) I understand there is a "workaround" contributed to by a community member and a native OSX/ObjC option, does anyone have a reliable implementation of that live and working in the wild?

**Comment by ivanicin** [comment]
@KeithBoynton I think you vote here by pressing thumbs up button.

**Comment by KeithBoynton** [comment]
Perfect, thank you @ivanicin

**Comment by DennisWelu** [comment]
I'm with @KeithBoynton, App Center is great but multiple times I've been in a position where a Mac project in my x-platform Xamarin solution is either left behind or a different choice has to be made for reporting errors/events. Given that both Xamarin and App Center are under the MS umbrella, and the fact that the bindings would likely be similar to the iOS bindings project, from the outside looking in it seems like a natural next step. There's already support for native MacOS platforms why not Xamarin-Mac?

**Comment by KeithBoynton** [comment]
I also see a community member @equinox2k put in some effort with this pull request
https://github.com/microsoft/appcenter-sdk-dotnet/pull/658

Which was just closed down.. what's going on?

**Comment by projectgoav** [comment]
If you look through the repsonses linked at the bottom of my original post it's clear that Xamarin.Mac is not a priority for them. 

I requested the feature almost 2 years ago now and nothing has been done about it so I think it's a lost cause at this point :(

**Comment by KeithBoynton** [comment]
Yep I feel your pain, it's been like that with Xamarin.Mac for years in most areas, without the legendary support of @chamons who knows where we'd be.

I find it particuarly perplexing given that Native MacOS is supported so struggle to understand why we can't just have a wrapper around that.

**Comment by tipa** [comment]
I just started to look into porting my existing Xamarin apps to MacOS and I was seriously surprised
that there is no support from AppCenter for it yet - not even on the roadmap...

**Comment by KeithBoynton** [comment]
Yes it's perplexing, make sure you vote on this and any other relevant threads and hopefully it will get addressed. Unfortunately it makes you consider other cross platform solutions when you're needing decent support for Mac OS

**Comment by Suplanus** [comment]
Please do not close this issue, bot 🤖

**Comment by Suplanus** [comment]
Bump

**Comment by DennisWelu** [comment]
On behalf of @Suplanus and friends, stay alive

**Comment by KeithBoynton** [comment]
2 and a half years on a Mac still not properly supported on a "cross platform" framework. Is macOS really that much of an unpopular platform?

**Comment by DmitriyKirakosyan** [comment]
Hi folks, glad to inform that we are currently working on supporting Xamarin.Mac platform. You can track the progress here: https://github.com/microsoft/appcenter-sdk-dotnet/pull/1586.
The PR is based on @nor0x's implementation, thanks a lot to him for his great work.

The Xamarin.Mac support is expected to be available in the next release this quarter.

**Comment by AnastasiaKubova** [comment]
Hi there! The feature has been released in the [4.5.0](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/4.5.0) version of App Center SDK.
