### ISSUE TITLE
Search distribution group members

### ISSUE THREAD

**Issue by matsmalmstensc** [microsoft/appcenter#1438]
Would be great to be able to search distribution groups members by name or email. Rigth now you have to scroll through the whole list to find the right member.

**Comment by amitse** [comment]
Moreover we can't ```Cmd+F``` items in the member list, as the rows are virtualised.

**Comment by Zakeelm** [comment]
Hi there! 

Thanks for submitting this feature request. I'm going to leave this open to gauge the interest on this feature. Also, looping in our product owner of this area so that they can take a look at this.

**Comment by andrewdmontgomery** [comment]
+1

This is really important.  We assumed Cmd-F was working.  When realized a few days ago that it only searches the active screen, we performed an exhaustive (and time consuming, and error prone) audit.  We discovered multiple accounts from departed employees that were never removed because we thought Cmd-F was functional.

Visually scanning 200+ accounts is highly error prone.  It's nearly an impossible mission, though, since the list isn't even sorted.
