### ISSUE TITLE
Security Audit

### ISSUE THREAD

**Issue by bakerm00** [microsoft/appcenter#1485]
**Describe the solution you'd like**
All events relating to CRUD of all objects within App Centre logged within a database to support audit capabilities;
these logs should be shippable or stored in Azure Log Analytics.

**Describe alternatives you've considered**
there is no full Azure AD idP integration to restrict to corporate or published B2B account utilisation within app centre.  so "don't" use app centre is the security message.
**Additional context**
standard security and identity management features.

**Comment by nrajpurkar** [comment]
Thanks for this feature request as well @bakerm00. @iageoghe to take a look at this too.

**Comment by ScottArbeit** [comment]
@bakerm00 App Center has a lot of different kinds of objects that we handle... analytics logs, crash dumps, team and distribution group memberships, app downloads, etc. Auditing CRUD for all of those objects probably doesn't make sense... is there a subset of them that you think we should be auditing?

For users... if you add Azure AD groups to teams and distribution groups instead of individual accounts, you can leverage the auditing features in Azure AD (and I'm guessing you're thinking the same thing in #1486).

**Comment by askpatrickw** [comment]
Full audit trail is required for all user actions in most if not all audited standards (think HIPAA, ISO, etc...). Having this would be a big differentiator.

**Comment by askpatrickw** [comment]
Hey Bot, we still want this fixed.

**Comment by askpatrickw** [comment]
Soooooo need to fix this.

**Comment by askpatrickw** [comment]
Pls fix the thing.

**Comment by tasomaniac** [comment]
OMG. So sorry to see this being closed just because an uncaped hero did not reply the 4th or 5th time after so many months.

This clearly tells you something about the product.
