### ISSUE TITLE
appcenter APP for ios and android (similar to Hockeyapp APP)

### ISSUE THREAD

**Issue by mohammedmsadiq** [microsoft/appcenter#1571]
**Describe the solution you'd like**
appcenter APP for ios and android (similar to Hockeyapp APP).

**Describe alternatives you've considered**
n/a. users dont really like using web browser.

**Comment by derpixeldan** [comment]
@mohammedmsadiq there is one for Android, you can download it from the [Play Store](https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp). Due to Apple's terms we're not allowed to release a similar app to the App Store. If this will ever change, we will reconsider creating one for iOS as well.

**Comment by spraveenk91** [comment]
@dipree 

In HockeyApp there was a feature that making the application to 'Public' mode to make it visible to the associated UDID added devices especially for iOS. Do we have any similar feature in AppCenter. It seems like every time we need to login into the appcenter to download the app.

**Comment by dipree** [comment]
@spraveenk91 exposing to UDIDs in the provisioning profile doesn't exist in App Center. You can only create a public distribution group, however, that exposes the build to all users with access to the link. Feel free to open a new feature request for this.
