### ISSUE TITLE
iOS app for AppCenter (similar to what HockeyApp had)

### ISSUE THREAD

**Issue by spencer-microsoft** [microsoft/appcenter#1627]
**Describe the solution you'd like**
An iOS app with a better experience than the current mobile web app, which is very slow with things that should be simple (like searching your apps)

**Describe alternatives you've considered**
I use the web app, but searching for apps freezes the UI for about half a second in between every character added or removed

**Additional context**
Here's the link to the HockeyApp internal app I'm referencing:
https://install.appcenter.ms/orgs/hockeyapp/apps/HockeyApp-for-Testers-Internal-01

**Comment by dipree** [comment]
@spencer-microsoft thanks for your feedback. Please reach out through internal channels as this doesn't serve any public purpose.

**Comment by yvbeek** [comment]
@dipree This discussion would probably serve a public purpose. When I moved our apps from Fabric to App Center, I was explaining the new environment to one of our QA people. Her first instinct was to search for an app in the App Store, because she is really used to TestFlight to install her test builds.

It would be great to have a simple app that displays the releases and makes it easy for them to install Production / Staging builds (depending on the git branch).
