### ISSUE TITLE
The build pipeline does not currently support non-ASCII characters in certificate names

### ISSUE THREAD

**Issue by rfsouto** [microsoft/appcenter#1652]
With a recent update of the pipelines. 

Those are more secure but it´s not possible to sign iOS builds with non-ASCII characters in certificate names.

**Comment by lores3000** [comment]
I just want to give a bit more background information to the severity of the issue: The iOS Certificate name has to contain the company's legal name and cannot be changed. I just had this issue setting up a project for a customer with Umlauts in their company name and we are not able to use Appcenter Build.

**Comment by rfsouto** [comment]
I think this should be a bug and not a feature request, cause this properly working in the past. 
In fact, we have some old builds that are working actually in the correct way.

**Comment by ryanthompson0123** [comment]
Just wanted to report here that I'm strongly considering moving my build pipeline to App Center, but this issue is preventing me from using the service. 

My company's legal name is Kordata, LLC so my distribution certificate is named Apple Distribution: Kordata, LLC. I can see in the build logs that the toolchain is being invoked with `/p:Codesignkey=Apple Distribution: Kordata%2C LLC ` and so the build errors out with "iOS code signing key 'Apple Distribution: Kordata%2C LLC (WPVB93E8VR)' not found in keychain"

I submitted a ticket to support as well. Maybe there's a workaround, but I'm not seeing it.
