### ISSUE TITLE
[Xamarin.UITest] Failed to launch DeviceAgent

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/appcenter#1662]
Using Xamarin.UITest 3.0.6, which did not happen using 3.0.5, running UITests using the iOS Simulator:

```
 Xamarin.UITest.XDB.Exceptions.DeviceAgentException : Failed to launch DeviceAgent

ExitCode: 1

/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/uitest/a-74E675F13AA319302ED389DB58333C4F69C32260/launch-safely.sh: line 34: 1851 Terminated: 15 $COMMAND

cat: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/uitest/heartbeat.log: No such file or directory

heartbeat.log missing or empty
```

Is there are workaround for this issue ?

Thanks!

**Comment by owenniblock** [comment]
We believe we have a fix for this - just verifying that it resolves the problem fully before releasing a `dev` package.

If other users are hitting the same issue - you could try manually creating the file referenced and trying again - that may work around the issue before the fix comes out (although I've not tested that theory so it could lead to another failure slightly further along).

**Comment by stoneman** [comment]
Another possible workaround is to not call the [LogDirectory()](https://docs.microsoft.com/en-us/dotnet/api/xamarin.uitest.configuration.iosappconfigurator.logdirectory?view=xamarin-uitest-sdk#Xamarin_UITest_Configuration_iOSAppConfigurator_LogDirectory_System_String_) API if you are doing so.

**Comment by stuarth-inova** [comment]
Hey @Oddj0b - we are seeing a related issue w/ Xam UITest 3.0.6. Since I've been upgrading Xcode I seem to still have the old simulators, so my tests run on both iOS and Android. When they pass, they work fine. When they fail, however, the test halts with no result (neither pass nor fail). Debugging showed an System.IO.IOException, a sharing violation, on that exact same file: /var/folders/<stuff>/heartbeat.log. This IO exception is not bubbling up to make the test fail.

**Comment by owenniblock** [comment]
@stuarth-inova and @jeromelaban please could you try https://www.nuget.org/packages/Xamarin.UITest/3.0.7-dev1 - we believe this should resolve both of these issues but please report back either way :)

**Comment by stuarth-inova** [comment]
Patch worked for me, resolved my issue! Thank you for the quick turnaround.

**Comment by stuarth-inova** [comment]
@owenniblock @Oddj0b - Hey, I couldn't find this issue in the list, asking if I should file it or if you know anything about it. When I try to use Repl with the iOS Simulators it fails when I actually login to our app:

Xamarin.UITest.XDB.Exceptions.ExternalProcessException: xcodebuild output not as expected

Any ideas? Should I write it up? Thanks.

**Comment by owenniblock** [comment]
@stuarth-inova best thing to do is report it via the support in App Center - I've not seen this issue before so it's unlikely to be recorded but you'll get a faster response if it goes through our support channels.

**Comment by stuarth-inova** [comment]
@owenniblock - Hmmm, submitting through App Center.

I had started that process for this particular issue and they never sent me here - they provided no clue it was already known and being worked on. One of my co-workers found this page through his own resourcefulness.

So that is disappointing because they seem to be focussed almost entirely on app center itself, and not on Xamarin and Xamarin UItest that run on the users' platforms.

**Comment by owenniblock** [comment]
@Oddj0b ^

I can only say sorry that this has happened! At present the App Center Test team is responsible for Xamarin.UITest so support through App Center makes most sense (this repo is intended for feature requests and support issues can get lost as they don't make it in to our normal support escalation queue).

**Comment by jeromelaban** [comment]
@owenniblock I understand why you want to have a support system integrated in app center, but your support tickets that could be public are not, making it difficult to find resources and have a community effect.

Once you make Xamarin.UITest open source (at least I hope you will), you'll most probably probably have to support it through github anyways.

**Comment by Lonswaya** [comment]
3.0.8-dev1 worked for me here, too. Thanks for the patch.

**Comment by Oddj0b** [comment]
I believe this has been, but not closed.
