### ISSUE TITLE
More info in the all apps section

### ISSUE THREAD

**Issue by BillyMartin1964** [microsoft/appcenter#170]
When we have several apps, it's a pain to go through them checking for crashes. Can you please put some sort of crash summary for each app in the ALL APPS section of the dashboard.

**Comment by winnieli1208** [comment]
Hi @BillyMartin1964 - thanks for the feedback! I can definitely see this being useful for developers with multiple apps (especially cross-platform apps). Due to other priorities, this isn't currently on our roadmap but I will monitor this feature request for community support and prioritize appropriately.

Thanks!

**Comment by halgadaibi** [comment]
Any update regarding this feature? I was about to open a ticket to at least show the latest build status in the all-apps view. This is a small feature but it's extremely useful! We have 18 apps in total and this will help alot. Thank you in advance.

**Comment by winnieli1208** [comment]
@halgadaibi no updates at the moment. We would love to have some sort of dashboard in the future but unfortunately, due to other priorities right now, we don't have any immediate plans to build this. We will continue to monitor this feature request and post updates if we have any. Feel free to check out our [roadmap](https://github.com/Microsoft/appcenter/wiki/Roadmap) and [iteration plans](https://github.com/Microsoft/appcenter/wiki/Iteration-plans) to see what our team is working on. 

Thanks!
