### ISSUE TITLE
Ability to create direct links to specific error reports

### ISSUE THREAD

**Issue by steffos** [microsoft/appcenter#1700]
I would like to, at the time an error occurs, create a link to that particular error. Then I could use that link and send it in an email or to a Slack channel. I did find this in your api specs (https://openapi.appcenter.ms/):
/v0.1/apps/{owner_name}/{app_name}/errors/errorGroups/{errorGroupId}/errors/{errorId}

If I, for instance, could get the errorId parameter back when App Center is submitting the report, I then could create the link myself.

Or maybe there is another way to link to a specific error report at the same time it's reported to App Center?

**Comment by akravch** [comment]
I am looking for something similar myself. There is an ugly workaround though 😃

At the time you are sending a crash report, you know crash id (a GUID). Let's call it a `crashGuid`. Then, I noticed a crash URL in app center has the following format:

`https://appcenter.ms/orgs/{appOwner}/apps/{appName}/crashes/errors/{errorGroupId}/reports/{someNumber}-{crashGuid}`

Open API provides an URL for search, so you can search for this guid:

`https://api.appcenter.ms/v0.1/apps/{appOwner}/{appName}/errors/search?q={crashGuid}`

There is an extremely high probability that the `crashGuid` is unique across the app, so you will get only one crash item as response, which contains `errorGroupId` and full `errorId`, which is basically `{someNumber}-{crashGuid}`. Having all this data, you can build a final URL you need.

Although I would very much like to see a simpler way to achieve this. It would be great if AppCenter returned some ID uniquely identifying an error so that we could access this error without knowing `errorId` and `errorGroupId`.
