### ISSUE TITLE
Support non-unicode characters in the certificate name when re-signing for iOS

### ISSUE THREAD

**Issue by NeverwinterMoon** [microsoft/appcenter#1715]
**Describe the solution you'd like**
I expect re-signing to work with the certificate that contains non-unicode characters.

**Describe alternatives you've considered**
The alternative is to use a certificate with unicode characters, but my full company name contains unicode characters, so does the development team created at the Apple developer portal, so did the certificate.

**Additional context**
Surprisingly, it was possible to make a build using the same certificate, but not to re-sign the build when new test devices tried to download the test application.

**Comment by Oddj0b** [comment]
Thank you for your request. I'm looking into it with an engineer.

**Comment by Oddj0b** [comment]
Hey @NeverwinterMoon, I talked with my engineers and we can't make an easy fix. It means that we will see the interest (👍 ) in this issue before we can start to work on it.

**Comment by DomiR** [comment]
@Oddj0b Thanks for looking into it. For me Resigning did also fail for non-ascii-128 characters (namly ö). I don't see how I can change the certificate, as the character stems from the name of the account holder. I can see that supporting non Unicode characters might be a lot of work, but supporting unicode or even ascii-256 might be easier? Would you mind to take another look?

**Comment by zawasp** [comment]
I have the same situation due to my name containing the letter ă. I can upload the p12 cert, however when saving the build settings, but can't save them because the certificate contains non-ascii characters. This is a blocking point from using AppCenter to build, test and distribute apps.

**Comment by ryanthompson0123** [comment]
Just wanted to report here that I'm strongly considering moving my build pipeline to App Center, but this issue is preventing me from using the service. It's not even just non-ASCII characters, it seems to be anything that would normally be URL encoded.

My company's legal name is Kordata, LLC so my distribution certificate is named Apple Distribution: Kordata, LLC. I can see in the build logs that the toolchain is being invoked with /p:Codesignkey=Apple Distribution: Kordata%2C LLC and so the build errors out with "iOS code signing key 'Apple Distribution: Kordata%2C LLC (WPVB93E8VR)' not found in keychain"

**Comment by jarekbb** [comment]
I have the same problem. Any solutions?

**Comment by DomiR** [comment]
I asked apple to change my name and used ascii symbols only 🙈
