### ISSUE TITLE
Connecting Enterprise Github to App Center

### ISSUE THREAD

**Issue by bharathraj-91** [microsoft/appcenter#1719]
**Describe the solution you'd like**
It would be nice if we could connect our enterprise github account to app center to build our app. Right now we are unable to use appCenter just cause we cannot connect with our enterprise account.

**Describe alternatives you've considered**
We considered forking the repository to a personal account but that seems to be a bunch of security risks that have to be considered for an enterprise that already has an enterprise account.

**Comment by ahdbilal** [comment]
Thank you for showing interest in this request. We have started looking into this feature and will love to schedule a few minutes call to understand the use case and expectation of this request. Please click [here](https://outlook.office365.com/owa/calendar/Microsoft2278573@microsoft.onmicrosoft.com/bookings/s/haFgloiuDUyOj18bp0wJcA2) to schedule the call. Really appreciate your help with this feature request!

Thanks
App Center Product Team

**Comment by mat-goralczyk** [comment]
Dear Support Team,

Has it been resolved, meaning App Center can connect to GitHub **Enterprise** repos as well or is it only possible to connect to non-enterprise GH repos?  

The information here: https://learn.microsoft.com/en-us/appcenter/general/account is not clear to me. Please let me know as we are planning to use App Center to build and distribute our iOS and Android apps but due to company restrictions only GH Enterprise can be considered as code repository. 

Kind regards,
Mateusz
