### ISSUE TITLE
After changing email in AppCenter, I can still use my previous email to login

### ISSUE THREAD

**Issue by androideveloper** [microsoft/appcenter#1736]
Steps to reproduce:

- Create account in https://appcenter.ms/
- Change email to another email under you account settings
- Logout and login with your new email
- Logout and login with your previous email

Expected Result:

- Should prevent login with old email and only login with new email

Observed Result:

- Successfully logged in and you can use both emails to login to the same account. This is security vulnerability.

*Tried on 3 different PCs and with another user account

Here is video showing how to reproduce. 

https://1drv.ms/v/s!AiUG8l584Bi2kihsnZ3jgpM4tMfe?e=ouyaiN

**Comment by lumaxis** [comment]
Thanks for the detailed report @androideveloper ! What you're experiencing is a bit unintuitive but currently expected behavior.
Once an App Center account is associated with a given SSO provider's account (i.e. a Google, Facebook, Microsoft, or GitHub account), there is currently no manually way of changing that association.
When you're changing the email address in the App Center user settings, you're simply changing the email address that could in the past be directly used for email & password login to App Center.

**Comment by lumaxis** [comment]
@ScottArbeit I've looked through other open issues but didn't find a good match. Better management of linked SSO accounts has been something I wished for for a long time, maybe we want to capture that separately as a feature request?

**Comment by androideveloper** [comment]
> Thanks for the detailed report @androideveloper ! What you're experiencing is a bit unintuitive but currently expected behavior.
> Once an App Center account is associated with a given SSO provider's account (i.e. a Google, Facebook, Microsoft, or GitHub account), there is currently no manually way of changing that association.
> When you're changing the email address in the App Center user settings, you're simply changing the email address that could in the past be directly used for email & password login to App Center.

@lumaxis Thanks for the feedback on this issue. Besides being unintuitive I think this is a security vulnerability, because potentially you can change your email many times under the settings and in that case, every new email can be used for signing in to AppCenter later, even if you removed that under the settings.

**Comment by lumaxis** [comment]
@androideveloper That's not exactly how this works. Only the currently set email address could be used to directly log in to App Center with a password.
Each SSO account is linked to exactly one App Center account at a time.

**Comment by androideveloper** [comment]
@lumaxis In this case we get many SSO to one AppCenter linking. Please find the video showing how to reproduce here https://1drv.ms/v/s!AiUG8l584Bi2kihsnZ3jgpM4tMfe?e=ouyaiN

**Comment by lumaxis** [comment]
@androideveloper That's correct and currently by design, as I mentioned. You can have multiple SSO accounts linked to a single App Center account but each SSO account can only be linked to one App Center account and each App Center account only to one Google, Facebook, GitHub, or Microsoft account at a time.

Additionally, what you're showing in the last part of the video is another functionality where, when you login with a given SSO account for the first time, we look up that SSO account's email address in the App Center database and link it to an existing App Center account if it exists with that email address.

**Comment by androideveloper** [comment]
New activity, please don't close it bot
