### ISSUE TITLE
Add ability to change application secret 

### ISSUE THREAD

**Issue by richardpineo** [microsoft/appcenter#1742]
**Is your feature request related to a problem? Please describe.**
We set up a different app center stack for our different customers. Because we work in the enterprise space (airlines) it is a requirement to keep the logs and application insights separate for our product. 
We are unable to log out from one customer and log into another and point AppCenter to the new application secret without exiting the iOS application, which you should not do programmatically (per Apple guidelines)

**Describe the solution you'd like**
Would like the ability to call configureWithAppSecret multiple times in the life of the application to target different apps in ms app center.

**Describe alternatives you've considered**
Forcing a restart of the application (not allowed by iOS guidelines)
Disabling app center when the user logs out and logs in again in a different context than the initial authentication.
We cannot think of any other workaround to this issue.

**Additional context**
It is generally less than ideal to keep state in application instance variables. This statefulness is somewhat unexpected and definitely inconvenient if those variables are not able to be modified. 

Here is a little more information on that topic.
https://stackoverflow.com/questions/4399611/force-iphone-app-to-restart-programmatically

**Comment by Majidco18** [comment]
I am using the AppCenter sdk for an Android app (Kotlin) for several month and now just realized a critical issue in my app. 
In my app somehow I need to chnage the Appcenter application after application runs. 
UserStory 
- Application starts
- Appcenter starts with temp target 
- User scans a QRCode
- There is an env variable in the QRCode which it change the application api endpoints,... to the right targets.
- But Since Appcenter SDK is supper sticky and there is even no funtion to say AppCenterStop() to forcibly stop it it continues to send the logs to temp target even if I start it again, or stop/disable all the services and so on
- I think this is very useful to have Reconfiguration method or restart(newSecret) method

**Comment by Eeems** [comment]
Why are feature requests being marked stale automatically? That seems fairly silly.
