### ISSUE TITLE
Store crash data longer then 28/90 days

### ISSUE THREAD

**Issue by schriftgestalt** [microsoft/appcenter#1749]
I need an archive of the crash data. 
I need to know what crashes I have fixed (because that info is also gone after that time) and the total number of all crashes. 

Hockeyapp did store all data forever.

**Comment by Oddj0b** [comment]
The commendation is to export your data and query it from there: https://docs.microsoft.com/en-gb/appcenter/diagnostics/features#export-diagnostics-data

**Comment by schriftgestalt** [comment]
But the whole point of appcenter is that I have a UI for it, And don’t need to query it myself. If I build all the tools to do that, I don’t need appcenter at all.

Can the limit not be changed to the number of crash reports instead of a hard expiration date? With the possible (payed) option to increase the storage?

**Comment by matthiaswenz** [comment]
@schriftgestalt Thanks for your feature request. At this point the recommendation is to use the export feature for any data that might be aged out in App Center past the retention period for your app.
We are considering different retention models in the future but don't have any announcements about these right now.

**Comment by schriftgestalt** [comment]
Why you can’t serve the needs of you customers (that where served by the previous solutions just fine)? Can you at least release the Hockeyapp code that people can server themselves? Maybe the code of the Hockeyapp desktop app? With that base I maybe can build my own system and get off your nerves.

**Comment by guidedways** [comment]
+1 This is important. You lose your history of fixes and any bugs that really are OS originating and unfixable. This is how it works in Firebase / Fabric too.

**Comment by tonyarnold** [comment]
I'm resurrecting this issue, because it was never resolved, and the "answers" are not workarounds or workable solutions.

I’m sorry to say that the decision to drop data retention beyond 28 days means that we'll be moving to another product/competitor.

The lack of meaningful updates and improvements to AppCenter's core product over the past couple of years, plus removing the functionality of longer term data storage and analysis _without a paid solution in place to replace it_ is perhaps too much to ask of users - but I do understand that many of us are not paying for the service.

I would happily pay for a better level of service, but that is not on offer so I will have to move to a competitor and pay them instead. 

Gosh I wish Microsoft would stop buying products like HockeyApp only to collapse them down and abandon them.

**Comment by datwelk** [comment]
@tonyarnold May I ask which competitor you are using now? The limited retention period of AppCenter is seriously impacting our development process, we have no way of tracing down when certain inexplicable crashes started occurring. To give a concrete example, our application is severely impacted by an opaque Apple bug (see https://developer.apple.com/forums/thread/696764) but thanks to Microsoft we have no way of tracing back when it surfaced.

**Comment by tonyarnold** [comment]
@datwelk for our app/team, I assessed a number of options, and ended up choosing [Sentry](https://sentry.io/).
