### ISSUE TITLE
Distribution App on Google Play and AppStore

### ISSUE THREAD

**Issue by tmdues** [microsoft/appcenter#178]
**Describe the solution you'd like**
HockeyApp currently has an on Google Play and the AppStore. This app provide a list of all the apps and their build history. Our QA department finds it useful to quickly access previous builds.

**Describe alternatives you've considered**
The alternative we are using now is a public download page from AppCenter. This is more or less a suggestion as this alternative is currently working.

**Comment by lumaxis** [comment]
@tmdues There is actually already an app on Google Play: https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp&hl=en
Even though it is branded as "HockeyApp", the app version with the pink icon is already using App Center underneath and you should be able to see all your apps that you can get from the website today.

There was never a HockeyApp app on the Apple App Store, due to issues with the store's submission guidelines but we're always exploring better solutions for our iOS users too 🙂
