### ISSUE TITLE
Must need to add the settings for change the time zone

### ISSUE THREAD

**Issue by merbin2012** [microsoft/appcenter#1786]
**Describe the solution you'd like**
In the admin panel "Log Flow" menu, we can not able to see the log in our time zone.

**Describe alternatives you've considered**
You must add time zone options in the user settings.

**Comment by YeshanJay-Urban** [comment]
I'm facing the same problem.

I use AppCenter Analytics and cross check the event counts per day with other Analytics services (Segment/Amplitude).

Problem occurs when the other services have their time zone set to another country.
And AppCenter takes the time zone of the country I'm in (I guess - or is it UTC?).

Anyway I get the counts mismatched due to this.
If there was a way to change the time zone in AppCenter and show the reports appropriately to that given time zone, that would be really ideal.

FYI @winnie 
---
Also would be nice to have an option to filter by a single date or date range  🙂
Analytic -> Events -> <Selected Event> -> Check the filters..

**Comment by YeshanJay** [comment]
I'm facing the same problem.

I use AppCenter Analytics and cross check the event counts per day with other Analytics services (Segment/Amplitude).

Problem occurs when the other services have their time zone set to another country.
And AppCenter takes the time zone of the country I'm in (I guess - or is it UTC?).

Anyway I get the counts mismatched due to this.
If there was a way to change the time zone in AppCenter and show the reports appropriately to that given time zone, that would be really ideal.

FYI @winnie 

---
Also would be nice to have an option to filter by a single date or date range  🙂
Analytic -> Events -> <Selected Event> -> Check the filters..

**Comment by Rothanan** [comment]
Same here, this would make a huge difference.

**Comment by LouisShark** [comment]
Same question，is there any progress

**Comment by LouisShark** [comment]
Is it have some changes
