### ISSUE TITLE
No Analytics for event if deleted from dashboard.

### ISSUE THREAD

**Issue by Faisal-Manzer** [Microsoft/appcenter#180]
**What App Center service does this affect?**
Analytics React Native.

**Describe the bug**
There is an Event (say "Audio Played").
We are getting its analytics in Appcenter Dashboard.
If we DELETE EVENT HISTORY, I don't know why but future events with the same event name is not being tracked.

**To Reproduce**
1. Add some Analytics key point in your app.
2. Receive some data from it.
3. Come to the dashboard and delete event history.
4. Error: Dashboard not showing that particular Event.

**Comment by yochaude** [comment]
Hello,

This is an expected behavior.

Deleting an event can be a long operation so while our backend is processing the request, we artificially "hide" the event from our API responses for an hour.

Future events emitted after the deletion completed will show up in our portal (and be returned by our API) within an hour.

**Comment by Faisal-Manzer** [comment]
Ohh, I got that thanks. I was confused that tracking is not happening.
