### ISSUE TITLE
bug: app installs successfully even though device is not part of PP

### ISSUE THREAD

**Issue by tele-bird** [microsoft/appcenter#1815]
**Describe the solution you'd like**
iOS apps signed with ad-hoc PPs that **don't** contain the UDID of the device I'm using should fail to install.

**Describe alternatives you've considered**
There is no alternative.  This is required by Apple.  Apps should never install in this scenario.

** Steps to reproduce **
Build an iOS app with an ad-hoc provisioning profile.  Distribute the release using app center to a distribution group that has access to the app.  On an iPhone 6, login to install.appcenter.ms using an account that belongs to the group, and using a device that **isn't** part of the provisioning profile.  Select the release to install, and tap install.  Minimize the browser and watch the app's icon appear.  notice that it is greyed-out and has the app's bundle ID as the icon label.  Tap it, and watch the icon un-grey-out and the icon title gets corrected.  Then, tap it again, and the app will launch.

** Expected result **
An iOS error should appear saying the app could not be installed.

**Additional context**
App successfully installs *intermittently*.  I haven't found a way to reproduce every time.  It may be an Apple issue.  If there is an existing Apple issue covering this, we should link this issue to it.

I tried to reproduce the problem by installing the app from Xcode, but it correctly failed.

![IMG_3823](https://user-images.githubusercontent.com/8117598/79800002-72bb5980-8329-11ea-8372-82c66c63e9cb.PNG)
![IMG_3824](https://user-images.githubusercontent.com/8117598/79800008-76e77700-8329-11ea-9097-663df0e2bae6.PNG)
![IMG_3825](https://user-images.githubusercontent.com/8117598/79800022-7c44c180-8329-11ea-8437-50b82afd261d.PNG)
![IMG_3827](https://user-images.githubusercontent.com/8117598/79800047-86ff5680-8329-11ea-8035-e094b98e39a3.PNG)
![IMG_3828](https://user-images.githubusercontent.com/8117598/79800067-8f579180-8329-11ea-82b2-619f7beba897.PNG)

**Comment by winnie** [comment]
Hey @tele-bird - thanks for filing an Issue. Can you check if you have the "[automatically manage devices](https://docs.microsoft.com/en-us/appcenter/distribution/groups#automatically-manage-devices)" setting enabled for your distribution group?

You can check by clicking the group and then the settings/tool icon:

![image](https://user-images.githubusercontent.com/8868628/81092693-0155dc00-8ecf-11ea-91f8-14464baf1e2b.png)


If this setting is turned off, please file a support ticket with a link to this issue and include the app name/distribution group in question so our team and further investigate. Thanks!

**Comment by tele-bird** [comment]
@winnie 
It shouldn't matter whether "automatically manage devices" is enabled or not.  It should fail to install in either case.

Please provide a URL for opening a support ticket.  (I thought *this* was the ticket.)

**Comment by winnie** [comment]
@tele-bird with "automatically manage devices" enabled, App Center will automatically register the device and add it to the provisioning profile. If you have this setting is enabled, then the behavior you described seems like expected behavior. This [blog post](https://devblogs.microsoft.com/appcenter/announcing-auto-provisioning-build-and-distribute-apps-faster/) does a good job explaining our auto provisioning feature.

If you don't have this feature enabled however, there might be an issue on our end or a bug with Apple since they control what gets installed. 

Either way, you can start a support ticket by selecting the info menu in the upper right corner:

![image](https://user-images.githubusercontent.com/8868628/82130250-a9a15580-9797-11ea-89c9-b4b2537b32ae.png)


Thanks!
