### ISSUE TITLE
Add label/branch field and a filter for this in Releases 

### ISSUE THREAD

**Issue by donnib** [microsoft/appcenter#184]
**Describe the solution you'd like**
*Background* 
We deploy each build we make of our iOS app to AppCenter from all branches meaning both develop and feature branches. We do this to easily be able to install the different versions dirrectly from the iOS device. At the moment all releases are just in one bucket making it extreme difficult to find that particular release that you want between hundreds of other releases.

*Ideal solution*
We wish there was a way we could specify branch/label on each Release that we could filter on in the iOS device when we go to install.appcenter.ms. It could be a drop down that user selects for which he wants to see the releases. If you think branch would be too specific then you can call the field Label and users can use it for anything they wish.
This would be such a great feature that would solve our problem and i would think others would want this. 

**Describe alternatives you've considered**
- If ideal solution is not possible then another way to achieve something simmilar could be to add a search field on install.appcenter.ms that searches the release notes (we have added the branch information in the release notes).
- Another solution would be to Expand ALL releases on install.appcenter.ms so one could use the build in Search on page on iOS device, this is not a nice solution and will be performance wise be bad. 

**Additional context**
We don't think the use of Groups for branches is a good solution if you wanted to suggest that. That would require to create a Group for each branch and then remembering to clean it up. We think this would be a very bad solution.

**Comment by larskemmler-flaregames** [comment]
We're having pretty much the same issue: We're uploading builds quite frequently and from different branches (currently still to HockeyApp) and it's time consuming to find the correct build in the App Center UI since branch information isn't visible in the overview page (we would have to open each build's page and check if it's the correct one).
Additionally we're uploading 2 versions for each iOS build: One signed with an adhoc profile, one signed with an in-house profile. This is necessary due to cooperation with external partners, but it makes it even harder to find the correct build.
In HockeyApp we used to just put branch and provisioning profile information in the release notes of the build, which was a decent workaround since the release notes were visible in the build history page. Unfortunately this doesn't work on App Center, which is currently blocking us from making the transition.

**Comment by derpixeldan** [comment]
@larskemmler-flaregames I'm wondering what's different for you on App Center in terms of the release notes? Each release shows the release notes similar to how HockeyApp is doing it.

**Comment by donnib** [comment]
@derpixeldan if you navigate to install.appcenter.ms on a iOS device and navigate to your app then you only see the release notes for the last build so if you want to use the build in Search in Safari iOS for branchX then you can't because the releases are collapsed. Even if we could do this it would be a VERY bad solution. We upload each build from each branch and during the last 1 month we uploaded 640 builds. Imagine what would happen if you would Expand all 640 builds in Safari iOS ?? As i mentioned, if you just add a field Label to each release that can be set by the CLI and add a filter at the top for the app then problem solved.

**Comment by larskemmler-flaregames** [comment]
@derpixeldan If I navigate to rink.hockeyapp.net/apps/[app_id] and tap on History, I can see the release notes for all builds.
If I do the same thing on install.appcenter.ms, I can only see the release notes for one build at a time because all other builds are collapsed.

**Comment by zurielb** [comment]
I think ideally when you have builds from multiple branches, they would be grouped by branch, that way you can pull the latest release from each branch.

We do releases for development, QA, staging, etc, and having no way of differentiating them from the releases screen is a non-starter.

The workaround for now, is to create a **separate** app PER branch so that our testers can tell them apart, but it would be nicer if we didn't have to do that.
