### ISSUE TITLE
Diagnostics.IsConnected

### ISSUE THREAD

**Issue by Suplanus** [microsoft/appcenter#1858]
Firewalls or Pi-Holes often block communication to App Center. It would be great to check if App Center can connect or is connected.

I don't find a workaround, tried a `HttpRequest` to `in.appcenter.ms` but this failed.
Have someone an idea for a workaround?

**Comment by Suplanus** [comment]
Its not a beauty code... but it works (for me) 🦄

```csharp
private static bool IsAppCenterConnected()
{
  try
  {
    string url = @"https://in.appcenter.ms";
    var httpWebRequest = (HttpWebRequest)WebRequest.Create(url);
    httpWebRequest.GetResponse();
    return true;
  }
  catch (WebException e)
  {
    return e.Response != null;
  }
}
```

**Comment by Suplanus** [comment]
Any update?

**Comment by Suplanus** [comment]
Bump

**Comment by Suplanus** [comment]
Bump

**Comment by DmitriyKirakosyan** [comment]
Hi Johann,

I would like to know more about your feature request.
Could you please share more details about the behaviour you want to achieve by using such API?

**Comment by Suplanus** [comment]
Sure 💖

I am using appcenter in my .NET apps. So it would be nice a Property like `Appcenter.IsConnected` to check if the client can reach Appcenter through proxies etc.

**Comment by DmitriyKirakosyan** [comment]
Thank you for the details.
Could you elaborate on this. Could you describe an example of usage of this API? How would your app react to the result returning by calling this API?
I just want to get a better picture of a possible use cases of such API.

**Comment by Suplanus** [comment]
In a desktop application the user can opt-in for a, we called it, "Appcenter logging". Then all critical events are logged into app center.
Our enterprise customers often have proxies in their companies which are blocking https://in.appcenter.ms.
So we want to give back a feedback in the UI if the connection fails.

**Comment by DmitriyKirakosyan** [comment]
Got it, thanks for the clarification! Looks like it is not a standard way of using AppCenter SDK. Since you expose the usage of AppCenter to users, I would rather recommend to handle such connectivity checks on your side.

Actually, this API won't work consistently, because there are many reason which can affect the connection stability. On the other hand, on your end you would be able to check if there is any proxy used on the device and handle it as you need. In case of proxy, you can use `SetLogUrl` API, see: https://github.com/microsoft/appcenter-sdk-dotnet/issues/624.

**Comment by Suplanus** [comment]
The user don't see anything about AppCenter. Its just a checkbox for "cloud logging". I described it for you directly to better understand :)

**Comment by wisdeom** [comment]
Hi @suplanus! Thank you for sharing the use case and starting this thread. It's an opportunity for us to learn better about our customers, and I'm sure the community will find your case informative.

From the feature request perspective, this can be tricky. I'm afraid this feature won't be as expandable for some scenarios, and might end up leading to confusion. For example, The API won't work as expected when the network connection on the end user side is not stable at the application start. Due to this discrepancy, the API usage will be very limited to specific scenarios. For this reason, I echo what @DmitriyKirakosyan suggested above to handle connectivity on the application side. Thanks again for sharing your feedback with us.
