### ISSUE TITLE
How to build a multi project android app?

### ISSUE THREAD

**Issue by deesharmahc** [microsoft/appcenter#1861]
My app consists of 5 modules and each module exists in a separate repository on GitHub.
The gradle `settings` from the main project includes all the other sub modules while building the app.
Is there a way to achieve this on AppCenter ? I could not find a way to link multiple projects together or connect multiple repos within a single App.

**Comment by nquangphan** [comment]
In your .gitignore file in the root of your project folder, you need to remove some lines, so that you check in these files. You must do this, to enable AppCenter to detect your Android app. If you don’t, AppCenter will not be able to find your Android app, and not be able to build.
# Android related
[REMOVE THIS LINE] **/android/**/gradle-wrapper.jar
**/android/.gradle
**/android/captures/
[REMOVE THIS LINE]**/android/gradlew
[REMOVE THIS LINE]**/android/gradlew.bat
**/android/local.properties
**/android/**/GeneratedPluginRegistrant.java

*from: https://buildflutter.com/deploying-flutter-apps-via-appcenter/
it's work for me
