### ISSUE TITLE
App Center iOS app

### ISSUE THREAD

**Issue by Mikilll94** [microsoft/appcenter#1893]
**Describe the solution you'd like**
For Android, there is a nice app in Google Play from which you can download releases. On iOS, there is no such app in the App Store.

It would be nice to be able to download releases from App Center iOS app.

**Comment by J-Swift** [comment]
Ive been looking all over for an app online because I assumed I was missing something, and couldn't understand why the apps in the app store were not by 'Microsoft'. I almost installed the top result for 'appcenter' because it looked convincing enough, only near the end did I realize the developer's name.

**Comment by MatkovIvan** [comment]
Hi there.

We don't have a similar iOS application because of Apple's App Store rules that don’t allow other App Store like applications. I'm closing this because we are not going to add it due to platform restrictions.
