### ISSUE TITLE
Manual APK release uploads are super slow

### ISSUE THREAD

**Issue by caltseng** [microsoft/appcenter#1896]
Manual APK release uploads are super slow. It takes ~10 minutes to upload a 80 MB APK. 

These upload significantly faster to other endpoints. AppCenter seems uniquely slow. I'm testing setting up automatic updates in code, but this makes it very frustrating.

**Comment by karimElJed** [comment]
I am experiencing the same with manual uploads of IPAs. It is super frustrating to wait such a long time for only 36 MB to get uploaded.

**Comment by kasimier-vireq** [comment]
For me it was 21 minutes for a 12 MB AAB file.
Just an empty Xamarin.Forms dummy app created using the VS 2022 17.4.0 Preview 4.0 templates.
I'm on a free App Center account for evaluation.

Actually the file upload only took ~ 10 seconds, but the process afterwards took 21 minutes.
We can see that because we are trying to use the web API directly as described in https://learn.microsoft.com/en-us/appcenter/distribution/uploading.
From the docs: "Once uploaded, there is a short delay before the upload is marked as finished. Poll for this status to get the $RELEASE_ID for the next step".
That delay is not short but very long.

Same results using the App Center CLI: it takes very long to "validate" the release upload- whatever that validation means.
