### ISSUE TITLE
App uploading failed due to new app-store version

### ISSUE THREAD

**Issue by jayesh-hyperspace** [microsoft/appcenter#1909]
See image build failed after in processing 
![image](https://user-images.githubusercontent.com/47419993/85016126-ba722c00-b186-11ea-8dee-4a9e2a4b97b8.png)
It may happen for new app-store update
https://github.com/fastlane/fastlane/issues/16621

**Comment by rlasker-b2w** [comment]
We just ran into this issue. Fastlane log indicates:

/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.150.0.rc1/spaceship/lib/spaceship/connect_api/client.rb:134:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - **You must provide a value for the attribute 'whatsNew' with this request** 

Field for release notes no longer applies for Apple Connect. I'm not sure how this is defined as a "feature request" as the release to stores is now broken.

**Comment by noxe** [comment]
Having the same issue - whats wrong here?

**Comment by rlasker-b2w** [comment]
@noxe I have a support ticket for this. It's a little cryptic but they might be intimating it's a fastlane issue by providing me this [link](https://github.com/fastlane/fastlane/issues/16645) but they have "back-end team" looking at it. I'll update this feature request as I hear more.

**Comment by noxe** [comment]
thank you!

**Comment by noxe** [comment]
As of today we now have an additional error message?

i cannot publish updates currently via appcenter?

Oops! Compliance Info and Release notes are not updated in App Store. Alternatively, you can set 'ITSAppUsesNonExemptEncryption' flag in info.plist and redistribute.

**Comment by rlasker-b2w** [comment]
@noxe, @jayesh-hyperspace ... can you provide the error messages from your fastlane logs? It would be helpful to see if we are getting the same errors or different ones. In my case the app still arrived at Apple Connect it was just missing information required to go to review. I was able to manually add the information and submit the app for review. I would recommend submitting a ticket with support and linking to this "feature request".

**Comment by noxe** [comment]
Hi,

"Oops! Compliance Info and Release notes are not updated in App Store. Alternatively, you can set 'ITSAppUsesNonExemptEncryption' flag in info.plist and redistribute."

[logs (3).txt](https://github.com/microsoft/appcenter/files/4858178/logs.3.txt)

**Comment by noxe** [comment]
I had manually uploaded the IPA today - and had to set some additional options, for the first time today? 

Ad-ID (IDFA) and some encryption export regulation... (https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations)

**Comment by jayesh-hyperspace** [comment]
Hi @rlasker-b2w 
Thanks for reply but right now i'm stuck other issue please look at this
And already updated plist file as per suggestion.
Here i'm attaching screenshot as well fastlane log so it might be helpful for you
[logs.txt](https://github.com/microsoft/appcenter/files/4859161/logs.txt)
![Screenshot 2020-07-01 at 10 04 20 PM](https://user-images.githubusercontent.com/47419993/86269209-0d1c0100-bbe7-11ea-9ee8-d735fedc0c79.png)

**Comment by noxe** [comment]
Had asolutly the same - i had to manually upload the IPA file today - and sign some export encryption compliance (https://developer.apple.com/documentation/security/complying_with_encryption_export_regulations) - and set an checkbox about an Ad-ID (IDFA) - after that i manually set the version for checking

**Comment by ajaykn** [comment]
@jayesh-hyperspace  and rest, 

There was so much stuff happened at fastlane side with much bigger commits adde addressing almost all the issues in this thread mentioned.
https://github.com/fastlane/fastlane/pull/16640

And we have rolled out our servers with this latest fastlane.
Would be great if you can retry. Thanks.

**Comment by noxe** [comment]
still does not work:

/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.150.1/spaceship/lib/spaceship/connect_api/client.rb:164:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request

[logs (2).txt](https://github.com/microsoft/appcenter/files/4901427/logs.2.txt)

**Comment by wocar** [comment]
Can we fix this!??!? thank you

```

# fastlane 2.155.3 is available. You are on 2.152.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': \e[31m[!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request\e[0m
	** Hidden Stack Trace ** `post'
	** Hidden Stack Trace ** `post_app_store_version_submission'
	** Hidden Stack Trace ** `create_app_store_version_submission'
	** Hidden Stack Trace ** `submit!'
	** Hidden Stack Trace ** `submit_for_review'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `block (2 levels) in run'
	** Hidden Stack Trace ** `call'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `run_active_command'
	** Hidden Stack Trace ** `run!'
	** Hidden Stack Trace ** `run!'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `start'
	** Hidden Stack Trace ** `take_off'
	** Hidden Stack Trace ** `<top (required)>'
	** Hidden Stack Trace ** `load'
	** Hidden Stack Trace ** `<main>'
/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
	** Hidden Stack Trace ** `post'
	** Hidden Stack Trace ** `post_app_store_version_submission'
	** Hidden Stack Trace ** `create_app_store_version_submission'
	** Hidden Stack Trace ** `submit!'
	** Hidden Stack Trace ** `submit_for_review'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `block (2 levels) in run'
	** Hidden Stack Trace ** `call'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `run_active_command'
	** Hidden Stack Trace ** `run!'
	** Hidden Stack Trace ** `run!'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `start'
	** Hidden Stack Trace ** `take_off'
	** Hidden Stack Trace ** `<top (required)>'
	** Hidden Stack Trace ** `load'
	** Hidden Stack Trace ** `<main>'

```

**Comment by calcazar** [comment]
Seeing the same issue as well using App Center

"You must provide a value for the attribute 'whatsNew' with this request"

**Comment by rlasker-b2w** [comment]
Just did a deploy on Friday and got this same problem. 

Support Id: c8492584-b26b-486a-adf6-4d1ac3672991

/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
	** Hidden Stack Trace ** `post'
	** Hidden Stack Trace ** `post_app_store_version_submission'
	** Hidden Stack Trace ** `create_app_store_version_submission'
	** Hidden Stack Trace ** `submit!'
	** Hidden Stack Trace ** `submit_for_review'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `block (2 levels) in run'
	** Hidden Stack Trace ** `call'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `run_active_command'
	** Hidden Stack Trace ** `run!'
	** Hidden Stack Trace ** `run!'
	** Hidden Stack Trace ** `run'
	** Hidden Stack Trace ** `start'
	** Hidden Stack Trace ** `take_off'
	** Hidden Stack Trace ** `<top (required)>'
	** Hidden Stack Trace ** `load'
	** Hidden Stack Trace ** `<main>'

**Comment by carlosmen-hrbl** [comment]
I am having this error while trying to send to Production App Store:
Oops! Something went wrong. Please check logs for more details. Support Id: 48711d0d-3c0f-4c27-aada-5f2cc3bb463b

When checking logs, I found out this:
/Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.152.0/spaceship/lib/spaceship/connect_api/client.rb:163:in `handle_response': \e[31m[!] The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request
The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request\e[0m

I did provide a release note, but maybe it needs to be localized as, whenever I go to App Store Connect, it asks me to fill the release notes for every language to be able to submit it. Are you going to provide a way to send localized release notes to fix this issue?

**Comment by dfjones1981** [comment]
We received the same error today: **You must provide a value for the attribute 'whatsNew' with this request**

Is there any update on this?

**Comment by wisdeom** [comment]
This seems to be a known issue on fastlane, which I reported to their repository. 
 https://github.com/fastlane/fastlane/issues/16700#issuecomment-670324834

**Comment by Woit** [comment]
try to force it in lane declaration, i pasted [example here](https://github.com/fastlane/fastlane/issues/16700#issuecomment-703312898)

**Comment by peirens-bart** [comment]
I have the same issue, is there any workaround?

**Comment by rlasker-b2w** [comment]
@peirens-bart while it is an annoyance it seems to be workable as, at least for me, the App still gets delivered to Apple Connect you just need to re-fill the What's new section.

**Comment by peirens-bart** [comment]
@rlasker-b2w what do you mean by "re-fill the What's new section". I can't see any field that label. the only thing I can see is "release notes " where is states "optional"

**Comment by rlasker-b2w** [comment]
@peirens-bart what I mean is that the app, at least for us, still got delivered to Apple Connect despite the error message in App Center. So you can fill in the missing details there and submit it for review.

**Comment by ilyakar** [comment]
Hi, still having this issue as the rest of the guys. Appcenter has been broken for months and still no fix?

**Comment by rlasker-b2w** [comment]
I am agains seeing this problem though it is a different and the end result is that the app does NOT make it to Apple Connect Store so there is no work around. It seems the only option will be to use Apple Connect on a mac. Since this is a new error and is blocking I am logging a new error for this.

The new fastlane error is:

[!] Syntax error in your configuration file './Deliverfile' on line 19: (eval):19: syntax error, unexpected constant, expecting '}'
    * "Object reference not set to an inst...
       ^~~~~~
(eval):19: syntax error, unexpected local variable or method, expecting '('
    * "Object reference not set to an instance of an object...
                            ^~~
(eval):19: syntax error, unexpected '}', expecting end-of-input
...ror message in certain cases."})
...                              ^
[0m

**Comment by rlasker-b2w** [comment]
Got this same problem again in a release today. Same result. App arrives at App Store Connect but release notes are not present. Any plans to fix this?

Users/runner/work/r1/a/ios-publisher/bundle/ruby/2.7.0/gems/fastlane-2.162.0/spaceship/lib/spaceship/connect_api/api_client.rb:188:in `handle_response': The request cannot be fulfilled because of the state of another resource. - Submit for review errors found. (Spaceship::UnexpectedResponse)
The provided entity is missing a required attribute - **You must provide a value for the attribute 'whatsNew' with this request**

**Comment by ilyakar** [comment]
I think we need to start looking for an alternative to AppCenter…
This critical bug has been around for months now and their support are saying they’re aware of it but with no plans on the roadmap to fix it...

**Comment by noxe** [comment]
same here....

**Comment by SalihZinaty** [comment]
same here!! -

**Comment by Brosten** [comment]
@ajaykn What happened to the update?
This is still an issue. Can you please provide us with info about why this potentially pretty easy fix isn't prioritized?

**Comment by rlasker-b2w** [comment]
@ajaykn support had sent me this:

"we are waiting for the fix from fastlane. which haven't provided any updates as of yet  https://github.com/fastlane/fastlane/issues/16700#issuecomment-670324834"

**Comment by LucasPMM** [comment]
Hello guys, any updates? I'm facing the same issue here : `The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request`

**Comment by ilyakar** [comment]
It’s been 6 months and they haven’t fixed the problem. This happens when Microsoft buys a product :)
I switched to codemagic.io, took a few hours to set up but it’s working perfectly.

Kind regards,
Ilya
Founder/CEO at Einee
The app that teaches kids what schools do not.
Einee | LinkedIn | Twitter

**Comment by ronaldobutrus** [comment]
> Hello guys, any updates? I'm facing the same issue here : `The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request`

It appears our current workaround is to simply log into App Store Connect after we attempt to distribute, add the "What's New" text and submit manually. 

We need a fix!

**Comment by LucasPMM** [comment]
> > Hello guys, any updates? I'm facing the same issue here : `The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request`
> 
> It appears our current workaround is to simply log into App Store Connect after we attempt to distribute, add the "What's New" text and submit manually.
> 
> We need a fix!

Yes, I did that and it worked. But I have more than 40 apps to release continually and we use GitHub actions to automatize the deployment process. I need to automatize the greatest part of the process in order to improve our scalability. Unfortunately, release everything manually is not an option for us....

Please guys, fix that asap

**Comment by Brosten** [comment]
Seems like a work is in progress in fastlane.
https://github.com/fastlane/fastlane/issues/16700

Are you (AppCenter folks) following this progress?

**Comment by A-Kojic** [comment]
This issue is not yet resolved (first time encountered it 4 months ago). Even though I provide 'whatsNew' content , I still can't submit my apps to the Apple store from the AppCenter : _"The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request"_

**Comment by Brosten** [comment]
I get the feeling MS are silently abandoning AppCenter.
From the RoadMap I can read

_Just like any software engineering team, as we focused on building and scaling App Center, we accumulated technical debt that can no longer be sustained. Therefore, as we look to what is next, the App Center team will **prioritize improving reliability and performance** for the service through mid-2021_

So, focus is on reliability and performance. This is defenetively to categorize as reliability. But the response on this issue is close to zero. :(

**Comment by rodrigomafei** [comment]
same bug around here

**Comment by webmasterdevlin** [comment]
OMG. It's been a year now since this issue was reported. Last week, I faced this issue and had to submit our IPA file to Apple Store manually.  ='(

**Comment by dougg0k** [comment]
I got the issue here, but then it was in the applestore connect with a Prepare for submission status. It seems that at least the IPA was uploaded.

**Comment by Manouli** [comment]
I successfully uploaded the ipa I get a status of failed but the ipa goes to Appstore. Only thing I got to do is manually add the whats new and send for review. No the end of the world I guess.

**Comment by A-Kojic** [comment]
> > Try to delete existing project and create a new one.
> 
> Do you mean 'add new app'?

Yes, I've added a new app and since then this issue didn't occur any more

**Comment by snice1981** [comment]
same problem here. Any news on a real fix?

**Comment by velimir-jankovic** [comment]
> same problem here. Any news on a real fix?

Hello! We've updated to version 2.196.0 of Fastlane in our services. Can you please try creating a new app and see if issue still occurs?

**Comment by picninim** [comment]
> > same problem here. Any news on a real fix?
> 
> Hello! We've updated to version 2.196.0 of Fastlane in our services. Can you please try creating a new app and see if issue still occurs?

Yes is still occurring, "Release notes" data coming from AppCenter is not reaching "What's new" on Apple store API

**Comment by sash** [comment]
Guys, this is getting ridiculous! Is there a workaround that doesn't include manual work? We are using AppCenter to distribute close to 100 apps - manual doesn't cut it!

**Comment by picninim** [comment]
Well, we are moving on Jenkins + Fastlane due to this issue and some others like keep losing the AppleStore auth, and the config based by branches which enforces a project pattern :/

**Comment by qbunia** [comment]
Yep got the same error still not fixed

**Comment by megajogos** [comment]
Any news? We have a lot of apps in five languages so it is terrible to manually enter the "whats new"!

**Comment by Martinedo** [comment]
It can be done without creating a new version in Connect. If you publish via AppCenter it creates a new version without "Whats new", but there is a time window till Apple processes the build. So you have like 10 minutes where you can edit and save the new version. After the time window fastlane completes the publishing and Connect won't throw an error with missing Whats new.
We do it like that for many apps (like 100). It would be better without this small manual edit!! But it works.

**Comment by wisdeom** [comment]
Hi - The connect API connection should be able to solve this known issue. It's available in the portal, so please give it a try and report any issues you might face. I'm doing my best with the current priorities and capacity we're at, but my sincere apologies we are not as fast in resolving issues. Thank you for your patience.

**Comment by brux88** [comment]
i have the same problem, its no Wasn't it fixed via app center?

**Comment by danielftz** [comment]
So this still seems to be an issue? On App Store Connect the "What's New in This Version" section is blank, despite filling in "release notes". As a result the app is not automatically submitted for review to the app store

**Comment by AlessandroAries** [comment]
I am also facing this issue in version 5.0.0 of appcenter. I have to manually add the "What's New" string on AppStoreConnect everytime I distribute via AppCenter. Since the upload fails (`The provided entity is missing a required attribute - You must provide a value for the attribute 'whatsNew' with this request[0m`) and the build stays on "Prepare for Submission" until you fill in the "What's new" string.
![image](https://github.com/microsoft/appcenter/assets/15822086/6e9b5920-8f99-4e30-a5bb-78be39d2d414)

**Comment by AshleyEke** [comment]
> The connect API connection should be able to solve this known issue.

@wisdeom Could you explain more about what you mean by this? Are you referring to the app store connect integration within AppCenter? I couldn't see anything relevant we can set there to resolve the issue.
