### ISSUE TITLE
Cordova: Support for Handled errors

### ISSUE THREAD

**Issue by Lubans** [microsoft/appcenter#20]
**Reporting of Handled errors** is currently supported for Xamarin only.
Would be nice to have this for Cordova (and other platforms also).
Nothing special is needed, just same functionality as exists for Xamarin

**Comment by patniko** [comment]
Thanks for the feature request! We're always talking about how we'll carry handled errors over to other platforms and will be happy to keep this open to track general interest in adding support for this.

**Comment by ElD4n1** [comment]
Any updates on this?
It would be great to have at least a statement about the status of this issue or what makes it so difficult to add support for other platforms than Xamarin.
I'm especially interested in tracking handled (JavaScript) exceptions for Cordova apps and as far as understood I can only achieve this by using custom events with properties which sometimes makes it a little bit difficult, when attaching a stack trace for example.

**Comment by winnieli1208** [comment]
Hi there! This isn't on our immediate roadmap so unfortunately, I don't have an ETA. As Patrick mentioned, we definitely hope to bring handled errors to other platforms but due to other priorities, such as supporting HockeyApp scenarios, our team hasn't invested much time into this. 

We will continue to monitor this feature for community support to help our team prioritize. In the meantime, the workaround would be to use custom events as you mentioned. I understand this isn't an ideal experience and I'll make sure to post here with any updates. Thanks!
