### ISSUE TITLE
Support for XCTestplans

### ISSUE THREAD

**Issue by bobmosh** [microsoft/appcenter#2046]
It would be a really nice feature to have the option to use [XCTestplans](https://help.apple.com/xcode/mac/current/#/dev2d0f63f98) for test execution. This feature allows for easy splitting of multiple tests into different test runs, relevant for different teams and brings many organisational benefits to our project. We are happily using Testplans locally but have to revert to using Xcode Schemes for achieving the same test separation using AppCenter Testfarm. Also this feature allows for testing using multiple app configurations (localisation, locations etc.) wich is not possible as easily with Xcode schemes.

**Describe alternatives you've considered**
We have worked with Xcode Schemes to achieve the separation but thanks to multiple staging environments and multiple teams with separated concerns, we have reached a very very high number of schemes that have become very difficult to handle.

**Comment by automagicallyio** [comment]
+1

Desperately need support for XCTestplans. Otherwise, can't use Appcenter for IOS testing and have to fallback to using simulators and command line which is far from ideal.

**Comment by AnatoliBenke-Helsana** [comment]
+1

We also require that feature for our UITesting on AppCenter. Testplans are most clear and clean solution on XCUITest.

**Comment by andrejacobs-unily** [comment]
+1

Just got bitten today by the fact that AppCenter builds now fail because we switched over to using test plans. However this had to be removed and now we can only do tests locally.

I have +1 voted here, but I am not going to be holding my breath on this one. Given that we have waited years for some of the most basic features that other services offer and that the official road map states: "App Center team will prioritize improving reliability and performance for the service. This means new feature work will be significantly reduced."

At this rate we might have to switch over to Xcode Cloud just to keep current. Right now neither App Center nor Azure Pipelines (which just shares App Center + Git Hub tech anyways) can't even give us Xcode 12.5 (building on Big Sur) support.
