### ISSUE TITLE
Appcenter iOS install error “this app cannot be installed because its integrity could not be verified”

### ISSUE THREAD

**Issue by DragonflyJones** [microsoft/appcenter#2107]
I see that this question has been asked many times but I see no solution that works for me so I'm hoping that providing more info might shed some light.

We use appcenter.ms to test iOS apps. Until our iOS certificate expired this method worked fine. We generated a new enterprise certificate and ad hoc provisioning profile for new releases of the iOS app. Which led to the first curiosity.

I see how to upload a certificate on appcenter.ms but not a provisioning profile. I thought there was an option to do this in the past but perhaps I am mistaken. However, the app is signed with a provisioning profile before upload, so perhaps this is not needed now.

Once the app is uploaded, it can't be installed. It remains grey and when you tap it, you get the "this app cannot be installed because its integrity could not be verified" error. Again, that the .ipa is created with an ad hoc certificate and profile in Xamarin (VS for Mac).

Also, I can't install the provisioning profile on a device from appcenter.ms. You basically get stuck in a loop where you seem to successfully install the profile but have to keep doing it because it never actually installs.

I hope this is enough info for some insight and thanks in advance for any feedback.

**Comment by kpietrzak-web** [comment]
Same here. Me and everyone in my team has same problem.

After successfully installing profile and successfully installing app - it's installing but icon is "disabled" and when trying to launch it this info appears.

**Comment by Geremp** [comment]
Same Probleme here …

**Comment by m4rcoperuano** [comment]
Why was this closed without resolution?

**Comment by ikmrgrv** [comment]
@DragonflyJones Did you find any solution to this ??

**Comment by Geremp** [comment]
Hello,
Yes, my device ID was missing in the provisioning profile. That’s why. 

Cordialement,

Jérémie PERERA

**Comment by m4rcoperuano** [comment]
My issue was that the Provisioning Profile was expired. For some reason, never got an alert from Apple >_<

**Comment by ramtechjoe** [comment]
I am having this issue suddenly.  I have confirmed provisioning profiles are correct.  I have created new certificates and generated new provisioning profiles confirming everything is included.  I cannot install applications and receive "the this app cannot be installed because its integrity could not be verified" error.

The build I use pushes to AppCenter from DevOps.  I have also tried to create a build in AppCenter and these will not even build.   The build is cancelled in 0 sec before it even starts

**Comment by oliver-ep** [comment]
I have the same issue suddenly also, as of last Friday. I'm using automatic provisioning, and just tried to onboard 20 testers yesterday - some are reporting this issue.
I've tested this same provisioning profile and distribution to work last Wednesday internally.

**Comment by oliver-ep** [comment]
@ramtechjoe for this app I did not use devops pipeline - just AppCenter Build and Distribute.

There were a couple of things I noted through my experience though: 
1. some users' default browser was chrome, not safari and that seemed to be a thing to keep an eye on
2. some users directly went to install.appcenter.ms, log in, and then downloaded the app, instead of following the email link - this skipped device registration and provisioning workflow. This was an issue for one user for me at least, where in the past they provisioned a different iOS device in the past - so on AppCenter -> App -> Distribution -> Group -> Devices view, it looks like the user is using a provisioned hardware (but the reality was different). For that user, asked to follow email link and they went through the device registration flow, after that a new device was displayed on AppCenter and I was able to click a button to register their device. That fixed it for that user.

**Comment by DragonflyJones** [comment]
I resolved this by downloading an older version of xcode and and point visual studio to that. I then regenerated all of my provisioning profiles and everything is working again.

**Comment by ramtechjoe** [comment]
@oliver-ep interesting observations.  I do have my device manually added to AppCenter and is still a problem but will look at that.  All the other users just use the provisioning profile, we have 97 testers and getting them to all do the manual operation to register devices will be pretty tough

AppCenter build and deploy uses devops pipeline behind the scenes, just gives a very nice interface to doing setup.

@DragonflyJones what version did you use?  I rolled back to 12.51 after upgrading to 13.0 broke xamarin (Xamarin.iOS is not yet compatible with xcode 13.0) but still have the issue

Sticking with my very brute force approach till I get everyone up and running then will start working on it again

Thanks for the input

**Comment by DragonflyJones** [comment]
I too went back to 12.51.

**Comment by tamirla** [comment]
> @ramtechjoe for this app I did not use devops pipeline - just AppCenter Build and Distribute.
> 
> There were a couple of things I noted through my experience though:
> 
>     1. some users' default browser was chrome, not safari and that seemed to be a thing to keep an eye on
> 
>     2. some users directly went to install.appcenter.ms, log in, and then downloaded the app, instead of following the email link - this skipped device registration and provisioning workflow. This was an issue for one user for me at least, where in the past they provisioned a different iOS device in the past - so on AppCenter -> App -> Distribution -> Group -> Devices view, it looks like the user is using a provisioned hardware (but the reality was different). For that user, asked to follow email link and they went through the device registration flow, after that a new device was displayed on AppCenter and I was able to click a button to register their device. That fixed it for that user.

this was also the issue in my case - user was using chrome as default browser, once opened the link with Safari it works.

**Comment by zkyronex** [comment]
> > @ramtechjoe for this app I did not use devops pipeline - just AppCenter Build and Distribute.
> > There were a couple of things I noted through my experience though:
> > ```
> > 1. some users' default browser was chrome, not safari and that seemed to be a thing to keep an eye on
> > 
> > 2. some users directly went to install.appcenter.ms, log in, and then downloaded the app, instead of following the email link - this skipped device registration and provisioning workflow. This was an issue for one user for me at least, where in the past they provisioned a different iOS device in the past - so on AppCenter -> App -> Distribution -> Group -> Devices view, it looks like the user is using a provisioned hardware (but the reality was different). For that user, asked to follow email link and they went through the device registration flow, after that a new device was displayed on AppCenter and I was able to click a button to register their device. That fixed it for that user.
> > ```
> 
> this was also the issue in my case - user was using chrome as default browser, once opened the link with Safari it works.

Our issue was not fixed, after telling users to set their default browser to Safari instead of Chrome, the App page showed a gray `Get` button instead of a blue `Install` one and got the "app unable to be built" error. Uninstalling the Chrome app doesn't work at that point.

So far the only surefire way is to use a device without a chrome ever being the default browser.
Any help would be appreciated.

**Comment by ollydixon** [comment]
This issue has returned with ```iOS 16.1.2```

**Comment by SyntactixGmbH** [comment]
Today I have also this issue. The last version we deployed through AppCenter was on Dec 1, and this version worked. We didn't change any Certificates and Profiles and all are still valid, and today I got this error. Don't know how to fix.

**Comment by yudhacashenable** [comment]
Something is wrong with my app in last 1-2 days on testflight

> Today I have also this issue. The last version we deployed through AppCenter was on Dec 1, and this version worked. We didn't change any Certificates and Profiles and all are still valid, and today I got this error. Don't know how to fix. And I saw in the build log that AppCenter used an macos-12 image with version 20221204.1, so I think this image was updated 4 days ago.

**Comment by SyntactixGmbH** [comment]
I have found a workaround to be able to install the app. I added an external tester in the testflight section and the current build, then I was able to install and start the app.

**Comment by antpuleo2586** [comment]
I've opened a support issue with App Center but so far unresolved as they aren't acknowledging there is any issue. I can confirm I can successfully build and distribute then install via TestFlight when I use the same profile and certificate on XCode on my Mac, so issue is for sure with App Center.

**Comment by softsan** [comment]
Same issue here. Not able to install the latest  or older build from AppCenter

**Comment by Brad19** [comment]
I've have the issue where the app cannot be installed because its integrity cannot be verified. Here are the things i tried
1. opened install.appcenter.ms in safari private mode and added the device and installed the appcenter certificate.
2. went to apple developer portal and added my device under profiles (in this case distribution profile).

Basically we use fastlane match profile via pipelines to sign the certificate. It has been working in the older devices which was previously registered. When we added couple of new devices, it didn't work and it throws the same error.

Not sure whatelse i'm missing. If anyone knows the solution, Please advise

**Comment by justingiffard-impact** [comment]
Hi all, Im also having this issue. I'm new to this and at this point Im not 100% convinced I'm doing everything correctly.

So for starters I can download perfectly on my device, but Im on the provisioning profile so I'm assuming that thats why it works for me. My manager and product manager tried to download from AppCenter and weirdly the first time it allows them to download but then there after it tells then "The developers are working on a version for your device". The one they installed first attempt gives the same error mentioned here (ie "this app cannot be installed because its integrity could not be verified"). If we follow the link from the email they get the option to install again but it still gives the same issue.

Interestingly enough when the get the "The developers are working on a version for your device" you can sat "previous versions" and get that list of releases but there is no 'download' button. The download button does appear on the latest build if you tap an older build but only for a fraction of a second then vanishes. Lovely

I have 3 builds on AppCenter: Prod, UAT and Stubbed. Both Prod and UAT use adhoc provisioning profiles and then Stub uses a development profile but all three do the same. I though maybe that because they aren't on the provisioning profile that that could be why the adhoc builds aren't working but shouldn't the development build work? Do they need to be on the provisioning profile for both cases?

**Comment by adil-hussain-84** [comment]
I was getting this error on one of my iOS devices despite my iOS device being included in the Ad Hoc provisioning profile which was used to sign my app.

The issue for me was that I had not (1) added the device to my App Center account and (2) installed the App Center profile on the device.

You can see which devices are already added to your account by navigating to https://install.appcenter.ms/profile.

You can add a new device to your App Center account by navigating to https://install.appcenter.ms/register-device on the device that you want to add. Follow the instructions to add the device to your account and to install the App Center profile on the device.

All of this (and more) is explained in the [Testing iOS Apps > Adding your Device](https://learn.microsoft.com/en-us/appcenter/distribution/testers/testing-ios#adding-your-device) App Center documentation page.

**Comment by Json-serialization513** [comment]
https://stackdev.space/questions/discover-the-steps-to-embedding-a-provisioning-profile-in-your-ios-application



The answer’s in sight
