### ISSUE TITLE
Support for Uno Platform WebAssembly

### ISSUE THREAD

**Issue by MartinZikmund** [microsoft/appcenter#2195]
**Describe the solution you'd like**

Currently it is possible to use AppCenter in almost all Uno Platform targets, but not with WebAssembly. Having it supported would be very valuable for fully cross-platform app analytics.

This might be tackled simultaneously with #1084.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by russelarms** [comment]
Hi @MartinZikmund, thanks for opening the feature request!

At the moment our .NET SDK is heavily coupled with Windows and requires an additional effort to make it WASM compatible. Details:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/1513
I don't have an ETA for it, cause at the moment App Center is [focused](https://github.com/microsoft/appcenter/#planning) on performance and reliability, rather than implementing new features or supporting new platforms.
