### ISSUE TITLE
Error: /usr/bin/xcodebuild failed with return code: 65

### ISSUE THREAD

**Issue by mvn-trungle-dn** [microsoft/appcenter#2209]
**Describe the solution you'd like**
I use swift language to code, and when I build with appcenter, there is an error code like this, deployment info is ios 14, after getting error code: 65,  i fixed ios 13, because according to log i read virtual running mac 10.15.3 so i think Xcode can't run ios 14. i fixed ios 13 but still error.

**Describe alternatives you've considered**

**Additional context**
![Screen Shot 2021-06-11 at 1 16 55 AM](https://user-images.githubusercontent.com/67259297/121576592-b9e73b00-ca52-11eb-932a-26358c46980b.png)

**Comment by akamenev** [comment]
Hi @mvn-trungle-dn! Thanks for submitting the issue! It looks like you have some problems building your app - please open a ticket through the App Center portal so that support engineers can help you with this issue. Here is [the link](https://docs.microsoft.com/en-us/appcenter/help) that describes how to do it.

**Comment by mvn-trungle-dn** [comment]
Hello,
I was fixed it. Thanks very much

Vào 20:07, Th 5, 17 thg 6, 2021 Andrei Kamenev ***@***.***>
đã viết:

**Comment by kostiantyn-solianyk** [comment]
Same issue, @mvn-trungle-dn how did you fix this?

**Comment by mvn-trungle-dn** [comment]
I fixed it. You update avatar for app, will fix it.

Vào 0:21, Th 6, 2 thg 7, 2021 Kostiantyn Solianyk ***@***.***>
đã viết:
