### ISSUE TITLE
Leaky repo logins

### ISSUE THREAD

**Issue by TaylorDale** [microsoft/appcenter#2214]
I've just logged out of one account for one company (A), and created a new account for company (B). The Github repo for company (A) was immediately available on the brand new account (B). This is a little concerning for info security purposes. 

The only solution I can see is to unlink the GH account via their interface which breaks my setup with (A). This is concerning and frustrating to work with!

**Comment by akamenev** [comment]
Hi, thanks for submitting this request. This is actually a known issue to our team, and we're trying to make improvements on the flow. Please stay in tune with us!

**Comment by akamenev** [comment]
@TaylorDale sorry for the confusion, I actually referred to a different issue that our team was working on that seems to be not related to what you're describing. 

Could you please share step-by-step details on how to reproduce this issue? What type of accounts do you use to log in and are there any relations between those accounts and organizations?

**Comment by TaylorDale** [comment]
No worries.

Two companies/user accounts: A & B.

Link Github to account A. Sign out of account A. 
Sign up for an account for company B. Github from account A is immediately authorised and available to account B.

**Comment by denysop** [comment]
Hello @TaylorDale,

My name is Denys and I am a part of the development team from AppCenter. I am looking into the issue you've reported and would like to get some more details in order to have clear picture of the case:
1. "Two companies/user accounts A & B". At this step we create two GitHub user/company accounts.
2. "Link Github to account A. Sign out of account A." At this step you sign-up to AppCenter with GitHub credentials of account A and then do sign-out. New account on AppCenter side created. How do you link it to the source? Do you use GitHub AppCenter app for that? Afterwards you sign-out. 
3. Now you sign-in with GitHub account B credentials. Also new account on AppCenter side is created. Do you use GitHub AppCenter app here?
After steps specified AppCenter account B has an access to resources of GitHub account A in the AppCenter which is concerning.
Please let me know if my understanding is correct so that I can proceed with the investigation.

Thanks in advance!

**Comment by TaylorDale** [comment]
Hi,

Close, in my case the order was important:


   1. Create company A - AC (AppCenter) account.
   2. Link company A GH (Github) account to company A AC account.
   3. Sign out of company A AC account
   4. Create company B AC account and sign in
   5. Click "Github link" button
   6. GH Account A is immediately available to company B

I did this in the same browser window. It was a while ago.
