### ISSUE TITLE
[BUG] Android App is broken since June 23rd

### ISSUE THREAD

**Issue by vesper8** [microsoft/appcenter#2229]
Have a look at the Google App Store listing for Visual Studio App Center: https://play.google.com/store/apps/details?id=com.microsoft.hockeyapp.testerapp

Starting from June 23rd there are reports of releases no longer showing up. I just pushed a new Android release via the appcenter-cli and I'm also getting this error.

It also appears as though the App Center app is not even searchable on the app store? I had to use a direct link to get to the above listing otherwise I can't find it.

This seems like a very serious problem!! I'm not sure if here is the right place to mention it but can't find any other place.

**Comment by joemather** [comment]
The app is deprecated.  Use the web portal instead:

"Visual Studio App Center is no longer available in the Google Play store. Unfortunately, Google Play store considers the in-app update code as malicious behavior even if it isn’t used at runtime. There are no current plans to bring the app back to the Google Play store due to their policies. The same set of functionality is still available via the App Center install portal."

Source:
https://docs.microsoft.com/en-us/appcenter/distribution/testers/testing-android

Possible dup of:
https://github.com/microsoft/appcenter/issues/2174

I have no other info.  I'm just relaying what I've read in other threads.

**Comment by AnastasiaKubova** [comment]
Hi there! You are right. Unfortunately Visual Studio App Center app is no longer available in the Google Play store due to Google Play restrictions but you can use the App Center install portal instead.

**Comment by mzimdars-gms-online-de** [comment]
As there is no principle issue with 'alternate stores' (functionality wise I would consider the App something like this) on Android, will you make the app available as an APK so that it is possible to install it as a side load?

**Comment by AnatolyPristensky** [comment]
Hello, @mzimdars-gms-online-de, unfortunately we don't have any plans for the Android app release as APK, we recommend to use the portal.
