### ISSUE TITLE
Requesting to change dll name shipped with microsoft.appcenter.distributeplay.4.3.0.nupkg

### ISSUE THREAD

**Issue by Vinayak-Nikam** [microsoft/appcenter#2245]
**Describe the solution you'd like**
While shipping my xamarin.forms application to the google play, I shipped the microsoft.appcenter.distribute.dll and my app got rejected. On investigation I realised that microsoft.appcenter.distributeplay.4.3.0.nupkg and microsoft.appcenter.distribute.4.3.0.nupkg both contains the dlls with same name. I suppose, if appcenter removes this name ambiguity between these two dll's, it will be more easier for sdk consumers to find such problems earlier. This will save us consumers from lot of frustration and time waste; which is caused due to google removing or suspending app from the google play console.  

**Describe alternatives you've considered**
I recommend microsoft.appcenter.distributeplay.4.3.0.nupkg should ship dll with name "microsoft.appcenter.distributeplay.dll". Having dll with another name will make us easier to identify if right dll goes to the google play console for review.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
The `Distribute` and `DistributePlay` modules have the same assemblies name to avoid extra changes in the customers' apps. 
The `DistributePlay` contains stub methods for the `Distribute` module and has no in-app update implementation. When you add `DistributePlay` to your project before publishing your app to Google Play it replaces the main assemble of the `Distribute` module and you don't need to add additional changes to your app.

Please make sure that before publishing to Google Play you have the correct assemble with the `DistributePlay` module and you have no other publications for your app (for example for testers) where still use the `Distribute` module.

**Comment by Vinayak-Nikam** [comment]
@AnastasiaKubova Highly appreciate your response. I understand how Distribute and DistributePlay works under the hood. I need a full proof way with minimum ambiguity that will make sure that I'm not shipping wrong dll to google play store to avoid any app rejection. If there is any other work around, I'm happy to use that.

**Comment by AnastasiaKubova** [comment]
If you use `Xamarin.Forms` please make sure that you install `DistributePlay` to [both](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#remove-in-app-updates-for-google-play-builds) shares and `Xamarin.Android` projects.

You can check in the logs which module you use in the current assembly:
- Enable [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level).
- Make sure that in logs you can see the `DistributePlay` service in `startService` logs.

**Comment by Vinayak-Nikam** [comment]
@AnastasiaKubova Is there any way to identify in generated APK?

**Comment by AnastasiaKubova** [comment]
not sure if you didn't enable logs

**Comment by Vinayak-Nikam** [comment]
@AnastasiaKubova That's the reason, I'm saying its very risky and easy to ship wrong dll to google play. Nowdays Google is rejecting all the apps using Microsoft Appcenter SDK for the same reason. And Appcenter team should come up with some foolproof way to avoid this happening.

**Comment by AnastasiaKubova** [comment]
Google Play rejecting apps that use the `Distribute` module because it contains in-app update implementation. To avoid this situation in App Center SDK exist `DistributePlay` [module](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#remove-in-app-updates-for-google-play-builds) which contains stubs for the main module. It replace the main assemble to assemble with stubs API without additional changes in the code.
To makes sure that you use the right assemble you can check in the logs (after enabling [verbose logs](https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/xamarin#adjust-the-log-level)) or in the build logs after assembly your app (the logs shouldn't contain `Microsoft.AppCenter.Distribute.Android.Bindings.dll`)

**Comment by Vinayak-Nikam** [comment]
@AnastasiaKubova This helps now. Before closing this issue, I will appreciate if same is updated to microsoft documentation on this link - [https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#remove-in-app-updates-for-google-play-builds](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#remove-in-app-updates-for-google-play-builds).

**Comment by AnastasiaKubova** [comment]
Sure, we will update the [troubleshooting page](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin) for the Xamarin platform.

**Comment by nielscup** [comment]
Same problem here: one of my customers' apps got suspended today because of Appcenter SDK. The app was rejected recently because of the Appcenter.Distribution sdk so I removed the Appcenter.Distribution sdk and republished the app. The app is only using Appcenter.Crashed and Appcenter.Analytics now. But today it got suspended and the entire dashboard for this app is disabled so I have to appeal because I cannot fix it anymore:



> Issue with your app
> --
> Your app contains content that doesn’t comply with the Device and Network Abuse policy. We found your app is using a non-compliant version of Microsoft Appcenter SDK which contains code to download or install applications from unknown sources outside of Google Play.If necessary, you can consult your SDK provider(s) for further information.

It doesn't mention `Distribute` this time, so I don't know what is wrong now.

**Comment by Vinayak-Nikam** [comment]
@nielscup  
Removing Distribute dll solved my problem. Just make sure that while re-submitting the app, all the non compliant versions of the app are shown in "Not-Included" section of the release. If the Non compliant apk remains in "Included" section by mistake in any of the tracks - production, open testing, closed testing or internal testing, google again reviews the old apk and app gets rejected another time for the same reason.

**Comment by nielscup** [comment]
Thanks for the tip but I cannot do that anymore because the app's dashboard is disabled entirely...

**Comment by Vinayak-Nikam** [comment]
@nielscup  Yes that's true; Now you will have to wait until google accepts your appeal.

**Comment by nielscup** [comment]
I really don't understand why Microsoft distributes dangerous stuff like this: why would you publish an app library that causes your app to get suspended...

**Comment by AnastasiaKubova** [comment]
Hello, @nielscup ! Thanks for getting in touch with us!
This message is related to [this](https://support.google.com/googleplay/android-developer/answer/9888379?hl=en#zippy= ) restriction of Google Play. This restriction has started to affect our customers since last year and the App Center SDK team timely [released](https://github.com/microsoft/appcenter-sdk-dotnet/releases/tag/3.4.0) an additional `DistributePlay` module with stubs methods of the main `Distribute` module.
The `Distribute` module should be used for apps downloaded from App Center portal only. If you need to `Distribute` your app via Google Play you have to replace `Distribute` module with `DistributePlay` (how to do it you can read [here](https://docs.microsoft.com/en-us/appcenter/sdk/distribute/xamarin#remove-in-app-updates-for-google-play-builds)). The `DistributePlay` module doesn't have any in-app update code and does not fall under the restriction of Google Play.

If after replacing `Distribute` module with `DistributePlay` your app still gets rejected, please follow the steps below to verify that the Distribute module was replaced correctly:
- Make sure that you replaced `Distribute` with `DistributePlay` in all your releases for all your publishing groups in Google Play Console.
- If you use `Xamarin.Forms` please make sure that you add the `DistributePlay` module to both shared and `Xamarin.Android` projects.
- Verify that your output file does not contain the `Microsoft.AppCenter.Distribute.Android.Bindings.dll` assembly. You can use the [APK Analyzer](https://developer.android.com/studio/build/apk-analyzer) to check it.

We improved docs about it and we will notify you when these changes will be released.

**Comment by AnastasiaKubova** [comment]
Hi there! We published [improvements to docs](https://docs.microsoft.com/en-us/appcenter/sdk/troubleshooting/xamarin#google-play-rejects-the-application-after-adding-distributeplay) about the Google Play app rejection after adding DistributePlay. I am closing this issue but feel free to reopen it if you will have additional questions.
