### ISSUE TITLE
UITests on iOS: Incorrect coordinate calculation in NON Portrait orientation

### ISSUE THREAD

**Issue by lasseOL** [microsoft/appcenter#2305]
**Describe the solution you'd like**
We experience a incorrect coordinate position in our UITests in App Center.

If you start an iPad app in landscape orientation by eg. removing the Portrait orientations in Info.plist supported interface orientations (iPad), the coordinates are calculated incorrect when trying to do app.Tab etc. commands. It seems like it always calculate in Portrait (Bottom button) orientation. Our test starts working again, if we add this portrait orientation. 

It can also be reproduced by calling the app.SetOrientationLandscape() in an UITest and then all test commands with coordinate calculations is using incorrect coordinates.

We use
Xamarin.TestCloud.Agent 0.23.0
Xamarin.UITest 3.2.2

We use the mac-OS11 hosted environment
with Xcode 12.5.1 and Xamarin symlink 6_12_9

**Comment by DanielGlick45** [comment]
Any update on this issue? I am running into the same problems running Xamarin.UITest on an iPad

**Comment by lasseOL** [comment]
It has been fixed in Xamarin.TestCloud.Agent 0.23.1

**Comment by ccxla** [comment]
I am still observing this behavior with 0.23.1.

**Comment by yamamoo** [comment]
Please don't close this issue. I also have the incorrect coordinate issue with iOS Simulator running in landscape mode. I initially noticed this when our test stopped working. The app.Flash() was flashing the correct element but app.Tap() on the element did not tap. It was actually tapping the wrong position on the app so the tap event was ignored. Then I noticed X and Y coordinates returned by app.Query() were based on the Portrait orientation.

Out app was built with Xamarin.TestCloud.Agent 0.22.2 so I updated it to 0.23.1. After that, the tap started to tap the correct element. However, the coordinate values returned by app.Query() were still Portrait orientation based even though our app is showing in Landscape mode. For example, the top-left corner of our app has the coordinate like (0, 1180) instead of (0,0) and the bottom-right corner is (820,0) instead of (1180, 820). If I run `app.Query().First().Rect`, it returns `Width => 820, Height => 1180`. This is very confusing.

If I remember correctly, the coordinates returned by app.Query() always agreed with the current screen orientation, i.e., the top-left corner of the app was always (0,0). It was more than a year ago and there were many changes (Mac OS, Xcode, iOS, Visual Studio for Mac, Xamarin.UITest and libraries used by our app) so not sure what is causing this issue.
