### ISSUE TITLE
Android Activities with Intent Filters cause Stalled Errors during AppCenter builds.

### ISSUE THREAD

**Issue by DP-Technology-LLC** [microsoft/appcenter#2364]
First, thank you to the support people that provided the solution on the first try.

My AppCenter Android builds were stuck in a Stalled Error with no indication of why.  My local builds built successfully and deploying the app to a local device had no issues, no issues using the app on the Android device either.

The compiling of the code was successful in AppCenter but the next Task would get the Stalled Error after a few minutes.

Task         : App Center test
Description  : Test app packages with Visual Studio App Center
Version      : 1.152.3
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/test/app-center-test

The correct fix suggested was to create the "Exported = true" attribute.  This fix needed to be applied to any Activity (or AppWidgetProvider) that had an IntentFilter.

My app is in the Google Play Store, I manually uploaded the package and the app has no functionality issues.  I am ready to push an update and was planning on using AppCenter but I couldn't get a successful build until I applied the Exported=true attribute to the Activities that had an IntentFilter(not all my Activities needed this fix).

SUGGESTION:
=========
Would it be possible to identify Activities that have an IntentFilter and check to see if it also has the Exported=true attribute before running the App Center test?  If so a nice user friendly Warning in the beginning of the App Center test task would help us solve the problem without needing to reach out to your support team.

Thanks.

**Comment by konstantin-bobkov** [comment]
Hello, @DP-Technology-LLC! As I understood, your main point is about verbosity of the build error? We are planning the release next week which will provide error details (such as Android 12 Exported flag issue) instead of "Stalled Error" message. Would it satisfy your request?

I believe the error persisted because your tests tried to run on Android 12 device(s). It is not possible without exported flag explicitly described.

More in the Android [docs](https://developer.android.com/about/versions/12/behavior-changes-12).

**Comment by konstantin-bobkov** [comment]
@DP-Technology-LLC, aforementioned release has been deployed. I hope now you can see a root cause in the logs.

**Comment by DP-Technology-LLC** [comment]
A more detailed message would be great!

Thanks.
