### ISSUE TITLE
Please add ability to pass the filename to  Error and Crash Attachments instead of pushing RAW data

### ISSUE THREAD

**Issue by SiarheiFrunchak** [microsoft/appcenter#2367]
**Describe the solution you'd like**
In the current situation when we meet OOM crashes or work with low-end devices operation with sending raw data as an attachment to AppCenter report looks o expensive. It will be more useful to pass the filename as an attachment to the report to reduce the cost of this operation for the end device.

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! 
You can send file name via [properties](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#handled-errors) or [text attachments](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/ios#add-attachments-to-a-crash-report) instead of file attachments.
