### ISSUE TITLE
https://appcenter.ms/ in China mainland not accessible 

### ISSUE THREAD

**Issue by kingnight** [microsoft/appcenter#2410]
**Describe the solution you'd like**
https://appcenter.ms/ in China mainland not accessible for several days

**Describe alternatives you've considered**

**Additional context**

**Comment by DmitriyKirakosyan** [comment]
Hi @kingnight , thank you for reaching out to us!

Unfortunately we cannot guarantee that AppCenter works in all countries, due to country specific policies and law. See [Data residency and sovereignty](https://docs.microsoft.com/en-us/appcenter/general/app-center-security#data-residency-and-sovereignty).

Closing this issue. Feel free to ask any additional questions.
