### ISSUE TITLE
Xamarin.UITest is not able to enter text for Acr.UserDialogs box on Samsung Devices

### ISSUE THREAD

**Issue by Moshex** [microsoft/appcenter#2426]
I am having an issue where both `app.ClearText()` and `app.EnterText()` is not working for Acr.UserDialogs box on Samsung  Devices (see attached screenshot) however works on Pixel. I am not sure what I can do to work around this, I have already tried to use `app.Query(e => e.Id("custom").Invoke("setText", string.Empty)) ` and this is not working as well. I have found no way that Xamarin.UITest is able to change the text of these dialog boxes and I am really hoping there is a workaround or something I am missing. Thank you for your help in advance

![Screenshot_20220610-071351](https://user-images.githubusercontent.com/6087936/173144606-9e0f1fd9-32fd-43c1-a4ea-a3e9a926cc82.jpg)

**Comment by DmitriyKirakosyan** [comment]
Hi @Moshex , thank you for getting in touch with us!

What Xamarin.UITest version do you use in your android project?
Do you experience this issue locally or when running tests on the AppCenter portal?

**Comment by Moshex** [comment]
I am on the latest version of Xamarin.UITest which as of today is version 3.2.8.
and I do see the issue both locally and on app center with just Samsung devices as stated.
Thank you @DmitriyKirakosyan for your help on this!

**Comment by DmitriyKirakosyan** [comment]
Hi @Moshex , I was able to repro and test your scenario with the `Acr.UserDialogs`. `App.SetText` doesn't work as the item is not focused and as you already figured out, you need to use a query.
Your query doesn't work because `e.Id("custom")` is not an `EditText` element but its container. So modifying query to `app.Query(e => e.Id("custom").Descendant().Invoke("setText", string.Empty))` should work for you.

There is a useful tool [app.Repl()](https://docs.microsoft.com/appcenter/test-cloud/frameworks/uitest/features/repl), which you can use to trigger a xamarin uitest terminal and perform/test commands in it.

I'm closing this issue, but feel free to reopen if you have additional questions.

**Comment by Moshex** [comment]
@DmitriyKirakosyan  Thank you for your reply I did not realize that `.Descendant()` was needed for this case since on the Pixel it does not require that to be able to interact with the box. However, your solution does work and I thank you so much for that! 

Also, I use [app.Repl()](https://docs.microsoft.com/appcenter/test-cloud/frameworks/uitest/features/repl) all the time and love the tool, I was just not able to troubleshoot why I was getting stuck in this case.

Thank you once again!
