### ISSUE TITLE
Xamarin.UITest, Android and macOS azure hosted agents 20220815.1 or later generating black screenshots

### ISSUE THREAD

**Issue by jeromelaban** [microsoft/appcenter#2460]
I'm currently running Xamarin.UITest "local" tests using Azure Devops hosted agents, and they've been working for years without trouble, up until a few days ago, when macOS agents hosted agents bumped to the `20220815.1` version.

Using `AndroidApp.TakeScreenshot();` now randomly generates completely black colored screenshots, without much reason. The only part that may have changed (and is related to screenshot taking, since it' using Java for that in Xamarin.UITest) is the JDK which went from `Java_Temurin-Hotspot_jdk/8.0.332-9` to `Java_Temurin-Hotspot_jdk/8.0.345-1`.

I'm posting this in search of anyone who would have seen a similar behavior, of it's a known issue.

**Comment by DmitriyKirakosyan** [comment]
Hi @jeromelaban , thank you for reaching out to us!

Please contact our [support team](https://docs.microsoft.com/en-us/appcenter/help) using the "?" (question mark) button on the AppCenter main page.
They will able to consult with the backend team and investigate your case.

Since this is not a feature request, I'm closing this issue.
