### ISSUE TITLE
allow to increase the build watchdog timeout

### ISSUE THREAD

**Issue by vonovak** [microsoft/appcenter#279]
Currently, appcenter builds taking longer than one hour are automatically killed.

As our e2e test suite expands, we'll arrive at a point when one hour will not be enough for our build pipeline (even though we use test parallelization). That will, of course, be a showstopper for us. It'd be nice if the timeout was customizable.

**Comment by vonovak** [comment]
@nrajpurkar I see you were assigned - is there any ETA on this? Thanks.

**Comment by nrajpurkar** [comment]
Hi @vonovak, thanks for checking in. There is no current ETA on this, but I can understand how this could be an issue as you begin to expand your test suite. We'll keep this open as something to continue looking into.

**Comment by othorin** [comment]
Why is there even a limit? The pricing page clearly states that it should be unlimited.

> Each paid build comes with unlimited build time, ensuring all builds run and complete. 

https://visualstudio.microsoft.com/app-center/pricing/

**Comment by vonovak** [comment]
just as a follow up, we ended up migrating e2e tests to gitlab CI and it works really well for us. It's great to be able to use the "merge when pipeline passes" button :)

**Comment by othorin** [comment]
Nice! Our problem is compiling lots of c++ code for multiple ABIs. Would like to avoid setting up another CI solution to pre-compile libraries...

**Comment by viewpnt1** [comment]
We are experiencing iOS builds getting killed after exactly 30:06. Anyone knows if this has been changed?

**Comment by devshorts** [comment]
It's ridiculous that this isn't configurable.  Builds take what builds take. If we want to pay for more build time let us

**Comment by eghrari** [comment]
> It's ridiculous that this isn't configurable. Builds take what builds take. If we want to pay for more build time let us

100%

Even worse is that the builds are slower at certain times of day because Microsoft's server's are busier. So basically, we can't build during the day using CI. This is negating the whole purpose of using their solution.

So now I have to retry builds 10 times, using 600 hours of build time, instead of just making the timeout 90 minutes (or whatever).

I would understand if we were on the free tier. Like devhosrts mentioned, I'm even willing to pay more to have longer build times. Setting configurable build timeouts up to some reasonable threshold should be a feature that it takes 1 week for Microsoft to build and test.

How can we get this feature request escalated because I can't imagine they think its ok to a) eat up more cpu and b) lose customers over this silly limitation they put in place.

**Comment by maciej-lepb** [comment]
Just bumping it - it's currently a blocking issue for our team. Builds failing precisely at 60-minute thresholds on a paid plan.

**Comment by shllg** [comment]
Without any bigger code changes, our builds went from ~45min per build to now stopping at 60 minutes. It's crazy since we cannot control the resources or build times. Still, we're getting billed for "using" the service. We would like to avoid to switch to another service. Are there any updates?

**Comment by krszwsk** [comment]
Similar case here. We have to switch to a different CI/CD provider, it takes 40 minutes to build our iOS 80% of the times, but in the other 20% it takes over 60 minutes for no apparent reason, so our builds are randomly timing out. It's frustrating enough to have the builds be a lot longer at random, the fact that we can't even control the 60 minutes limit is now becoming a deal breaker.

**Comment by shllg** [comment]
After getting in touch with the support, we've been told to set up a pipeline with azure on our own since they cannot change the 60min limit. They told us, that the appcenter stack is build on azure pipelines but they cannot provide the actual pipeline configuration to make a setup easier... sad.

We were forced to rebuild the whole pipeline. Using the azure build in tools brought a lot of issues to when working with react-native.

At the end, we now built our pipeline with fastlane again. At least, we can now switch from azure if we need to.

**Comment by othorin** [comment]
Still need it

**Comment by johnmbklein** [comment]
Our team also needs this. Building a React Native iOS app typically takes 40-50 minutes but will timeout at 60 minutes about 20% of the time. Having builds randomly timeout is really problematic for a paid service.

**Comment by krszwsk** [comment]
@johnmbklein we've switched to bitrise.io and we're more than happy with what we're getting from them, not looking back to the lack of customisation and flexibility AppCenter offers

**Comment by KishCom** [comment]
> After getting in touch with the support, we've been told to set up a pipeline with azure on our own since they cannot change the 60min limit. They told us, that the appcenter stack is build on azure pipelines but they cannot provide the actual pipeline configuration to make a setup easier... sad.
> 
> We were forced to rebuild the whole pipeline. Using the azure build in tools brought a lot of issues to when working with react-native.
> 
> At the end, we now built our pipeline with fastlane again. At least, we can now switch from azure if we need to.

This is insane.

Is there really no other way to change the 60m build timeout? Even for paying users? Without having to build our own Azure pipeline?

**Comment by billnbell** [comment]
2 things. Give us an export/import into azure pipelines. Or allow us to pay to go to 90 minutes or 120 minutes.

**Comment by ppohja** [comment]
Progress of this issued has been so long stalled. My company, and probably many before us, and many after us, are focusing for searching the better foundations for providing conceptually rigid solution.

**Comment by Antoine-Mace** [comment]
@billnbell looks like there is an import/export option https://docs.microsoft.com/en-us/appcenter/build/export-to-azure-pipelines

**Comment by nzcodarnoc** [comment]
This limit is affecting my ability to deliver in my job. MS pls.

**Comment by billnbell** [comment]
Again, export to Azure and run from there. If you need help let me know. And No I dont work for MS.
