### ISSUE TITLE
CodePush to include bundling of pdfs and videos

### ISSUE THREAD

**Issue by BbFGE** [Microsoft/appcenter#29]
Appliles to AppCenter CodePush 

When developing Cordova apps, CodePush allows us to roll out changes to the app HTML, Javascript and images.

It would be extremely useful for this is include pdfs and videos ie that would be included as part of the downloaded package that could be stored and accessed locally by the app (eg if the device is offline).

Alternatives include using FileTansfer plugins or XMLHttpRequest but these require extra coding and downloading at run time, rather than just when CodePush sends an update.

**Comment by patniko** [comment]
Thanks for the feedback @BbFGE! I know this is possible for React Native if you edit the bundler config to pick up files with additional extensions, but will have to look into Cordova. Technically our backend for CodePush expects a zip with files in it so there isn't a direct limitation built-in.

**Comment by patniko** [comment]
Ran some quick tests @BbFGE and can confirm this works with Cordova currently today. If you put the files into your main Cordova project and run a build the pdf's and videos should get copied to your publish folder and packaged up by CodePush.

I wouldn't necessarily recommend this if the files are large because we don't do block level diffing (only file diffs), but it is definitely doable.

Going to close this for now as it is possible across React Native and Cordova platforms.
