### ISSUE TITLE
Project builds for UWP 

### ISSUE THREAD

**Issue by mattleibow** [microsoft/appcenter#296]
**Describe the solution you'd like**
I would like to be able to select a .csproj file to build rather than a full solution.

Right now I can only select a .sln file. For typical Xamarin.Forms mobile apps, I'd have Android, iOS and UWP. If the UWP builds everything it takes forever. And it is unnecessary. 

**Describe alternatives you've considered**
As a workaround, I created a a second solution that just has the UWP app and it's related projects. 

This makes my repository look uncool 😎

**Additional context**
The UWP builds do seem very slow. Android and iOS take single digit minutes. UWP appears to take upwards of 15 for a simple forms app build.

**Comment by khoduley** [comment]
Have the same issue( for iOS and Android everything's all right.

**Comment by nrajpurkar** [comment]
Thanks for filing this feature request! We'll keep this open to track as we continue to prioritize what we work on next

**Comment by hschmidt99** [comment]
Is this still being considered? Our build times for UWP explode...

**Comment by jpm1** [comment]
I have the same issue, The support team gave me a workaround by disabling IOS and Android release builds in the Visual Studio solution file but being able to create an App Center UWP build on a .CSPROJ file instead of a .SLN would help.

**Comment by potudopotudo** [comment]
I really need this feature too. Some solutions have more than 15 projects when you only need to build 1 of it. Add a combobox with checkboxes where you can select the projects to build. 

Thanks!

**Comment by potudopotudo** [comment]
I'm having a big problem in here, because I'm using a mono-repo for android, windows and UWP projects, so this basically doesn't work at all, if you want to build an Android project it fails because there are Windows projects; if you want to build a UWP project fails because there are some Android projects there... please this is of paramount importance otherwise this is unusable, and not worth paying premium mode for AppCenter if I can't build a thing there.

**Comment by mnxamdev** [comment]
We're having issues in App Center that seem to be caused by the fact that we can't select a CSPROJ. I have a separate SLN which only includes necessary shared projects for UWP in the root of the repo but that doesn't work as well as our Android and iOS builds since App Center allows for selection of a CSPROJ for building. I don't know what the difference is but it seems to be problematic when selecting a SLN file. The problem we're seeing is that UWP builds using the SLN file located in the root of repository actually looks at everything in the root of the repository during builds and causes issues.

**Comment by Samit-BTE** [comment]
Any update on this will be appreciates.

**Comment by DennisWelu** [comment]
I haven't been able to build the main UWP apps I work on in app center for a couple years now. Even with trying to create a dedicated trimmed down SLN it just times out at 30 minutes. The project builds locally on my machine in about 5 minutes.

**Comment by potudopotudo** [comment]
I wouldn't expect any feedback on this, probably they'll ditch UWP soon in favour of MAUI, so they are probably not doing any investments on this.
