### ISSUE TITLE
Xamarin.iOS crash report doesn't include user ID

### ISSUE THREAD

**Issue by ArtyomVoronov** [Microsoft/appcenter#301]
**What App Center service does this affect?**
Crashes

**Describe the bug**
User Id and custom properties set on app start. 
Crash reports for Android contain all the information.
Crash reports for iOS don't contain user Id and custom properties.  

**To Reproduce**
1. Add code to set UserId on app start
2. Launch the app
3. Throw a test crash
4. Check crash reports

**Expected behavior**
Crash reports for iOS contain user Id and custom properties. 

**Additional context**
The app is based on the MvvmCross framework.

**Comment by Jhultink** [comment]
Also seeing this same bug using Xamarin.Forms. https://github.com/Microsoft/AppCenter-SDK-DotNet/issues/871

**Comment by elamalani** [comment]
@ArtyomVoronov @Jhultink Thanks for reporting this bug. We will investigate this issue and keep you posted.

**Comment by ArtyomVoronov** [comment]
I set user id after initialize.

**Comment by annakocheshkova** [comment]
Thank you for providing that info @ArtyomVoronov. I think I've managed to reproduce your issue and determine the root cause of it. The thing is, you misuse `NotifyConfirmationHandler`. 
If you don't implement confirmation handler that tells the sdk to wait for user confirmation before sending crashes data, there's no need to call this: `Crashes.NotifyUserConfirmation(UserConfirmation.AlwaysSend);`.

And, vice versa, if you had the following lines in your code:
```
Crashes.ShouldAwaitUserConfirmation = () =>
{
    return true;
};
```
Then you should have implemented a user dialog asking user whether to send the crashes or not. For more information I recommend you to refer to [Xamarin Crashes documentation](https://docs.microsoft.com/en-us/appcenter/sdk/crashes/xamarin#ask-for-the-users-consent-to-send-a-crash-log). There's also a link to an example there.

And many thanks for your assistance! We have a few more customers complaining about setUserId, I think they might have the same issue.

**Comment by annakocheshkova** [comment]
Hey @ArtyomVoronov just a friendly ping, did you manage to resolve your issue?

**Comment by sledderGIT** [comment]
Hi I faced the same issue and your solution helped. But now I had another issue. I can't figure out if ConfirmationHandler will be called or not. Appcenter API doesn't provide any method to determine if there are any crash reports available. Only Crashes.HasCrashedInLastSessionAsync(); but crash could be not in previous session so I can't rely on this method.

**Comment by ArtyomVoronov** [comment]
@annakocheshkova Yes, removing `Crashes.NotifyUserConfirmation(UserConfirmation.AlwaysSend);` solved the problem. Thank you!
