### ISSUE TITLE
Crashes are not appearing as JIRA tickets

### ISSUE THREAD

**Issue by admin-altrooz** [Microsoft/appcenter#302]
AppCenter and JIRA are integrated as per https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/, and the Services panel shows JIRA as "connected".  Crashes are appearing in the Diagnostics page but they are not being recorded as JIRA tickets.  What can we do?

**Comment by amchew** [comment]
Hey @admin-altrooz, thanks for reaching out! We'll need to collect more information about your app name etc to debug further. Could you go to App Center, click the bottom right-hand corner and copy paste this issue here, and ask to be transferred to Amanda? I'll take it up from there. 

Message in this GitHub issue once you've done that too.

**Comment by admin-altrooz** [comment]
Requested the transfer, thanks.

**Comment by amchew** [comment]
Hey! I received your ticket, and am getting our engineers to take a look at it. Will get back shortly.

**Comment by admin-altrooz** [comment]
Hi Amanda, can you check on the status of this?  Thanks.

**Comment by admin-altrooz** [comment]
Heard back from Yoann, and the resolution is that the component field cannot be required in the JIRA workflow since it is not provided by AppCenter during ticket creation.
