### ISSUE TITLE
Support for testing Push notifications on iOS

### ISSUE THREAD

**Issue by cmautosanity** [microsoft/appcenter#390]
Hi,
I'm using AppCenter for testing my IOS app (Appium+Java) and found that I'm not getting push notifications while I should get.
I got this message from your support group:
"Currently App Center Test doesn't have any direct support for testing Push notifications on iOS. The apps are resigned with XTC profiles which strips any entitlements / provisions for APNS."

The point is that this is very important for us (I guess for every one who test his app) this push issue, we can't keep doing if this feature is missing.

Can you please find your way and support it, thanks you.
Lior

**Comment by Oddj0b** [comment]
Thanks for your request,

I want to provide a counter-proposal as a solution. As App Center tests is a service for scaling your UI tests across our +3000 devices it's testing framework isn't suitable for testing your push backend. Instead of testing your backend through a UI test I would recommend mocking the push notification and focus on testing your apps UI.
And another point is that when you select a device, let's say, iPhone 8 on iOS 12.2 it's actually part of a pool with multiple devices, so sending the push to the right device would be close to impossible.

**Comment by cmautosanity** [comment]
Hi, thanks for your answer.
I'm not testing the back but the front, I need to verify in the UI few issues after the push message so it's important anyway.
Also, in my Android app it's works as expected.
I didn't saw anything about what app center can or can't do so whay you say it's not suitable for testing push?

**Comment by Oddj0b** [comment]
Unfortunately, receiving push notifications for iOS in a device cloud is difficult because of how Apples re-signing works. Which is why I recommended to mock-up the push notifications for your testing builds, this will remove time issues if you run the test on multiple devices.

**Comment by Oddj0b** [comment]
Hi @cmautosanity,

I will be closing this feature request after doing investigations with the engineering team we found it extremely hard to implement due to the limitations fo Apples re-signing system. I refer to my previous comment about mocking the push notification and focus on testing the UI with App Center Test.
