### ISSUE TITLE
Build emails have a broken application icon

### ISSUE THREAD

**Issue by tonyarnold** [microsoft/appcenter#391]
**What App Center service does this affect?**

Build emails, release emails.

**Describe the bug**

The application icon linked to from the email is hosted at https://rink.hockeyapp.net/api/2/apps/2e0d1bd645fd4a98a659e9d7b75b580e?format=png

This image does not exist for apps that have been created directly on App Center.

**Screenshots**

<img width="985" alt="image" src="https://user-images.githubusercontent.com/4802/57359054-13b51100-71ba-11e9-9d91-aca173ab9ea7.png">

**Comment by DennisPan** [comment]
Thanks for reporting this @tonyarnold ! I remember we've had issues with icons in emails before. But I thought we've resolved them. So this could be something new.

However, I haven't heard similar issues on this recently. So this could be something specific to your app. Do you mind reaching out to our support (via the Intercom chat bubble at bottom right of the portal) so that we can collect more information and take a deeper look?

As for the icons being stored in HockeyApp, that's same for all other apps right now, because at this point we still use HockeyApp as backend for part of Distribution, which is where icon is extracted and stored.

**Comment by tonyarnold** [comment]
This app hasn't been on HockeyApp for years, and was never associated with the emails/accounts I'm using now. Given that: how could it draw _any_ information (icons or otherwise) from Hockey? 

I've reported the issue here - why do I also need to go through support? They're super useful, but they're just going to direct me back to this issue, right?

**Comment by DennisPan** [comment]
@tonyarnold Support will be able to collect more details of your application, which allows us to perform deeper investigation if needed. 

As for you question on HockeyApp, I tried to explain in my last reply but sounds like it didn’t help. This is implementation detail on our end. Most likely is irrelevant with the issue you are seeing.

**Comment by tonyarnold** [comment]
Ok, thanks for the additional information. I've opened a support request as you suggested.

**Comment by DennisPan** [comment]
Close this as this is being discussed over support. Let us know if you run into anything else.
