### ISSUE TITLE
API - Get list of active users.

### ISSUE THREAD

**Issue by FelipeGatti** [microsoft/appcenter#445]
**Describe the solution you'd like**
I'd like to have an endpoint at the API that would show me all the active user's so i can handle the push notification via users_id correctly.

**Describe alternatives you've considered**
For now i'll keep sending push notifications to users that are not currently active but in order to handle resources better this functionality would help.

**Additional context**
I've got a problem where clients can clear the cache from their cellphones and therefore they don't follow the logout path wich clears them from my database... so in those cases i'll be firing some unecessary push notifications to all those users.

**Comment by jwargo** [comment]
@FelipeGatti Are we talking about user identities set using the SDK, or App Center Auth?

**Comment by FelipeGatti** [comment]
Sorry for the delayed response!

Via SDK @jwargo , when the user login into the app i retrieve an unique id and use the following:

`AppCenter.setUserId(UID);`

wich is loaded using `import AppCenter from 'appcenter';`.

**Comment by jwargo** [comment]
@FelipeGatti OK, thanks for that clarification. As I understand it, that capability is not on our roadmap due to some technical limitations. Our recommendation is for you to send the User ID to your app backend at the same time you set it through the SDK, then you'll have a repository with all the User IDs associated with your app.

**Comment by FelipeGatti** [comment]
Ok, thanks for the response !

Thats what i'm currently doing but when de app gets uninstalled or the user clears the cache before logging out the logout path is not followed so i cant clear that id in my database.

It's not a big deal but when i'm in another backend application that will fire those push notifications it checks in this same database, so there will be an lost call to the api with an id that is not currently set to any mobile therefore unnecessary.

**Comment by jwargo** [comment]
@FelipeGatti OK, I understand your need here and I'm trying to figure out what we can do to help you. What you really need is an uninstall event and a cache clearing event on the device you can hook and take care of this yourself (in the app) when the user acts. Unfortunately this isn't possible as I understand it. 

The problem for us is that we don't **know** whether the device is actually inactive. We know we haven't heard from the device in a while, but we don't really know what the user did with the app.  Giving you a list of users doesn't really solve your problem because you still have to process the whole list against your internal list of users. We don't have a way to give you this list today (and, like I said, I'm not sure it's really possible) and you'd have a lot of work to do on the backend to process this list. With that in mind, wouldn't this be easier?

Every time your user opens your app, you notify your backend (send a date/time value or some sort of semaphore) and store it with the user ID in your backend. Then, write a scheduled tasks (daily for example) that purges user IDs from your system after ## days. Wouldn't that be easier?

**Comment by FelipeGatti** [comment]
@jwargo, thank you again for taking time to evaluate and consider my feature request.

Oh, I thought you could figure out if an user is reachable or not before even sending the notification.

Actually I haven't thought in anything like your method and It could work well, I will try this way.
