### ISSUE TITLE
Build is experiencing problems because of a backend issue that may lead to longer than expected queue times - please try again later

### ISSUE THREAD

**Issue by mpghelli** [microsoft/appcenter#490]
Build is experiencing problems because of a backend issue that may lead to longer than expected queue times - please try again later

**Comment by DennisPan** [comment]
@mpghelli could you clarify a bit more what are you looking for? This message is currently shown in Build service, because there is an ongoing incident.

**Comment by mpghelli** [comment]
I can't generate builds anymore

**Comment by DennisPan** [comment]
The incident should be mitigated now. Could you give this another try?

If you need additional assistance, please feel free to reach out to support (via the chat bubble at bottom right of the portal).

I removed the "bug" label from the Issue because this is not exactly a "bug". I'm also going to close this as we have an active incident tracking this.
