### ISSUE TITLE
Short Push Survey

### ISSUE THREAD

**Issue by jwargo** [microsoft/appcenter#491]
Ensuring we're offering the right capabilities to our Push customers, this issue is basically a research project - we're asking your help to better understand how you use App Center Push in your applications.  In the comments, please answer the following questions:

How does your app use notifications?

- Alert the app to take an action (notification triggers new data pull from server)
- Alert the app user about some new data available in the app (when the user opens the app, the data refreshes and updates the UI)
- Deliver promotion or reminder to the user (marketing stuff)
- Send data to the app (notification payload contains data the app uses)
- Other (please specify)
 
How do you target notifications?

- Audiences
- Broadcasts (notify all devices)
- Specific devices
- Users

Finally, what additional features would you like to see in App Center Push?

**Comment by KSemenenko** [comment]
**How does your app use notifications?**
1.  Alert the app to take an action (but now it will work only when user will tap on popupbage)
2. Alert the app user about some new data available in the app ( I need silent push for iOS and Android)
3. Send data to the app (but it's small data)

**How do you target notifications?**
1. Users  ( 90% of pushes)
2. Specific devices (10% of pushes)

**Comment by ChrisMGilbert** [comment]
**How does your app use notifications?**

1. Alert the user to updates within the app
2. Alert the user that the app installed on another device has altered the state of the data within this device i.e. Global logout on device A has logged out devices B & C

**How do you target notifications?**

1. 100% Device - Due to the fairly minimal push quota limitations, we are having to push exclusively by devices in small bursts. If we attempt to push by Audiences or Broadcast we will almost immediately hit the max devices/user limit and the system doesn't fail gracefully, it simply stops sending the messages. In this instance, according the your technical support, the recipients are non-deterministic so we can't even begin to guess who has and who has not received the push notification.

**Finally, what additional features would you like to see in App Center Push?**

1. The ability to **accurately** know when an app has been removed from a device or unsubscribed from the PNS. Currently I will send a notification to a device that I **know** has been uninstalled, the push will fail and yet the export devices API endpoint will still return that device as being registered more than 8 days later. According to App Center Support, this is not correct.
2. More accurate indication as to whether or not a push notification has been successful.

**Comment by NunoBem** [comment]
**How does your app use notifications?**

1. Alert the user of an incoming/outgoing request

**How do you target notifications?**

1. Specific devices (100% of pushes). We have 2 situations. We have some users that access an backoffice. They are register in our own database, but has we're using Auth too, we're going to start testing to push to 'user'. Regular users we don't have a login, so it will always be device specific.

**Finally, what additional features would you like to see in App Center Push?**

1. **Important** - Get notifications when app is not running

**Comment by martelart** [comment]
How does your app use notifications?

- Alert the app user about some new data available in the app (when the user opens the app, the data refreshes and updates the UI)
- Deliver promotion or reminder to the user (marketing stuff)

How do you target notifications?

- Broadcasts (notify all devices)
- Specific devices
- Users

Finally, what additional features would you like to see in App Center Push?

- Extended SDK for more push capability, such as in-app-push-notifications cross platform.
- One root app in App Center for Xamarin Forms apps, to reduce amount of API calls

**Comment by jwargo** [comment]
Silent notifications are on our roadmap, trying to get that one sorted out now. On top of that, we're looking at adding more capabilities to the SDK. 

@martelart how do you see in-app notifications working? That's built into the mobile platforms, what value add does App Center add to that equation?

**Comment by martelart** [comment]
@jwargo Currently it is required to write platform specific code add multiple classes for supporting default in app notifications 

in ios we can reach that by 

> UNNotificationPresentationOptions.Alert
> UNUserNotificationCenterDelegate

and in android by

> NotificationManager

Talking about a push message drops from top shows up a few seconds even the user using the app at the moment. I just wish not implementing them seperately in a Xamarin.Forms app, but just set in App.xaml.cs to receive and show push notification.

**Comment by jwargo** [comment]
@martelart OK, thanks for the clarification. App Center wouldn’t be in involved in this as it’s just a local SDK item. but I’ll talk with the team. It may be better served by the Xamarin team, perhaps I’ll ask them.

**Comment by jamesmontemagno** [comment]
@martelart are you talking about this stuff here: https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios#common-tasks-for-push-notifications
