### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by miktap** [microsoft/appcenter#503]
**Describe the solution you'd like**
I would like to build my UWP application on a Visual Studio 2019 agent. Configuring the build so that the agent could be selected based on the Visual Studio version would be the ultimate goal as most likely upgrading all agents to Visual Studio 2019 would brake some other user builds.

**Describe alternatives you've considered**
I could try Azure Pipelines as Visual Studio 2019 seems to be supported there. Or I could change my app so that it builds on Visual Studio 2017 (which App Center agents currently seem to use).

**Comment by nrajpurkar** [comment]
Thanks for this feature request @miktap! We've been starting to look into this. Out of curiosity, is it important for you to be able to select between VS 2019 and VS 2017 for builds or would just having support for VS 2019 be enough?

**Comment by miktap** [comment]
Support for VS 2019 is enough for me. Thanks!

**Comment by charlesroddie** [comment]
What's the status of this? This is a problem on Windows (VS2019) and also Mac. Our Android builds are failing because the build chain on Mac is not updated.

We started using F# 4.7 features as soon as VS2019 was released, and this was not a problem on Azure DevOps as that was updated straight away, but builds are still failing on App Center.

**Comment by seankanderson** [comment]
+1 Same here.  I'm on the bleeding edge with Xamarin Forms UWP/Android, so having 2019 build agent support would take a lot of the "build-and-pray" out of my development cycle.  I have had to wrestle with issues where my local builds would not build on AppCenter.

**Comment by nrajpurkar** [comment]
As an update here, we're looking to switch from VS 2017 agents to VS 2019 agents by mid-February.

**Comment by aphunclearwave** [comment]
+1 Thank you! Same here. Also, thanks for the update @nrajpurkar!
We're trying to build a UWP app in App Center. For development, our machines are using Visual Studio Pro for mac and Visual Studio 2019 for Windows. We don't get any errors when building from our machines but we get an error `Fody is only supported on MSBuild 16 and above. Current version: 15.`  We use Fody on our code and will try downgrading it to a previous version in order to make the app build on App Center but only for now.

**Comment by hiraldesai** [comment]
+1 on this. @nilofer, is mid-February for this still on track? The reason I ask is because I had opened a ticket about a failing UWP build on 1/10 and I was told by intercom support engineer to open an issue because there was no plan to support VS2019 in the pipeline. This is the exact response I received.

> App Center currently only supports building UWP apps with Visual Studio 2017. As you have discovered, the version of .NET Core you are targeting is not supported by this version of Visual Studio. At this time, that means you can't use App Center for building this app.
> Please consider opening a feature request so we can determine how many people are looking for this to work. We track feature requests here: 
> I had a look for similar requests, but did not find any that cover your request exactly.
> I'll close this issue now since requests for new features are handled through the GitHub repository.
>

**Comment by kmatthijssen** [comment]
Hello, any update on this? we are looking forward to use AppCenter for our deployments of visual studio 2019 apps

**Comment by nilofer** [comment]
@hiraldesai @kmatthijssen, apologies for that response from support. This is still on our roadmap and our team will pick this up in the coming week. We may slip into the following week, but aiming to get this done soon.

**Comment by chrisweihu** [comment]
Any latest update for add VS 2019 support in AppCenter? When will be the next release fix?  We are encountering UWP compiler errors ONLY on AppCenter build because it is using VS2017. Our build works fine on VS2019. 
This is the Error. This happened after we added EntityFrameworkCore.SQLite nugget.
`Error CS7069: Reference to type 'IAsyncDisposable' claims it is defined in 'netstandard', but it could not be found`

**Comment by King-of-Spades** [comment]
VS 2019 support was added on approximately March 5th: https://github.com/MicrosoftDocs/appcenter-docs/commit/48fe3b6282e3484c32eae24a025f60a45e634fba
