### ISSUE TITLE
Make push results easier to understand

### ISSUE THREAD

**Issue by adrianknight89** [microsoft/appcenter#506]
**Describe the solution you'd like**
When I see the list of push notifications on the portal, I get confused by "0/0" below the Results column. What is the meaning of this? Does it mean the push failed to send? What about "0/1"?

![Capture](https://user-images.githubusercontent.com/16855542/58745724-31bd0c80-841a-11e9-86cd-b7891b95f58c.PNG)

**Comment by jwargo** [comment]
@adrianknight89 what this is indicating is a ratio of the number of messages sent against the number of devices in the target audience. 

Assuming your target audience had 100 devices in it, 37/100 means the message was sent to 37 out of the total audience of 100 target devices.   it's showing what would be the percentage calculation if you were to do it (37% sent).  0/0 means no messages were sent since the target audience (the second number) was an audience of zero. 0/1 means no messages were sent to an audience of 1. 

When you look at a multi-step wizard, you'll see something on the page indicating 1/3 - meaning you've seen 1 out of 3 (a simple ratio) of the available wizard pages, 2/3, 3/3, etc. That's what we're doing here and it's a common approach.  How are you proposing we show this more clearly?

**Comment by jwargo** [comment]
@adrianknight89 looking at this again, there's clearly disparity between target and results. I'll have the designer take a look and do what I can to clean this up.

**Comment by adrianknight89** [comment]
@jwargo Thanks for your response. In what situation does a target audience of zero device make sense? This is what I'm confused about. Shouldn't this number be 1 at minimum? Tying back to #505, I send a push to an Android device (after registering a UserId), but I keep seeing 0/0 results. Surprisingly, if I send a push on the portal to all audiences, the SDK recognizes the registered device (and I did verify my UserId is correct). So, I'm wondering if somehow the SDK is overwriting the user id with null or something else.

**Comment by jwargo** [comment]
@adrianknight89 yes, it does make sense - it's possible that your audience doesn't result in any devices. for example, if your audience targets US devices and there are no registered devices from the US, then your audience size would be 0.

**Comment by jwargo** [comment]
i'm working with our design team to give this UI a bit of love, I'll let you know when I have something to show.

**Comment by jwargo** [comment]
@adrianknight89 Thank you very much for your feedback on App Center Push. We announced yesterday in a [blog post]( https://devblogs.microsoft.com/appcenter/app-center-mbaas-retirement/) that we’re retiring the Push service later this year and recommending customers transition to Azure Notification Hubs instead. The good news is that the same team operates both App Center Push and Azure Notification Hubs, so all customer feedback and feature requests have been transferred to the Azure Notification Hubs roadmap.
