### ISSUE TITLE
AppCenter Push stops working when the app crashes

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#537]
Hi,

When I open the app and then it crash for whatever reason and then I send a Push message then no message will be received so user needs to open the app again first in order to get the messages.

**Comment by jwargo** [comment]
@jrahma have you discussed this issue with our support team?  I'm not sure exactly what's going on here, but I'd like to rule out other issues before treating this as a bug. If the app's crashing, the the SDK's not going to be able to process the incoming message; it feels like this is expected behavior. Reloading the app resets the SDK and that's how you're getting the messages.

**Comment by jrahma** [comment]
But this is an issue because the messaging should work in the background no matter what and what if the app crashes and the user did not start the app again for few days? then he is going to lose all the incoming messages?

**Comment by jwargo** [comment]
@jrahma I understand, it should, but if a crashed app puts the SDK into an unstable state, it may be out of our control. That's why I'm asking you to work with our support team to resolve the issue, if possible. 

This is not expected behavior for our SDK and we'd like to collect more information before we address the bug and the support team is the best way for us to do that (our engineers work closely with support)

**Comment by jwargo** [comment]
@jrahma did you connect with our support team on this?

**Comment by jrahma** [comment]
This problem seems to be resolved now. Thank you so much
