### ISSUE TITLE
Delete all events at once

### ISSUE THREAD

**Issue by Balu2** [microsoft/appcenter#58]
Like deleting push notifications all at once, I like to the option to delete events all at once as well. Especially when you have generated a lot of events during development of an app, it is a lot of work to delete all those events one by one.

**Comment by joemellin** [comment]
Hello @Balu2! Thanks for posting this feature request. We will keep this issue open to track further interest in providing this feature.  

For other users, please upvote the initial message with a 👍if you would like this feature as well.

**Comment by wisoka** [comment]
👍

**Comment by Hurricane31337** [comment]
Any update on this? We just migrated to App Center and also find it annoying to delete every event one by one – especially when you also have to type out its event name in order to delete it...

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1693115/98835888-4ab85280-2441-11eb-81a8-669b83fb6810.png">

**Comment by lndr27** [comment]
> Any update on this? We just migrated to App Center and also find it annoying to delete every event one by one – especially when you also have to type out its event name in order to delete it...
> 
> <img alt="image" width="570" src="https://user-images.githubusercontent.com/1693115/98835888-4ab85280-2441-11eb-81a8-669b83fb6810.png">

I ended up using the [App Center API](https://openapi.appcenter.ms/#/analytics/Analytics_EventsDeleteLogs) to loop through the events and delete them.
