### ISSUE TITLE
Need to Easily Link from App Center Crash to Individual Bug

### ISSUE THREAD

**Issue by WhiteDog12** [microsoft/appcenter#597]
Need to make it easy to link from App Center crash reports back to DevOps bugs that are automatically created.   In Hockey App, it was easy to link back to the bug system.  You could open a crash group, then select the bug tracker and click the URL to go to the specific bug in the bug tracking system.  I can't seem to find this same URL/process in App Center.  We have setup the bug tracker integration already (https://docs.microsoft.com/en-us/appcenter/dashboard/bugtracker/).  
![image](https://user-images.githubusercontent.com/1944408/59851728-9b01b280-932a-11e9-9091-a7cdb980ae22.png)

**Comment by winnieli1208** [comment]
@WhiteDog12 thanks for the feature request. This is great feedback and I can definitely see the value in including the bug tracker link somewhere in the App Center UI. Due to other priorities at the moment, we don't have immediate plans to address this but I will monitor this thread and post any updates.

Thanks!

**Comment by joehanna** [comment]
All these little paper cuts are frustrating. Why on earth were we kicked off a solid, feature rich platform like HockeyApp when AppCenter is no where near feature parity? We should have been given another year so AppCenter can catch up.
