### ISSUE TITLE
Please give us more info when push notifications fail to be delivered

### ISSUE THREAD

**Issue by adrianknight89** [microsoft/appcenter#617]
When a push is not delivered, I'd like to see more information as to why that was the case. Here's one example when I see nothing but "Bad channel".

![11](https://user-images.githubusercontent.com/16855542/59966161-df817f80-94dd-11e9-897d-f4acbfa9f4cf.PNG)

**Comment by ChrisMGilbert** [comment]
I totally agree. It's completely ridiculous that there is basically no way of telling whether or not a notification push has failed in a large number of cases.

**Comment by amchew** [comment]
Thanks @adrianknight89, @ChrisMGilbert for the feature request! I'll let @jwargo share more details about this.

**Comment by jwargo** [comment]
@adrianknight89 and @ChrisMGilbert With these types of errors, we don't have a lot of additional information. We just get a bad channel error back from the PNS, so that's what we display.  We're considering adding an additional info link that points to the docs, but what else are you looking for here?

**Comment by jerryhuang-net** [comment]
You might be only got back a bad channel error from PNS, but you do know what parameters you sent to the PNS that completely hidden from developers. What is the token? When the token registered? etc. If you think of you were the developer and you received only bad channel, what would you like to know in order to get it works? It seems there isn't too much control by the developers, in the app we only call Start(typeof(Push)), if it's working it's great but when it doesn't, how we suppose to fix with just "bad channel"? BTW this is exactly happening to me. I'm considering switching to other platform because of this.

**Comment by jwargo** [comment]
@jerryhuang-net you have the ability to grab the token and store it away so you know what it is and when it was made. Bad channel essentially means the token expired: https://docs.microsoft.com/en-us/appcenter/push/troubleshooting#bad-channel. You can no longer use it to send to that device. As I understand it, we remove bad tokens once we know they're bad, so this will clean up over time. There's nothing we can do to prevent this though because one of the ways a channel goes bad is when the user uninstalls the app or installs a new version. We do try to clean it up as best we can.
