### ISSUE TITLE
custom build steps are skipped when using NodeJS Current instead of LTS

### ISSUE THREAD

**Issue by dkocich** [microsoft/appcenter#623]
**What App Center service does this affect?**
Web user interface for pipeline configuration.

**Describe the bug**
I have a project where I have React Native with these MS Appcenter packages:
    "appcenter": "2.0.0",
    "appcenter-analytics": "2.0.0",
    "appcenter-crashes": "2.0.0",

In the build configuration, I used `Node.js version: 12.x` which caused that my custom build scripts were ignored during the pipeline run but the web UI showed that they were recognized.

![image](https://user-images.githubusercontent.com/6165660/60026788-8f045080-969c-11e9-9e35-9542719d7db3.png)

When I switched back to `Node LTS 10.x`, I can see that those scripts were run in the pipeline log...
 
**Expected behavior**
It should work for NodeJS 12.x or at least a message should be visible in pipeline configuration (or in the docs) saying that custom build scripts are available only for LTS version of NodeJS...

**Comment by DennisPan** [comment]
@dkocich We've had customers reporting similar bugs before (custom scripts not running), and most of the time it was because the branch configuration wasn't saved. Not saying that's the case here. Just calling out a common scenario we've seen. Could you reach out to support (via App Center portal) so that we can look into details?

**Comment by nrajpurkar** [comment]
@dkocich were you able to get this resolved via support?
