### ISSUE TITLE
Android Push Notifications

### ISSUE THREAD

**Issue by hhasenauer** [microsoft/appcenter#635]
**What App Center service does this affect?**
PushNotifications for Android Cordova

**Describe the bug**
Reinstalling the same android app multiple times results in push notifications "Bad Channel" errors.
For development reasons, the app is installed multiple times on the same device and a new install id is generated each time. 
When a push notification is sent to this new install id I get this error:
![image](https://user-images.githubusercontent.com/16212806/60186167-89894080-982b-11e9-8789-7813997c573d.png)
Sometimes the problem seems to resolve itself, but now I am stuck and cannot get it to work at all anymore (even after numerous re-installs)

**To Reproduce**
1. Re-install the android app or clear app data from the device
2. Retrieve new install id from the device
3. Send a push notification via app center to the new install id

**Expected behavior**
The push notification is sent to the device.

**Smartphone (please complete the following information):**
 - Device: Medion E5005
 - OS: Android 6

**Comment by jwargo** [comment]
@hhasenauer have you worked with our support team on this to validate that it's actually a bug? I'm checking to see what this error means.

**Comment by jwargo** [comment]
@hhasenauer I checked with engineering and this error could be a number of issues including invalid app initialization, please reach out to our support team and they'll help you through it. If it turns out it is a bug, we'll track it and manage it on the backend.

App Center support is provided directly from within the App Center portal. Any time you need help, just click the blue chat button in the lower-right corner of any page and our dedicated support team will respond. For additional information, see the [App Center Help Center](https://intercom.help/appcenter/getting-started/welcome-to-app-center-support).
