### ISSUE TITLE
Push Notification Registration tidy up custom timeout

### ISSUE THREAD

**Issue by ChrisMGilbert** [microsoft/appcenter#648]
**Describe the solution you'd like**
It would be beneficial for app developers to be able to set a custom duration after which the Push Notification registration is tidied up within App Center.
Developers know more about their apps and how they are used than App Center and this arbitrary length of time seems unhelpful

As it currently stands, according to App Center Support "We tidy up registrations upon two criteria, the first one is that **your app has not been used in the past 90 days on the device**. The second criteria for removing a registration is if the PNS tried to send to the device and received invalid feedback indicating the app has been uninstalled."

**Describe alternatives you've considered**
I don't see that there is an alternative if your app is only likely to be used once a year for example.

**Additional context**
Some apps are used on a second by second basis and some are only opened after a long delay or weeks or even months. 
Our app may only be opened once per year and then used for an extended period of between a few days up to a few weeks. We need to be able to push notifications in the meantime without fearing that the device has been automatically removed from the system.

**Comment by jwargo** [comment]
@ChrisMGilbert thanks for this suggestion, I'll track it as a feature request. Just to make sure I'm clear, you're talking about the device registration, right? Not a notification. 

Since we don't know if a user uninstalls an app, we can't know a device token is invalid until we try to send to it. Since the App Center SDK automatically refreshes the token on startup, that's how we're able to implement the automatic purge (assuming if the user hasn't opened the app, they're not using it). 

So what I hear you asking for is the ability to set a flag that says don't delete at 90 days, or the ability to set a expiration date?

**Comment by ChrisMGilbert** [comment]
> the ability to set a flag that says don't delete at 90 days, or the ability to set a expiration date?

Yes exactly this. 

Thanks

**Comment by jwargo** [comment]
@ChrisMGilbert I’ll take this into consideration, but I’m not sure its possible - I imagine the platform token will expire before then. If the user may open the app only once a year, then push notifications may not be the right approach.
