### ISSUE TITLE
Distribution of unity  standalone applications on window as .zip

### ISSUE THREAD

**Issue by christopheph** [microsoft/appcenter#711]
We would like to be able to distribute unity (or wathever type of standalone) applications on windows with as a .zip container.

**Additional context**
It is possible to upload a .zip file, but AppCenter does not recognize it because no versioning info is present .

**Comment by lumaxis** [comment]
Thanks @christopheph ! This does sound similar to some of the other open issues we already have but I don't think any cover this flow specifically, and especially not for Unity.
I know @winnieli1208, @jphenow, et al were looking at a flow that let's you specific the version info manually. Maybe they can comment on this 🙂

**Comment by chrisaswain** [comment]
We would like to be able to upload zipped UWP packages.  HockeyApp currently allows this and it is part of our existing flow.

**Comment by ringleader3** [comment]
our current UWP workflow on hockeyapp involves uploading a ZIP of all the artifacts of a app store build, so that QA can get the dependencies and other important files.  I hope that this functionality is preserved in app center by allowing uploads of zip files, and creation of 'app version' via the browser UI

**Comment by winnieli1** [comment]
Hey all - we just enabled support for releasing .zip for Unity Windows apps. Note you will need to manually specify the build version in the release flow. Thanks!
