### ISSUE TITLE
Tests failing due to iOS 12.3.1 Update Popup

### ISSUE THREAD

**Issue by Naishy** [microsoft/appcenter#720]
**What App Center service does this affect?**
Test

**Describe the bug**
Modal popup notification for iOS 12.3.1 upgrade is appearing and blocking all tests.

**To Reproduce**
Run tests with AppCenter

**Expected behavior**
Update notifications to not be displayed or automatically dismissed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1101674/61285786-78dc4280-a7b9-11e9-901e-4facfe6fb6ef.png)

**Desktop (please complete the following information):*
N/A

**Smartphone (please complete the following information):**
 - Device: [iPhone 7]
 - OS: [iOS 12.1.4]
 - Browser [N/A]
 - Version [N/A]

**Additional context**

**Comment by King-of-Spades** [comment]
Hi, thanks for the report. For this type of issue, we need to be able to view the backend logging details in order to identify which of our iPhone 7 - iOS 12.1.4 instances are impacted by the behavior, so we can fix them directly. 

We can determine this if you share links to your affected test runs. If you prefer not to share those links in this public channel, then you can share them by logging into https://appcenter.ms/apps and either:
- Clicking the chat icon in the lower right corner of the screen. https://www.screencast.com/t/uF8S5o0o0
OR
- Clicking **? > Contact Us** in the upper right corner of the screen.
