### ISSUE TITLE
Encrypted environment variables corrupted

### ISSUE THREAD

**Issue by nschild** [microsoft/appcenter#764]
**What App Center service does this affect?**
Website

**Describe the bug**
During our last build, of our 72 apps that use the same GitHub repo, 7 failed due to a corrupt encrypted environment variable. Resetting the environment variable in the build configuration allowed the build to succeed. We have been experiencing this randomly happening to random apps for some time now.

**To Reproduce**

**Expected behavior**
All the apps to successfully rebuild without environment variable errors.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Also, when configuring the build for a new branch, when cloning from existing, the system will not import the encrypted environment variables correctly.

**Comment by DennisPan** [comment]
@nschild Indeed we introduced a bug two weeks ago that can be related. If the branch configuration was saved when the bug was there, secret variables need to be re-entered. Apology for the inconvenience. This shouldn't happen anymore. If you would like to confirm whether that is what caused the issue, please contact our support via App Center portal, which will allow us to collect your app information and double check.

**Comment by tarun29061990** [comment]
Hey
I am getting *** instead of the value in pre-build script for ios? please help

**Comment by nschild** [comment]
@tarun29061990 This is the exact bug they claim they fixed months ago, lol. We ended up not encrypting any variables as it seemed to randomly break for us.

**Comment by DennisPan** [comment]
@tarun29061990  Secrets are masked in logs. If you need to print the secrets, you can print substring. 

@nschild Happy to look into more what's not working for you. I'm not aware of recent issues with secrets. If you reach out to support, we can take a deeper look.
