### ISSUE TITLE
possible GDPR problem

### ISSUE THREAD

**Issue by roger-olier-sb** [microsoft/appcenter#775]
Hi!
On unity, it seems that app center is sending some data BEFORE it gets to the scene with "app center behaviour".
Can we know what kind of data is sending, and, if possible, block it?

Thanks a lot for your help

**Comment by derpixeldan** [comment]
Can you please provide more information? The bug template helps us to triage issues.

**What App Center service does this affect?**
Name of service or sdk with the issue.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**

**Comment by roger-olier-sb** [comment]
**What App Center service does this affect?**
AppCenterEditorExtensions-v1.1.2.unitypackage

**Describe the bug**
When we open the app and we stay on a scene that has not yet called the app center behaviour, we can see that app center is sending some data to https://in.appcenter.ms

**To Reproduce**
Open the app but ensure that "App Center Behaviour" has not yet been called

Expected behavior
No data must be send before we use "App Center Behaviour", to ensure that we comply with GDPR (we must ask for user consent before we send any data outside the app

Screenshots
![app center](https://user-images.githubusercontent.com/23254913/61939959-bcdafe80-af94-11e9-8e2e-df27fa9354db.PNG)
You can see here the call

Smartphone (please complete the following information):

    Device: all ios and android devices
    OS: all os
    Version -v1.1.2

**Comment by annakocheshkova** [comment]
Hi @roger-olier-sb, the data being sent is "startSession" and "startService" events. If you want to ask user consent first, you can delay the start of App Center.
For this, add **AppCenterBehaviourAdvanced** to the game object and check the **Start native SDK from app** checkboxes. 
![image](https://user-images.githubusercontent.com/34677812/61957960-1a893e00-afc9-11e9-9945-d48ddc231e17.png)

**Comment by roger-olier-sb** [comment]
Thanks a lot!
