### ISSUE TITLE
Labels / tags for releases

### ISSUE THREAD

**Issue by a-uz** [microsoft/appcenter#78]
**Describe the solution you'd like**
Labels / tags for releases that are released to distribution groups. Similar to the ones that GitHub issues have. Labels could be automatically assigned or proposed based on the branch they were built on. These could be useful by both the administrators and testers. Administrators would have a better overview of what's distributed. Testers would be able to find releases faster.

**Describe alternatives you've considered**
As an administrator I'm using the branch name / release notes to identify for what environment / purpose the release is for, but there's no quick overview of that. I could use different distribution groups to identify them, but managing multiple groups for the same people could be quite time consuming.

**Additional context**
Testers for the application I'm working on are often quite confused when opening the site for accessing the releases, just because there are too many of them. Many of which have the same version number. To further limit the options they have to open them to find differences in the release notes.

**Comment by Aidurber** [comment]
App Center is an integral part of our workflow and our QA team are also having issues identifying the source of a release. 

Internally we use a branch structure such as: 

- support (bug fixes)
- test (feature development QA)
- release (our release candidate for major releases)

Currently we're struggling with helping the QA team determine what version they are testing, the release notes can be helpful if they have context and the version numbers aren't helpful since they're all the same. The alternative on our end would be to have different targets and flavours per branch and add a ribbon to indicate which, but that's harder to maintain and isn't ideal. We have 4 apps - each of which support both Android and iOS. 

We would love ❤️labels for our releases.

**Comment by Aidurber** [comment]
Just another thing about this, if you're installing through https://install.appcenter.ms/ you can see the branch name which is helpful. A minimum viable change for this to address (at least our) issues would be for the emails to include the branch name in the subject, body, or both. 

Our QA team usually relies on the emails.

**Comment by botatoes** [comment]
Hi there, we've introduced release types in appcenter.ms. It currently exists in the appcenter.ms UI and API and we are planning on supporting additional UI for testers.

**Comment by hari331996** [comment]
> Hi there, we've introduced release types in appcenter.ms. It currently exists in the appcenter.ms UI and API and we are planning on supporting additional UI for testers.

Do we have this available for appcenter-cli too?
