### ISSUE TITLE
Custom release notes for manual builds

### ISSUE THREAD

**Issue by istvanp** [microsoft/appcenter#81]
**Describe the solution you'd like**
When I create a manual build, I would like the option to add my release notes to it so that when the build is done, the release notes will be the text I entered instead of the last commit message.

**Describe alternatives you've considered**
_(positives and negatives in parens)_

**1) Best outcome, most frustrating:** Disable automatic distribution, create a manual build, wait for the build to finish (`---`), edit the release notes and then distribute.

**2) Less than ideal outcome but allows me to get the build out asap:** Leave automatic distribution on, wait for the the build to finish (`-`), build finishes and gets distributed with an email with the commit message as the release notes (`-`), edit the release notes at your convenience (`+`) but hope you edit the notes in time before your QA team asks what's in the build because commit messages like "_Merge branch xyz into abc_" isn't always the best description or a complete summary of the release (`---`) 😅 

**Additional context**
None.

**Comment by istvanp** [comment]
I would note that the TestFlight distributions already allows you to do just this :ok_hand:

**Comment by nrajpurkar** [comment]
Hear ya that those workarounds are less than ideal. What would a good solution look like for you? Would you want a file that you check in that has the release notes to be picked up and populated when your automatic build kicks off?

**Comment by istvanp** [comment]
If I'm using a manual build, having the Release Notes field in the build config window like the TestFlight one would be perfect. For automated builds, I'm guessing the best thing would be to use the `CHANGELOG.md` file and take the content under the first `h2` header (until the 2nd `h2` header) or something to that effect. Dumber version would be to take the entire `release_notes.txt` contents.

**Comment by ferdicus** [comment]
Would also be cool to have the option to overwrite this / do this via the appcenter-cli tools `appcenter build queue` command. 

Currently it's just triggers a build without any options.

**Comment by phoney** [comment]
I only do manual builds. When I submit to TestFlight there's a text field for the Release Notes as part of the distribution step. This exact UI should populate the Release Notes that are sent to Distribution Groups. 

It should also be possible to edit the Release Notes later and have emails sent to the Distribution Group without creating a new release. HockeyApp does this.

**Comment by ElteHupkes** [comment]
I don't want to hijack this issue, but I would be a big fan of being able to specify release notes for automated builds. The most simple option would be to just have a text file that, if exists, would be used to populate the release notes. Everyone can use their own pre-build logic to populate that file. Alternatively, a new build script of which the output is used for release notes would work just fine as well.

**Comment by crrobinson14** [comment]
There is a way to do this via the API but it doesn't work. It fails parsing newlines, even if they're escaped. The issue was first reported here https://github.com/Microsoft/appcenter/issues/210 and auto-closed for no response but is NOT resolved. Attempting to include multi-line release notes via the API call returns the following error, no matter what combination of newline-escaping I try. (It works if I include only a single line, but that's pretty useless.)

```

API call failed with 400: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>SyntaxError: Unexpected token <br> in JSON at position 82<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/home/node/data/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /home/node/data/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/home/node/data/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/home/node/data/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/home/node/data/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:203:15)<br> &nbsp; &nbsp;at IncomingMessage.EventEmitter.emit (domain.js:466:23)<br> &nbsp; &nbsp;at endReadableNT (_stream_readable.js:1145:12)<br> &nbsp; &nbsp;at process._tickCallback (internal/process/next_tick.js:63:19)</pre>
</body>
</html>
```

**Comment by ElteHupkes** [comment]
Updating the release notes through the API in a build script is something I hadn't yet considered - good to know that it wouldn't work XD.

**Comment by mnxamdev** [comment]
Allowing for a release-notes file is the best idea as it should cover all bases without needing to build out new UI. Regarding your last point, I created the following feature request to allow to tap into a post deployment script. If we had this we could just run a script following successful deployment to update the latest App Center built distribution.
https://github.com/microsoft/appcenter/issues/1989

> I don't want to hijack this issue, but I would be a big fan of being able to specify release notes for automated builds. The most simple option would be to just have a text file that, if exists, would be used to populate the release notes. Everyone can use their own pre-build logic to populate that file. Alternatively, a new build script of which the output is used for release notes would work just fine as well.

**Comment by crrobinson14** [comment]
It's stale because it's not addressed, msftbot, not because it's not wanted.

**Comment by lemessur** [comment]
Yeah. This is one of those obvious 1.0 type features. It’s completely ridiculous that it still has not been implemented even years later. 

My guess is that most companies have either developed their own jury-rigged workaround solution by now or have few enough apps (like us) that it’s not too much of a pain to just handle manually.

**Comment by lemessur** [comment]
This is a really really obvious basic feature that should have been included in the initial launch of the product. Why has it not been implemented yet?!

**Comment by hrodrick** [comment]
At the moment this feature is not implemented and we can not use a custom release notes/changelog using the Distribute section in the CI/CD configuration. BUT as a workaround we can create a custom **post-build script** and use App center's CLI to distribute the application using a release-notes file with markdown enabled.

You need to do some things : 
 * 1 :  Create an appcenter-post-build.sh file in the module/project you are building, and copy the code from this gist, which I am actually using in my projects and is working:
https://gist.github.com/hrodrick/2a88b4cc84eaf169dd1eb77c50c1099c
 * 2 : Create a changelog.md file at the same level. Describe there your new features/fixes (or whatever you want)
 * 3 : Check in Appcenter if your CI/CD configuration detects your post-build script. Like the image below, if it is not detected, you created the files in the wrong folder. Refer to the link in the "build scripts" section if you can not find where to place the files.
<img width="738" alt="Screen Shot 2021-10-29 at 16 16 59" src="https://user-images.githubusercontent.com/26490822/139699931-13838660-e3c4-49b7-90aa-4aa14268a23e.png">
 * 4 : Create the environment variables used in the script with your own configuration, as shown below :
<img width="531" alt="appcenter-params" src="https://user-images.githubusercontent.com/26490822/139701086-d6d8dd62-036f-4859-b82e-1f09624f6c74.png">
In the image the DISTRIBUTE_GROUP is defined as "QA", so the QA group will receive the release.

The CHANGELOG_FILE just have the name of the file (changelog.md) because it is at se same level as the script.

There is an environment variable called MOBILE_CENTER_CURRENT_APP. It is important because it is used by the CLI to know what application is distributing. The value is the application's Owner followed by an slash followed by the application's name.

Finally the CLI_LOGIN_TOKEN variable's value is a user token which can be created directly in the user settings. Do not confuse it with the application's token (that happened to me 😄)
 * 5 : **Disable Distribute** in the CI/CD configuration. This is because we are now distributing using the CLI in a custom script. If we left Distribute enabled the release will be distributed twice, and we only need it one.
 
And now all the releases will take your custom changelog.md content and format it with markdown. Here is an example of an E-mail distribution :
<img width="379" alt="Screen Shot 2021-11-01 at 13 07 01" src="https://user-images.githubusercontent.com/26490822/139703331-84c99d30-0758-44da-85b1-419b23cb2461.png">

Develop the workaround was not so easy because the documentation is a little poor and does not explain this kind of stuff. Hope it can help.

**Comment by ElteHupkes** [comment]
Thanks for sharing that @hrodrick, I personally actually need multiple languages in my release notes, something I don't think App Center supports at all at the moment, so I'm stuck doing it manually anyway. Otherwise I'd definitely consider using this. 

Seems like it shouldn't be too much work to implement in the main interface, so I guess this isn't a priority for the team ATM.
