### ISSUE TITLE
LogFlow is not Realtime!

### ISSUE THREAD

**Issue by jrahma** [microsoft/appcenter#828]
Hi,

The Log Flow is not showing data in realtime, most of the times it takes minutes to come and even after minutes you will have to refresh the screen which is not called real time

This is what I also received from te support team

![LogFlow](https://user-images.githubusercontent.com/6236241/62532728-23de9a00-b856-11e9-8698-0bcb28e2fd84.png)

Hope to fix this to show it in realtime

Thanks,
[Jassim](https://maxmon.softnames.com)

**Comment by hamswan** [comment]
Is this occurring for a specific app?

In order to populate the log flow page, you will need to:
Open the Log Flow page and wait a few seconds
Start sending logs from your device
No previous logs will show unless this workflow above was done earlier in the same day (in the UTC timezone). Also, this process will need to be done again after 10 minutes of the page not being in focus.
