### ISSUE TITLE
Auth.SignInAsync() - the SDK will not show the sign-in UI again

### ISSUE THREAD

**Issue by rodbassatgatech** [microsoft/appcenter#830]
@amchew I am using Xamarin Forms.  In my iOS app it is prompting me with the sign-on UI every time I call Auth.SignInAsync.  It is behaving as expected in my Android app.  What am I missing in my iOS app?

**Comment by amchew** [comment]
Hi @rodbassatgatech, thanks for letting us know! We'll get back shortly. Apologies for missing this.

**Comment by amchew** [comment]
Hi @rodbassatgatech, we believe that you're seeing this error because there may be something missing in your **Entitlements.plist** file for build type and device for Debug/Release and iPhones/iPhone simulator combinations. May I check if you have done this step: https://docs.microsoft.com/en-us/appcenter/sdk/auth/xamarin#add-keychain-sharing-capability for all the Debug/Release and iPhones/iPhone simulator combinations?

**Comment by rodbassatgatech** [comment]
Yes, that was it.  I had different settings for build/device combinations.  Thanks @amchew

**Comment by amchew** [comment]
No worries! :)
