### ISSUE TITLE
Support for Baidu Push Notifications 

### ISSUE THREAD

**Issue by KenrickV-Hexaware** [microsoft/appcenter#836]
**Describe the solution you'd like**
Our solution needs to support China where Google is banned. Hence we were hoping for App Center to have support for Baidu (like Azure Notification Hub!)

**Describe alternatives you've considered**
Our alternate solution would be to use Azure Notification Hub or AWS SNS

**Comment by amchew** [comment]
Thanks @KenrickV-Hexaware for the feature request! @jwargo would you mind taking a look?

**Comment by jwargo** [comment]
@KenrickV-Hexaware as we understand it, Baidu is shutting down that service, but we're still researching this to confirm. Customers told us Baidu is not accepting new customers or projects and for that reason we deprecated the Baidu sample on the Notification Hubs side because we couldn't even test it. 

For that reason, we have no plans for adding this to App Center today. The only option we're aware of right now is Azure Notification Hubs.
