### ISSUE TITLE
WPF Azure DevOps AppCenter Support

### ISSUE THREAD

**Issue by kpatwa** [microsoft/appcenter#852]
Will you guys be adding support for WPF application in the “Deploy to App Center” Azure DevOps component as well ? I think, currently it supports .ipa and .apk file only.

https://docs.microsoft.com/en-us/appcenter/distribution/vsts-deploy

**Comment by ameasor** [comment]
another vote for WPF deployment. Something we use massively with Hockey.

**Comment by rfellers** [comment]
another vote for WPF deployment from Azure DevOps. We'd love to AppCenter in place of Azure DevOps' Release pipelines ...

**Comment by winnie** [comment]
Hey sorry for the delay! We recently added support for .msi and .zip files in the Azure DevOps + App Center distribute task. Are there requests for any other package types?

**Comment by rfellers** [comment]
No worries on the delay and thanks for the follow up, now I'm the one behind! Please ignore my earlier request: I was not aware that WPF on .NET Core 3.x is fully supported and that this issue is likely related to WPF classic. I followed a wonderful guide [here](https://github.com/microsoft/AppConsult-WinAppsModernizationWorkshop/tree/master/Exercise6) and I'm up and running with App Center + Azure DevOps + WPF .NET Core using an .appxbundle file and your build task.

**Comment by winnie** [comment]
Glad to hear everything is working! I'm closing this issue but don't hesitate to reach out if you have any other questions or requests.
