### ISSUE TITLE
Reported issue doesn't appear in dashboard

### ISSUE THREAD

**Issue by ozzeye-playrix** [microsoft/appcenter#856]
**What App Center service does this affect?**
AppCenter ios SDK: 1.13.1

**Describe the bug**
App center sent logs successfully but there is no issue in dashboard

**To Reproduce**
1. Add AppCenter SDK to ios app instead of HockeySDK
2. Crash ios app
3. After relaunch app sent logs successfully (didSucceedSendingErrorReport called)
4. Go to dashboard in Diagnostics tab
5. There is no reported issue

**Expected behavior**
Sent issue appears in dashboard

**Smartphone (please complete the following information):**
 - Device: iPa (2017) (5th gen)
 - OS: iOS 12.3.1
 - Browser Chrome
 - Version 75.0.3770.142

**Note:**
* App transited from Hockey recently
* Issues from hockey are moved automatically from application with Hockey App SDK
* When logs are sent by debug application - they appear in dashboard in unsymbolicated tab

**Comment by lumaxis** [comment]
@ozzeye-playrix There was an issue earlier today where the App Center ingestion service was not properly working: https://status.appcenter.ms/incidents/7vcg4k0fb1c2
That problem was fixed now and the service is operating nominally again but it might take some additional time for all logs to be processed.

Can you wait a bit and check if the log shows up later today or by tomorrow?

**Comment by ozzeye-playrix** [comment]
There are still no new reports and the behavior remains the same
Tried with release version.
Tried with debug version:
1) Install Debug App
2) Run without debugger
3) Crash app
4) Run with debugger
5) See attached log [AppCenter Log.txt](https://github.com/microsoft/appcenter/files/3491429/AppCenter.Log.txt)

**Comment by ozzeye-playrix** [comment]
Problem solved. Thank you!
