### ISSUE TITLE
Android tests occasionally seem to crash from internal exceptions not related to our application 

### ISSUE THREAD

**Issue by PureWeen** [microsoft/appcenter#893]
**What App Center service does this affect?**
App Center Android UI tests

**Describe the bug**
Occasionally we are seeing crashes on random UI tests with crash logs that don't seem to correlate to any of our code

https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/AndroidControlGallery-1/test/series/pull-7032/runs/b826dc16-ee86-49f1-b5c4-0367526b5359/170-2-0/18824604-e78c-49aa-afc5-e384ed8305e6/logs

https://appcenter.ms/orgs/xtc-Xamarin-Forms/apps/AndroidControlGallery-1/test/series/pull-6762/runs/5f8151a9-35a0-4b15-bda9-62ca0a42bb16/83-0-0/18824604-e78c-49aa-afc5-e384ed8305e6/logs

It's never a consistent test that causes this exception and 100% of the time I can rerun the exact same tests and it'll eventually (usually on the first rerun) pass 

I checked the device logs as well and there are no Unhandled Exceptions in there.  The stack trace almost looks like the UI Test code is determining that the app isn't running so it kills the app but then it doesn't restart it fast enough for the UI tests to run? 

**Expected behavior**
It seems like these crashes shouldn't be happening and aren't a fault of the application. If it is a fault of the application then the exception should have more detail about what in the application is crashing. 

**Smartphone (please complete the following information):**
 - Device: Android

**Additional context**
https://xamarinhq.slack.com/archives/C24DVRZ7U/p1565633285117300

**Comment by Oddj0b** [comment]
Thank you for reporting the issues, our DRI will look into it.

**Comment by john7doe** [comment]
The crash in the test report is deep in the (native) code of android. The code path is triggered by the testserver processing a query from your test. The test server is running inside the same process as your application. There is no way we can catch the error/signal so the app process is terminated and as a result thereof the test fails since it cannot communicate with the test server. 

Since the crash occurs in libandroid_runtime.so I do not think there is much we can do to mitigate it

**Comment by PureWeen** [comment]
Looks like the crash was caused by by this https://github.com/mono/mono/issues/9314

We set our GC BRIDGE to new from Tarjan and everything works now

Thank you @john7doe for looking into this!!
