### ISSUE TITLE
WinForms build support

### ISSUE THREAD

**Issue by floele** [microsoft/appcenter#908]
I noticed that WPF build support has already been requested but did not find a request for WinForms yet (https://github.com/microsoft/appcenter/issues/85).

WinForms should have build support as well. I tried the app center the first time today and I don't really see much value for a WinForms/WPF app currently without these time saving features.

**Comment by winnieli1208** [comment]
Thanks for the feature request! We don't have immediate plans to support building WinForms apps but it's something we are definitely considering. 

We started with distribute, diagnostics, and analytics support for WPF/WinForms apps because those were the top requested services at the time. I'll monitor this thread for community support and post here with any updates. In the meantime, I recommend using Azure DevOps for building your WinForms apps. Thanks!

**Comment by floele** [comment]
@winnieli1208 Hi, thanks for considering my request. I'm not sure if a call is really necessary, my use case is quite easily explained unless you need in-depth details.

I have a WinForms app (also on Github by now https://github.com/canneverbe/Ketarin) that I would like to build and distribute to my users automatically. When I stumbled upon the App Center website I thought that's what it does. And it does indeed, except that it doesn't for WinForms projects.

The workflow I would have in mind is:
- Build and package the app after every commit (or after a certain time has passed and changes have been detected). appveyor build is in fact already configured.
- Allow me to select one of the generated packages to release it (by generating a download link).

As far as I can see, this is exactly what has already been implemented in App Center, even with support for multiple groups of people (in order to distribute to enthusiasts or beta testers for example). 
I could imagine additional features like automatically converting the output and distribute to the app store as well, but I suppose that's a different story.
