### ISSUE TITLE
Data support for multi model document

### ISSUE THREAD

**Issue by fileman** [microsoft/appcenter#946]
**Describe the solution you'd like**
Since Cosmos DB is multi model, I'm trying to have different type of document stored in same UserPartition, but Data.ListAsync<T> return all items in UserPartition, even they are X, Y class.

**Describe alternatives you've considered**
- Multiple user partition by append string to DefaultPartitions.UserDocuments + "T" #681 
- Add a property with class name and use it as discriminator (EF Core CosmosDB Provider has something similar)

**Comment by fileman** [comment]
any news about this?

**Comment by Zakeelm** [comment]
Hi @fileman apologies for the delayed response. I'd like to discuss more about your scenario. Are you essentially asking for better filter support within the List command?

**Comment by fileman** [comment]
Hi @Zakeelm no problem, I'll try to explain better what I mean, while 
if DefaultPartitions.UserDocuments contains 2 ClassX and 3 ClassY, if I use `Data.ListAsync<ClassX>(DefaultPartitions.UserDocuments);` return all items in DefaultPartitions.UserDocuments instead of only 2 ClassX items.

In general using the same approach of EF Core CosmosDB provider can be usefull for access this items from other platform not supported by AppCenter, like asp.net core mvc / blazor

**Comment by fileman** [comment]
Precisaly [this](https://docs.microsoft.com/it-it/ef/core/providers/cosmos/#embedded-entities) way:
"Id": 1,
"Discriminator": "Order",
"id": "Order|1"

**Comment by Nick92000** [comment]
I have the same problem : `Data.ListAsync<ClassX>(DefaultPartitions.UserDocuments)` returns all items in UserPartition (same with DefaultPartitions.AppDocument), regardless of what "ClassX" is.

In the doc, it is stated that "Data.ListAsync<**User**>(DefaultPartitions.UserDocuments) [...] will return a page of the documents that exist within a given user partition **that align with the User class model**."

https://docs.microsoft.com/fr-fr/appcenter/sdk/data/xamarin

That statement doesn't seem to be true from what I see, as every documents are return, regardless if they align with the provided class model or not.

Example : In my DB, in one UserDocuments partition, if I have : 
- 1 000 "Student" documents
- 1 "Professor" document

Then `Data.ListAsync<Professor>(DefaultPartitions.UserDocuments) ` returns **1 001** documents (Students + professor mixed), instead of just the one "Professor" document that truly exists.

It is possible to mitigate this issue by manually adding a dedicated property (ex : "DocumentType"="Professor") on each document. Then, on each ListAsync request, we (anormally) get all documents, but we can filter with something like this : `result.CurrentPage.Items.Select(a => a.DeserializedValue).Where(x => x.DocumentType == "Professor")) `

But that's very far from optimal, and causes a loss of performance and huge network traffic for nothing.

Or maybe I'm missing something?

**Comment by fileman** [comment]
@Zakeelm any news on this

**Comment by jimmccurdy** [comment]
I have this problem as well.  Allowing us to use the "partition" value as we wish would solve this.  We could set our partition values to be class names, and so the expected filtering could happen on the server side.  One other possible solution would be to add a new/optional string parameter as in Data.ListAsync<TT>(string partition, string idFilter = null).  Then documents could be filtered on the server side with a where clause:  *.Where(doc => idFilter== null || doc.id?.Contains(idFilter)

**Comment by RedChops** [comment]
Yeah this is a bit crazy and makes ListAsync completely useless as presented in the docs unless you're only ever storing one type of model.

Not particularly sure what the type actually 'does' in ListAsync in this case, as items are returned that don't deserialize to the class I'm expecting, giving me unfortunate empty objects mixed in with valid ones.

**Comment by RedChops** [comment]
No news on this still? I'd love some guidance on what's expected here - getting all of the documents in the user partition all the time and having to filter the full result set just doesn't seem to be what would be expected.

**Comment by jimmccurdy** [comment]
I agree with RedChops.  Is this a major design flaw?  Or can it be fixed?  It is unusable as is, and it appears that AppCenter.Data is not receiving much dev attention these days.
