### ISSUE TITLE
Notification of release failure / success (post build)

### ISSUE THREAD

**Issue by chris-cubhub** [microsoft/appcenter#956]
Please add a notification during the release process if it succeeds or fails. The notification should include the destination / environment (Test Flight, Alpha, Production iOS, etc), the release number, etc. It should also contain the logs as an attachment or a link to the release that failed. There is no obvious way to know a release failed at first glance without clicking down to the release level. 

For small apps that build and do light automated testing in AppCenter for iOS this can take up to 30 mins, so constantly checking and refreshing isn't an option. This would have saved us roughly a day of testing due since we believed the release was taking extra time in iOS when it was brought up to us that the iOS version had not come, but the Droid version did.

**Comment by chris-cubhub** [comment]
Thanks for the link. I'll definitely look into integrating those into our chat groups for the events that are possible.

Unfortunately it also seems to be missing an event for release failure. Really any kind of method would be super helpful in the case of failure, so I'd be totally happy with a webhook, email, or carrier pigeon that could be fired out of AppCenter.

**Comment by chrispaynter** [comment]
Release error notifications are as essential as the notification you get if the build fails.

For example, if the distribution to TestFlight fails because of an accidental conflicting version number, it's a critical failure, and the GUI should be highlighting this on the build itself, and there should be notification hooks to be alerted.

In common CI pipelines, the release step will fail the whole pipeline.

**Comment by chrispaynter** [comment]
Commenting so that this is not closed.

**Comment by chrispaynter** [comment]
Commenting (again) so that this is not closed.
