### ISSUE TITLE
Xamarin.Android "Generate one package(.apk) per selected ABI" option does not work

### ISSUE THREAD

**Issue by JeroenBer** [microsoft/appcenter#99]
**What App Center service does this affect?**
Xamarin.Android

**Describe the bug**
In Xamarin.Android there is a project option called "Generate one package(.apk) per selected ABI". When enabled it should generate 4 extra apk's: (arm64, armeabi, x86, x86_64). However after the app center build it is only 1 APK as output.

**To Reproduce**
Run the build. Download output.

**Expected behavior**
I expect an APK per ABI as output.

**Comment by patniko** [comment]
Hi @JeroenBer, we don't actually support this today, but have been looking at adding in support for it in the future. Switching this to a feature request for now.

**Comment by booker-dragon** [comment]
Supporting per ABI apk will be great but need to find out a way to handle the auto increment build version issue

**Comment by softlion** [comment]
You are specialized in distribution. Why don't you have this feature ? I don't understand.
In my latest project, the unified APK size is 93Mb. With the split option, it's down to 35Mb.

**Comment by aeirola** [comment]
This would also be useful for React Native builds. React Native supports splitting the build into multiple APKs https://facebook.github.io/react-native/docs/signed-apk-android#split-apks-by-abi-to-reduce-file-size

**Comment by softlion** [comment]
In fact it's no more useful. All devices are arm64 nowdays. No more x86/x86_64 or armv7a.

**Comment by danieljgmaclean** [comment]
Actually this is a much higher priority feature than is initially obvious. Google made it clear in [January](https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html) that all Apps submitted from August 1st 2019 must contain a 64bit ABI as well as the regular 32bit ABI. I expect that many Apps will be able to fit both ABI's under the 100 MB APK size limit Google impose on uploads to the Play Store i.e. as a universal APK. But, some of us have apps already very close to the 100 MB limit with only a single ABI. This problem is easily fixed i.e. just upload an APK per ABI, however App Center does not support specific APK's per ABI. Come August 2019, you may find this issue gets way more attention. If this feature isn't implemented before August 2019, I'll have to avoid using App Center for supporting Xamarin Android apps which exceed 100 MB with the 64bit and 32bit ABI's.

**Comment by toomasz** [comment]
This feature is necessary for deploying any professional android app.

**Comment by nrajpurkar** [comment]
Thanks for opening this request and the further detail. This greatly helps us when prioritizing future work! Will keep this open to track further interest.

**Comment by broderickmerritt** [comment]
I would also like to be an advocate for this. I believe this is a crucial step for contributing to the full DevOps process using AppCenter for Xamarin Forms app, especially on the part of fulfilling an optimized Google Store production deployment without manual steps.

**Comment by scastria** [comment]
But even without the multiple apk's per ABI, what about universal apk's?  When I build on my desktop, my apk is universal as it contains multiple lib/XXX for each ABI.  However, the build that App Center produces, only contains 32-bit.  How do I get App Center to generate a universal apk like my desktop?

**Comment by scastria** [comment]
I may have found the problem.  My csproj file does NOT EXPLICITLY list the AndroidSupportedAbis.  VS for Mac was showing 64 bit checked so maybe I am suffering from a problem with defaults.  With no AndroidSupportedAbis listed, VS for mac defaults 64-bit as ON, but maybe App Center defaults it to OFF.  I will explicitly add AndroidSupportedAbis in my csproj and see what happens with App Center.

**Comment by scastria** [comment]
Yes, that worked.  Sorry to bother everybody, but maybe my experience will help someone else.

**Comment by DennisPan** [comment]
Trying to understand this more. If we add support to build AAB for Xamarin.Android, is this still a critical issue to resolve?

**Comment by softlion** [comment]
If you manage to support AAB, it won't be necessary anymore.

**Comment by brodymerritt** [comment]
The primary issue to resolve here is AppCenter releases for both testing and the Google play store. If you manually upload any APK to the Google play store, it automatically shrinks the file size (even if it's over 100mb). To automate releases to the store,  we need the files to be less than 100mb - apps with many features using xamarin, this isnt likely. For AppCenter, itd be nice to build both types of apks on my build config - bundled or individual. and when I want to release to the store, if it also took the MultiAAB apk or the individual apks for each CPU type and uploaded them all into Google play for a single release shrunk (like it does if you upload manually). Currently it would overwrite each release with an individual apk and not shrink them apk - thus only making 1 apk available.

**Comment by DennisPan** [comment]
The spec and updates for the AAB work is shared in #194 . The gist is that we are working on building AAB and distribute to Store. Would love to learn additional thoughts if those aren't enough.

**Comment by MisterJimson** [comment]
One reason is distributing outside of the Play Store, like in China. No AAB support there, but we should have the option of doing both fat APKs and split APKs.

**Comment by jdepypere** [comment]
I appreciate the work that is done for AAB support in #194, but for me personally multiple apk support would still be preferred. A concern of AAB is that you need to give your signing keys to Google, since they create and sign the apk's for you. For this reason we are attempting to steer clear of AAB and split our own apk's for smaller filesizes & support for different abi's.

For us this is a deal breaker in using AppCenter for distribution for now.

**Comment by EmilAlipiev** [comment]
> One reason is distributing outside of the Play Store, like in China. No AAB support there, but we should have the option of doing both fat APKs and split APKs.

same for Amazon Store. no aab is supported there.

**Comment by othorin** [comment]
It would also be good for App Center Beta distribution of apps. Currently our universal APK is ~140MB while the ABI specific ones are ~30MB.

**Comment by jonathanantoine** [comment]
Any update on this one 😁?

**Comment by nrajpurkar** [comment]
@jonathanantoine no update to share at the moment, but we will continue to monitor this feature request!

**Comment by sim1986** [comment]
Is there any update on this item. As stated in the above comments it is extremely important to be able to upload multiple apks for different CPU architectures for a single release.

**Comment by ackava** [comment]
Xamarin.Forms apps are now failing due to size constraints, it is impossible to split apps using Bundles without reengineering entire app. As we are using many third party native libraries and it is a huge blocker now !!

**Comment by softlion** [comment]
> Xamarin.Forms apps are now failing due to size constraints, it is impossible to split apps using Bundles without reengineering entire app. As we are using many third party native libraries and it is a huge blocker now !!

Activate "link user and sdk libraries", add some preserve attributes and it will fix your issue forever

**Comment by ackava** [comment]
@softlion What makes you think we are not doing it? Does that automatically link native libraries which are compiled in c/c++ ?

**Comment by user1701** [comment]
(React Native) I'm building APK per CPU architecture, but how I can download it with universal APK from the app center. I found out that after the build process runs android-postprocess.sh that removes all ABI dependent APKs. It is a crucial feature for our project because APK size is more than 100Mb and we have to use splits. Is the feature adding arranged?

**Comment by user1701** [comment]
@patniko Do you have updates about the feature?

**Comment by ttodorov-maf** [comment]
@patniko, that's a huge blocker, please update if it's in scope at all.

**Comment by EmilAlipiev** [comment]
this needs to be reopened? !

**Comment by m-sadegh-sh** [comment]
Any update on this?
